#!/bin/sh
# gen_modules_initramfs.sh <out.inc> <module.ko>...
#
# Packages the built loadable kernel modules into the initramfs, together with
# the two index files the in-kernel request_module()/modprobe read:
#
#   modules.dep    "<module>: <dep> <dep>"   — computed from the real symbol
#                  graph: module A depends on B when an undefined symbol of A
#                  is EXPORT_SYMBOL'd by B.
#   modules.alias  "<alias>: <module>"       — every MODULE_ALIAS() tag found
#                  in the module's .modinfo section.
#
# Both are derived from the objects themselves, never from a hand-written list,
# so a new dependency or alias in the source shows up without touching a
# script.
set -eu

OUT="$1"
shift
# Kernel release, i.e. what uname(2) reports — the modules live under
# /lib/modules/<release>/ because that is where BusyBox's modprobe, modinfo and
# depmod look ($CONFIG_DEFAULT_MODULES_DIR/$(uname -r)). Defaults to the
# version header so a manual run needs no argument.
RELEASE="${RELEASE:-$(sed -n 's/.*B1NIX_VERSION_STR "\([^"]*\)".*/\1/p' \
    "$(dirname "$0")/../../kernel/include/b1nix/version.h")}"
[ -n "$RELEASE" ] || { echo "gen_modules_initramfs.sh: no kernel release" >&2; exit 1; }
[ $# -gt 0 ] || { echo "gen_modules_initramfs.sh: no modules given" >&2; exit 1; }

NM="${NM:-$(command -v llvm-nm 2>/dev/null || command -v nm)}"
OBJCOPY="${OBJCOPY:-$(command -v llvm-objcopy 2>/dev/null || command -v objcopy)}"

WORK="$(dirname "$OUT")/.modules-stage"
rm -rf "$WORK"
mkdir -p "$WORK"

MODULES=""
for ko in "$@"; do
    name="$(basename "$ko" .ko)"
    MODULES="$MODULES $name"
    # Exported symbols: EXPORT_SYMBOL() emits a "__ksymname_<sym>" string
    # object alongside each record, which is the cheapest reliable marker.
    "$NM" "$ko" | sed -n 's/.*__ksymname_//p' | sort -u > "$WORK/$name.exports"
    "$NM" -u "$ko" | awk '{print $NF}' | sort -u > "$WORK/$name.undef"
    # .modinfo is a run of NUL-terminated "key=value" records.
    "$OBJCOPY" -O binary --only-section=.modinfo "$ko" "$WORK/$name.modinfo" \
        2>/dev/null || : > "$WORK/$name.modinfo"
    tr '\0' '\n' < "$WORK/$name.modinfo" > "$WORK/$name.modinfo.txt"
done

# ── modules.dep ──
: > "$WORK/modules.dep"
for name in $MODULES; do
    deps=""
    for other in $MODULES; do
        [ "$other" = "$name" ] && continue
        if [ -s "$WORK/$other.exports" ] && \
           comm -12 "$WORK/$name.undef" "$WORK/$other.exports" | grep -q .; then
            deps="$deps $other.ko"
        fi
    done
    # depmod(8) — the BusyBox applet included — builds modules.dep from the
    # module's own "depends=" tag, so the tag has to say what the symbol graph
    # says. Compare the two and fail the build on a mismatch rather than ship an
    # index that a later `depmod` run would silently rewrite into something
    # else. (Order-insensitive: both sides are sorted names.)
    declared="$(sed -n 's/^depends=//p' "$WORK/$name.modinfo.txt" | tr ',' ' ')"
    want="$(printf '%s\n' $deps | sed 's/\.ko$//' | sort | tr '\n' ' ')"
    have="$(printf '%s\n' $declared | sort | tr '\n' ' ')"
    if [ "$want" != "$have" ]; then
        echo "gen_modules_initramfs.sh: $name declares MODULE_DEPENDS(\"$declared\")" >&2
        echo "  but its undefined symbols resolve to: $want" >&2
        echo "  fix the MODULE_DEPENDS() tag in the module source." >&2
        exit 1
    fi
    printf '%s.ko:%s\n' "$name" "$deps" >> "$WORK/modules.dep"
done

# ── modules.alias ──
: > "$WORK/modules.alias"
for name in $MODULES; do
    sed -n 's/^alias=//p' "$WORK/$name.modinfo.txt" | while read -r a; do
        [ -n "$a" ] && printf 'alias %s %s\n' "$a" "$name" >> "$WORK/modules.alias"
    done
done

# ── the .inc ──
mkdir -p "$(dirname "$OUT")"
: > "$OUT"
printf '/* Generated by tools/kernel/gen_modules_initramfs.sh — do not edit. */\n' >> "$OUT"
for ko in "$@"; do
    name="$(basename "$ko" .ko)"
    xxd -i -n "vfs_module_${name}_ko" "$ko" >> "$OUT"
done
xxd -i -n vfs_modules_dep "$WORK/modules.dep" >> "$OUT"
xxd -i -n vfs_modules_alias "$WORK/modules.alias" >> "$OUT"

printf '%s\n' '#define B1NIX_MODULE_INITRAMFS_FILES \' >> "$OUT"
for ko in "$@"; do
    name="$(basename "$ko" .ko)"
    printf '    {"/lib/modules/%s/%s.ko", (const char *)vfs_module_%s_ko, sizeof(vfs_module_%s_ko), 0},' \
        "$RELEASE" "$name" "$name" "$name" >> "$OUT"
    printf '\\\n' >> "$OUT"
done
printf '    {"/lib/modules/%s/modules.dep", (const char *)vfs_modules_dep, sizeof(vfs_modules_dep), 0},' "$RELEASE" >> "$OUT"
printf '\\\n' >> "$OUT"
printf '    {"/lib/modules/%s/modules.alias", (const char *)vfs_modules_alias, sizeof(vfs_modules_alias), 0},\n' "$RELEASE" >> "$OUT"
