#!/bin/sh
# gen_kallsyms.sh <kernel.elf>  >  kallsyms.S
#
# Emit an assembly blob mapping kernel .text addresses to function names, for
# in-kernel backtrace symbolication (M35). Reads the symbol table of an already
# linked kernel ELF (pass one of the two-pass link) with `nm -n` so entries are
# address-sorted, then writes packed records:
#
#     .quad <addr>      ; 8-byte little-endian function address
#     .asciz "<name>"   ; NUL-terminated symbol name
#
# into the `.kallsyms` section. The kernel walks these between the linker
# symbols __kallsyms_start / __kallsyms_end (see kernel/lib/klog.c ksym_lookup).
set -u
ELF="$1"
NM="${NM:-nm}"

printf '/* Auto-generated by tools/kernel/gen_kallsyms.sh — do not edit. */\n'
printf '.section .kallsyms, "a"\n'

# nm -n: numeric sort by address. Keep only text symbols (t/T) with plain C
# identifier names (skip section/local labels with odd characters).
"$NM" -n "$ELF" | awk '
  ($2 == "t" || $2 == "T") && $3 ~ /^[A-Za-z_][A-Za-z0-9_]*$/ {
    print ".quad 0x" $1;
    print ".asciz \"" $3 "\"";
  }
'
