# SPDX-License-Identifier: GPL-2.0-only
# Calamares for b1nix: Debian's installer framework, with b1nix's partition
# layout and Limine in place of Calamares' own bootloader module.
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:     b1nix-target
  module: shellprocess
  config: shellprocess-b1nix-target.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - hwclock
  - packages
  - shellprocess@b1nix-target
  - umount
- show:
  - finished

branding: b1nix
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
