/* SPDX-License-Identifier: MIT */
#ifndef LKPI_VIDEO_MIPI_DISPLAY_H
#define LKPI_VIDEO_MIPI_DISPLAY_H
/* MIPI DSI command opcodes. ABI numbers from the DSI specification, reproduced
 * as-is; only the ones the core names. */
#define MIPI_DCS_NOP           0x00
#define MIPI_DCS_SOFT_RESET    0x01
#define MIPI_DCS_ENTER_SLEEP_MODE 0x10
#define MIPI_DCS_EXIT_SLEEP_MODE  0x11
#define MIPI_DCS_SET_DISPLAY_OFF  0x28
#define MIPI_DCS_SET_DISPLAY_ON   0x29
#define MIPI_DCS_SET_COLUMN_ADDRESS 0x2a
#define MIPI_DCS_SET_PAGE_ADDRESS   0x2b
#define MIPI_DCS_WRITE_MEMORY_START 0x2c
#define MIPI_DCS_GET_DISPLAY_ID     0x04
#define MIPI_DCS_GET_POWER_MODE     0x0a
#define MIPI_DCS_GET_PIXEL_FORMAT   0x0c
#define MIPI_DCS_ENTER_INVERT_MODE  0x21
#define MIPI_DCS_EXIT_INVERT_MODE   0x20
#define MIPI_DCS_SET_TEAR_OFF       0x34
#define MIPI_DCS_SET_TEAR_ON        0x35
#define MIPI_DCS_GET_DISPLAY_STATUS 0x09
#define MIPI_DCS_GET_DISPLAY_MODE   0x0d
#define MIPI_DCS_GET_RED_CHANNEL    0x06
#define MIPI_DCS_GET_GREEN_CHANNEL  0x07
#define MIPI_DCS_GET_BLUE_CHANNEL   0x08
#define MIPI_DCS_GET_DIAGNOSTIC_RESULT 0x0f
#define MIPI_DCS_GET_SIGNAL_MODE    0x0e
#define MIPI_DCS_GET_ADDRESS_MODE   0x0b
#define MIPI_DCS_GET_SCANLINE       0x45
#define MIPI_DCS_SET_ADDRESS_MODE   0x36
#define MIPI_DCS_SET_PIXEL_FORMAT   0x3a
#define MIPI_DCS_ENTER_NORMAL_MODE  0x13
#define MIPI_DCS_ENTER_PARTIAL_MODE 0x12
#define MIPI_DCS_EXIT_IDLE_MODE     0x38
#define MIPI_DCS_ENTER_IDLE_MODE    0x39
#define MIPI_DCS_READ_MEMORY_START  0x2e
#define MIPI_DCS_READ_MEMORY_CONTINUE 0x3e
#define MIPI_DCS_WRITE_MEMORY_CONTINUE 0x3c
#define MIPI_DCS_SET_PARTIAL_ROWS   0x30
#define MIPI_DCS_SET_PARTIAL_COLUMNS 0x31
#define MIPI_DCS_SET_SCROLL_AREA    0x33
#define MIPI_DCS_SET_SCROLL_START   0x37
#define MIPI_DCS_SET_GAMMA_CURVE    0x26
#define MIPI_DCS_SET_DISPLAY_BRIGHTNESS 0x51
#define MIPI_DCS_GET_DISPLAY_BRIGHTNESS 0x52
#define MIPI_DCS_WRITE_CONTROL_DISPLAY 0x53
#define MIPI_DCS_GET_CONTROL_DISPLAY   0x54
#define MIPI_DCS_GET_POWER_SAVE        0x56
#define MIPI_DCS_WRITE_POWER_SAVE   0x55
#define MIPI_DCS_SET_CABC_MIN_BRIGHTNESS 0x5e
#define MIPI_DCS_GET_CABC_MIN_BRIGHTNESS 0x5f
#define MIPI_DCS_READ_DDB_START     0xa1
#define MIPI_DCS_READ_DDB_CONTINUE  0xa8
#endif
