#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Generate the parts of the filesystem shim that are derived from the imported
# source rather than written.
#
# So far that is one thing: the tracepoints. btrfs, ext4 and jbd2 call 231
# distinct trace_*() functions, and every one of them is a no-op in a kernel
# without ftrace. Writing 231 macros by hand would be 231 chances to miss one —
# and a missed one is not a compile error at the call site, it is an implicit
# declaration that links against nothing. Deriving them from the pinned source
# means the list cannot drift from the code that calls it.
#
# Output goes beside the staged tree, never into it: the import rule is that
# nothing under build/src/fs-<ver> is edited.

set -eu

ROOT_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
LINUX_VERSION="${LINUX_VERSION:-6.18.51}"
STAGE_DIR="$ROOT_DIR/build/src/fs-${LINUX_VERSION}"
GEN_DIR="$ROOT_DIR/build/src/fs-${LINUX_VERSION}-gen"

[ -d "$STAGE_DIR/fs" ] || { echo "gen-shim-headers: run tools/import/fs/fetch-linux-fs.sh first" >&2; exit 1; }

mkdir -p "$GEN_DIR/trace/events"

# One header per trace system, each carrying only the names its own subsystem
# calls. They could all be one file — but then a btrfs typo would be silently
# satisfied by an ext4 tracepoint of a similar name, and the point of deriving
# the list is to keep it honest.
# maple_tree comes from lib/ rather than fs/, so its source directory is named
# separately below rather than derived from the system name.
for sys in btrfs ext4 jbd2 maple_tree; do
	case "$sys" in
	maple_tree) src="$STAGE_DIR/lib" ;;
	*)          src="$STAGE_DIR/fs/$sys" ;;
	esac
	out="$GEN_DIR/trace/events/$sys.h"
	{
		echo "/* SPDX-License-Identifier: GPL-2.0-only */"
		echo "/* Generated by tools/import/fs/gen-shim-headers.sh from ${src#$STAGE_DIR/} — do not edit. */"
		echo "#ifndef B1NIX_TRACE_EVENTS_$(echo "$sys" | tr a-z A-Z)_H"
		echo "#define B1NIX_TRACE_EVENTS_$(echo "$sys" | tr a-z A-Z)_H"
		echo
		echo "/*"
		echo " * ftrace is not implemented. Each tracepoint becomes a statement that"
		echo " * evaluates nothing: the arguments are deliberately NOT evaluated, because"
		echo " * upstream tracepoints are documented to be free when disabled and some"
		echo " * call sites pass expressions that are only valid under a lock the tracing"
		echo " * path does not take."
		echo " */"
		grep -rhoE '\btrace_[a-z0-9_]+[[:space:]]*\(' "$src" |
			sed 's/[[:space:]]*($//;s/[[:space:]]*(//' |
			sort -u |
			while read -r name; do
				# A tracepoint has a companion predicate, `trace_x_enabled()`,
				# which a filesystem tests before doing work that only exists
				# to be traced. It is a VALUE, not a statement — btrfs writes
				# `if (trace_btrfs_tree_lock_enabled())` — so it expands to 0
				# rather than to an empty statement. With no tracing the honest
				# answer is false, and it is also the one that compiles.
				case "$name" in
				*_enabled)
					echo "#define $name(...) 0" ;;
				*)
					echo "#define $name(...) do { } while (0)" ;;
				esac
			done
		echo
		echo "#endif"
	} > "$out.tmp"
	mv "$out.tmp" "$out"
	n=$(grep -c '^#define trace_' "$out")
	echo "gen-shim-headers: $sys — $n tracepoints" >&2
done

# ── pass two: the names the source does not spell ──────────────────────────
#
# Some tracepoints are built by token pasting. btrfs's DECLARE_SPACE_INFO_UPDATE
# expands `trace_update_##name`, so `trace_update_bytes_pinned` exists in the
# preprocessed source and appears nowhere in the text — grep cannot find it and
# neither can any reasonable pattern short of a C preprocessor.
#
# So the compiler is asked instead. Every file is compiled against the stubs
# produced above, and any tracepoint it reports as undeclared is added. This is
# self-maintaining for the same reason pass one is: the list comes from the
# pinned source, by way of the only tool that actually knows what the macros
# expand to.
#
# Skipped when the shim cannot preprocess yet — during bring-up that is normal,
# and pass one alone is still correct as far as it goes.
CC="${CC:-clang}"
if [ -f "$STAGE_DIR/B1NIX-OBJECTS" ] && "$CC" --version >/dev/null 2>&1; then
	RES="$("$CC" -print-resource-dir)/include"
	extra="$(mktemp)"
	for f in $(cat "$STAGE_DIR/B1NIX-OBJECTS"); do
		"$CC" -std=gnu11 -nostdinc -ffreestanding -fno-builtin -w -fsyntax-only -ferror-limit=0 \
			-D__KERNEL__ -D__linux__ -DKBUILD_MODNAME='"b1nixfs"' \
			-DCONFIG_X86=1 -DCONFIG_X86_64=1 \
			-isystem "$RES" \
			-I "$ROOT_DIR/kernel/include" -I "$ROOT_DIR/kernel/include/uapi" \
			-I "$GEN_DIR" \
			-I "$STAGE_DIR/include" -I "$STAGE_DIR/include/uapi" -I "$STAGE_DIR/fs" \
			-include linux/compiler_types.h -include linux/types.h \
			"$STAGE_DIR/$f" 2>&1 |
			grep -oE "call to undeclared function 'trace_[a-z0-9_]+'" |
			sed "s/.*'\(trace_[a-z0-9_]*\)'/\1/" >> "$extra"
	done
	# Written whether or not anything was found: the build force-includes it,
	# and a file that only exists sometimes makes the build depend on whether
	# a previous run happened to find something.
	if true; then
		# They go into the trace system of the tree they were found in — but the
		# file that reported one is not always in that tree, so they are all
		# appended to a header of their own that the three include.
		out="$GEN_DIR/trace/events/b1nix-pasted.h"
		{
			echo "/* SPDX-License-Identifier: GPL-2.0-only */"
			echo "/* Generated by tools/import/fs/gen-shim-headers.sh — tracepoint names that"
			echo "   exist only after macro expansion, found by compiling. Do not edit. */"
			echo "#ifndef B1NIX_TRACE_EVENTS_PASTED_H"
			echo "#define B1NIX_TRACE_EVENTS_PASTED_H"
			sort -u "$extra" | while read -r name; do
				echo "#ifndef $name"
				case "$name" in
				*_enabled) echo "#define $name(...) 0" ;;
				*)         echo "#define $name(...) do { } while (0)" ;;
				esac
				echo "#endif"
			done
			echo "#endif"
		} > "$out"
		n=$(grep -c '^#define trace_' "$out" || true)
		echo "gen-shim-headers: pasted — $n tracepoints found by compiling" >&2
	fi
	rm -f "$extra"
fi

# ── pass three: structs named before their own header ──────────────────────
#
# A `struct X *` first seen inside a function prototype declares a type local to
# that prototype. When the real X arrives later in the same translation unit,
# the two do not match, and clang reports it as "conflicting types" at the
# function's definition — an error, where the compiler upstream builds with
# treats it as a warning.
#
# It happens inside the imported trees themselves: btrfs's extent-tree.h
# declares functions taking `struct btrfs_delayed_ref_head *`, and the header
# that defines that struct is included later by the .c. Editing either is the
# one thing this import forbids, so the names are forward-declared ahead of
# everything instead — which is exactly what the C the compiler wants would have
# said, and changes no code.
#
# The list is collected by compiling, for the same reason pass two is: the
# compiler is the only thing that knows which names end up in that position.
if [ -f "$STAGE_DIR/B1NIX-OBJECTS" ] && "$CC" --version >/dev/null 2>&1; then
	RES="$("$CC" -print-resource-dir)/include"
	fwd="$(mktemp)"
	for f in $(cat "$STAGE_DIR/B1NIX-OBJECTS"); do
		# -Wno-everything then -Wvisibility, not -w: `-w` wins over every
		# later -W flag in clang, so the one warning this pass exists to read
		# would be suppressed along with the rest.
		"$CC" -std=gnu11 -nostdinc -ffreestanding -fno-builtin \
			-Wno-everything -Wvisibility \
			-fsyntax-only -ferror-limit=400 \
			-Wno-incompatible-pointer-types \
			-Wno-incompatible-function-pointer-types \
			-D__KERNEL__ -D__linux__ -DKBUILD_MODNAME='"b1nixfs"' \
			-DCONFIG_X86=1 -DCONFIG_X86_64=1 \
			-isystem "$RES" \
			-I "$ROOT_DIR/kernel/include" -I "$ROOT_DIR/kernel/include/uapi" \
			-I "$GEN_DIR" \
			-I "$STAGE_DIR/include" -I "$STAGE_DIR/include/uapi" -I "$STAGE_DIR/fs" \
			-include linux/compiler_types.h -include linux/types.h \
			-include trace/events/b1nix-pasted.h \
			"$STAGE_DIR/$f" 2>&1 |
			grep -oE "declaration of 'struct [a-z_0-9]+' will not be visible" |
			sed "s/.*'struct \([a-z_0-9]*\)'.*/\1/" >> "$fwd"
	done
	out="$GEN_DIR/b1nix-fwd.h"
	{
		echo "/* SPDX-License-Identifier: GPL-2.0-only */"
		echo "/* Generated by tools/import/fs/gen-shim-headers.sh — structs the imported"
		echo "   sources name in a prototype before their own header defines them."
		echo "   Do not edit. */"
		echo "#ifndef B1NIX_FS_FWD_H"
		echo "#define B1NIX_FS_FWD_H"
		sort -u "$fwd" | while read -r name; do
			echo "struct $name;"
		done
		echo "#endif"
	} > "$out"
	n=$(grep -c '^struct ' "$out" || true)
	echo "gen-shim-headers: forward — $n structs declared ahead of their headers" >&2
	rm -f "$fwd"
fi

echo "$GEN_DIR"
