#!/bin/sh
# Build upstream libwayland client/server libraries for the b1nix userspace ABI.

set -eu

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
WAYLAND_VERSION="${WAYLAND_VERSION:-1.25.0}"
WAYLAND_TARBALL="wayland-${WAYLAND_VERSION}.tar.xz"
WAYLAND_URL="https://gitlab.freedesktop.org/wayland/wayland/-/releases/${WAYLAND_VERSION}/downloads/${WAYLAND_TARBALL}"
AR_BIN="${AR:-$(command -v llvm-ar 2>/dev/null || echo /opt/homebrew/opt/llvm/bin/llvm-ar)}"

. "$ROOT_DIR/tools/toolchain-env.sh"
SRC_PARENT="$ROOT_DIR/build/wayland-src"
SRC_DIR="$SRC_PARENT/wayland-${WAYLAND_VERSION}"
BUILD_DIR="$ROOT_DIR/build/wayland-b1nix/$B1NIX_TRIPLET"
INSTALL_DIR="$BUILD_DIR/install"
HOST_DIR="$ROOT_DIR/build/wayland-host/$WAYLAND_VERSION/$B1NIX_TRIPLET"
GEN_DIR="$BUILD_DIR/generated"
COMPAT_DIR="$BUILD_DIR/compat"
LIBFFI_DIR="$(B1NIX_ARCH="$B1NIX_ARCH" "$ROOT_DIR/tools/ports/build-libffi.sh")"

mkdir -p "$SRC_PARENT" "$BUILD_DIR/obj" "$INSTALL_DIR/include" \
  "$INSTALL_DIR/lib" "$HOST_DIR" "$GEN_DIR" "$COMPAT_DIR/sys"

# epoll/eventfd/timerfd/signalfd are now real libc headers (M56); only sys/file.h
# (flock + LOCK_*) still comes from the port compat shim. Symlinking the others
# to compat.h would shadow the real headers and self-include-guard them out.
rm -f "$COMPAT_DIR/sys/epoll.h" "$COMPAT_DIR/sys/eventfd.h" \
  "$COMPAT_DIR/sys/timerfd.h" "$COMPAT_DIR/sys/signalfd.h"
ln -sf "$ROOT_DIR/tools/wayland/compat.h" "$COMPAT_DIR/sys/file.h"

if [ ! -d "$SRC_DIR" ]; then
  tmp="$SRC_PARENT/$WAYLAND_TARBALL"
  if [ ! -f "$tmp" ]; then
    curl -L "$WAYLAND_URL" -o "$tmp" 1>&2
  fi
  tar -xJf "$tmp" -C "$SRC_PARENT" 1>&2
fi

cat > "$HOST_DIR/wayland-version.h" <<EOF
#define WAYLAND_VERSION_MAJOR 1
#define WAYLAND_VERSION_MINOR 25
#define WAYLAND_VERSION_MICRO 0
#define WAYLAND_VERSION "1.25.0"
EOF

# Meson normally generates this file. The client library only probes GETTID,
# which b1nix does not expose, so an empty platform config is sufficient.
cat > "$SRC_DIR/config.h" <<EOF
/* Generated by tools/ports/build-wayland.sh for b1nix. */
EOF

if [ ! -x "$HOST_DIR/wayland-scanner" ]; then
  cc -O2 -DHAVE_LIBXML=0 -I"$HOST_DIR" -I"$SRC_DIR/src" \
    "$SRC_DIR/src/scanner.c" "$SRC_DIR/src/wayland-util.c" \
    -lexpat -o "$HOST_DIR/wayland-scanner"
fi

"$HOST_DIR/wayland-scanner" client-header \
  "$SRC_DIR/protocol/wayland.xml" "$GEN_DIR/wayland-client-protocol.h"
"$HOST_DIR/wayland-scanner" client-header -c \
  "$SRC_DIR/protocol/wayland.xml" "$GEN_DIR/wayland-client-protocol-core.h"
"$HOST_DIR/wayland-scanner" server-header \
  "$SRC_DIR/protocol/wayland.xml" "$GEN_DIR/wayland-server-protocol.h"
"$HOST_DIR/wayland-scanner" server-header -c \
  "$SRC_DIR/protocol/wayland.xml" "$GEN_DIR/wayland-server-protocol-core.h"
"$HOST_DIR/wayland-scanner" public-code \
  "$SRC_DIR/protocol/wayland.xml" "$GEN_DIR/wayland-protocol.c"

if [ "$B1NIX_ARCH" = "x86" ]; then
  TARGET="i686-unknown-elf"
  ARCH_FLAGS="-fomit-frame-pointer"
else
  TARGET="x86_64-unknown-elf"
  ARCH_FLAGS=""
fi

CC_FLAGS="--target=$TARGET $ARCH_FLAGS -ffreestanding -fno-builtin
  -fno-stack-protector -nostdinc -isystem $ROOT_DIR/userspace/include
  -I$ROOT_DIR/userspace/include -I$SRC_DIR -I$SRC_DIR/src -I$GEN_DIR -I$HOST_DIR
  -I$LIBFFI_DIR/include -D__STDC_NO_ATOMICS__
  -include $ROOT_DIR/tools/wayland/compat.h
  -Wall -Wextra -O2 -msoft-float -mno-implicit-float -Db1nix"

compile()
{
  src="$1"
  obj="$2"
  clang $CC_FLAGS -c "$src" -o "$obj"
}

compile "$SRC_DIR/src/wayland-client.c" "$BUILD_DIR/obj/wayland-client.o"
compile "$SRC_DIR/src/connection.c" "$BUILD_DIR/obj/connection.o"
compile "$SRC_DIR/src/wayland-util.c" "$BUILD_DIR/obj/wayland-util.o"
compile "$GEN_DIR/wayland-protocol.c" "$BUILD_DIR/obj/wayland-protocol.o"

SERVER_FLAGS="$CC_FLAGS -I$COMPAT_DIR -DB1NIX_WAYLAND_SERVER"
compile_server()
{
  src="$1"
  obj="$2"
  clang $SERVER_FLAGS -c "$src" -o "$obj"
}

compile_server "$SRC_DIR/src/wayland-server.c" "$BUILD_DIR/obj/wayland-server.o"
compile_server "$SRC_DIR/src/event-loop.c" "$BUILD_DIR/obj/event-loop.o"
compile_server "$ROOT_DIR/tools/wayland/os.c" \
  "$BUILD_DIR/obj/wayland-os.o"
compile_server "$ROOT_DIR/tools/wayland/compat.c" \
  "$BUILD_DIR/obj/wayland-compat.o"

"$AR_BIN" rcs "$INSTALL_DIR/lib/libwayland-client.a" \
  "$BUILD_DIR/obj/wayland-client.o" "$BUILD_DIR/obj/connection.o" \
  "$BUILD_DIR/obj/wayland-util.o" "$BUILD_DIR/obj/wayland-protocol.o" \
  "$BUILD_DIR/obj/wayland-os.o" "$BUILD_DIR/obj/wayland-compat.o"
"$AR_BIN" rcs "$INSTALL_DIR/lib/libwayland-server.a" \
  "$BUILD_DIR/obj/wayland-server.o" "$BUILD_DIR/obj/event-loop.o" \
  "$BUILD_DIR/obj/connection.o" \
  "$BUILD_DIR/obj/wayland-util.o" "$BUILD_DIR/obj/wayland-protocol.o" \
  "$BUILD_DIR/obj/wayland-os.o" "$BUILD_DIR/obj/wayland-compat.o"
cp "$LIBFFI_DIR/lib/libffi.a" "$INSTALL_DIR/lib/"
cp "$LIBFFI_DIR/include/ffi.h" "$LIBFFI_DIR/include/ffitarget.h" \
  "$INSTALL_DIR/include/"
cp "$SRC_DIR/src/wayland-client.h" "$SRC_DIR/src/wayland-client-core.h" \
  "$SRC_DIR/src/wayland-server.h" "$SRC_DIR/src/wayland-server-core.h" \
  "$SRC_DIR/src/wayland-util.h" "$HOST_DIR/wayland-version.h" \
  "$GEN_DIR/wayland-client-protocol.h" \
  "$GEN_DIR/wayland-client-protocol-core.h" \
  "$GEN_DIR/wayland-server-protocol.h" \
  "$GEN_DIR/wayland-server-protocol-core.h" "$INSTALL_DIR/include/"

echo "$INSTALL_DIR"
