#!/bin/sh
# Build libcss as a static libcss.a for the b1nix userspace ABI. Freestanding
# curated compile of the portable C sources (no autotools), like the other
# ports. libcss is NetSurf's CSS parser + selection engine; it interns through
# libwapcaplet and parses input through libparserutils. The release tarball
# ships all generated property tables, so no python/perl generation is needed
# for them. Prints the install dir.
#
# M53 (NetSurf browser platform) — browser lib chain step 4. Depends on
# build-libwapcaplet.sh and build-libparserutils.sh.
# Build logic lives in tools/ports/drivers/nslib.sh; this is the manifest.
set -eu
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

NSLIB_NAME=libcss
NSLIB_VERSION="${CSS_VERSION:-0.9.2}"
NSLIB_ARCHIVE=libcss.a
NSLIB_DEPS="build-libwapcaplet.sh build-libparserutils.sh"
NSLIB_FIND_DIR=src
# css_property_parser_gen.c is the HOST generator tool (own main) — never in the
# target archive.
NSLIB_FIND_EXCLUDE='css_property_parser_gen.c'
# _ALIGNED is an alignment-attribute macro libcss leaves undefined, relying on
# old-GCC -fcommon to merge the bogus tentative global it produces in every TU
# (clang defaults to -fno-common → duplicate-symbol errors). Define it empty.
NSLIB_CFLAGS="-D_ALIGNED= -Wno-implicit-function-declaration"
NSLIB_HEADERS="tree:include/libcss"

# The "simple" enum/keyword property parsers (display, direction, ...) are not
# shipped: a host tool (css_property_parser_gen.c) is compiled and run once per
# property descriptor in properties.gen to emit autogenerated_<prop>.c. This
# mirrors the upstream parse/properties/Makefile rule exactly.
port_pre_build() {
  PERL_BIN="${PERL:-$(command -v perl)}"
  HOST_CC="${CC_FOR_BUILD:-$(command -v cc || command -v clang)}"
  PROP_DIR="$SRC_DIR/src/parse/properties"
  GEN_PARSER="$BUILD_DIR/gen_parser"
  if [ ! -f "$PROP_DIR/.b1nix-autogen-stamp" ]; then
    "$HOST_CC" -O2 -o "$GEN_PARSER" "$PROP_DIR/css_property_parser_gen.c" 1>&2
    PROPS=$("$PERL_BIN" -ne 'print "$1\n" if /^([^#][^:]+):/' "$PROP_DIR/properties.gen")
    for p in $PROPS; do
      line=$(grep "^$p:" "$PROP_DIR/properties.gen")
      "$GEN_PARSER" -o "$PROP_DIR/autogenerated_$p.c" "$line" 1>&2
    done
    touch "$PROP_DIR/.b1nix-autogen-stamp"
  fi
}

. "$ROOT_DIR/tools/ports/drivers/nslib.sh"
