#!/bin/sh
# Build libsvgtiny as a static libsvgtiny.a for the b1nix userspace ABI.
# Freestanding curated compile (no autotools). libsvgtiny is NetSurf's SVG
# decoder; the browser registers it as an image content handler so inline/img
# SVG renders.
#
# libsvgtiny parses SVG (which is XML) through libdom's XML binding
# (dom_xml_parser_*). b1nix's libdom build only ships the hubbub (HTML) binding,
# so we compile libdom's expat XML binding (bindings/xml/expat_xmlparser.c) into
# libsvgtiny.a here and link against the b1nix expat port. Also depends on
# libdom + libwapcaplet (staged) and openlibm (math). The named-colour table is
# generated from colors.gperf with gperf. Prints the install dir.
#
# M53 (NetSurf browser platform) — SVG image decoder.
# Build logic lives in tools/ports/drivers/nslib.sh; this is the manifest.
set -eu
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

NSLIB_NAME=libsvgtiny
NSLIB_ARCHIVE=libsvgtiny.a
NSLIB_SOURCE=bundle
NSLIB_BUNDLE_SUBDIR=libsvgtiny
NSLIB_SENTINEL=src/svgtiny.c
NSLIB_INC_DIRS="include src"
NSLIB_SOURCES="src/svgtiny.c src/svgtiny_gradient.c src/svgtiny_list.c"

port_pre_build() {
  GPERF_BIN="${GPERF:-$(command -v gperf 2>/dev/null || true)}"
  if [ -z "$GPERF_BIN" ]; then
    echo "build-libsvgtiny.sh: gperf not found on host (needed for colors table)" >&2
    exit 1
  fi
  # libsvgtiny + libdom both ship inside the netsurf-all bundle; use that copy of
  # libdom for the XML binding source.
  SVG_LIBDOM_DIR="$(ls -d "$ROOT_DIR"/build/netsurf-src/netsurf-all-*/libdom 2>/dev/null | head -1)"
  if [ -z "$SVG_LIBDOM_DIR" ] || [ ! -f "$SVG_LIBDOM_DIR/bindings/xml/expat_xmlparser.c" ]; then
    echo "build-libsvgtiny.sh: libdom XML binding source not found" >&2
    exit 1
  fi
  # expat (M51 port) — XML parser backing libdom's XML binding.
  SVG_EXPAT_INST="$(B1NIX_ARCH="$B1NIX_ARCH" "$ROOT_DIR/tools/ports/build-expat.sh" | tail -1)"
  # Sysroot from build-netsurf-fb.sh holds libdom/libwapcaplet headers + openlibm.
  SVG_SYSROOT="$ROOT_DIR/build/netsurf-sysroot/$B1NIX_TRIPLET"
  # Stage the libdom XML binding public headers under the install <dom/...>
  # layout (libdom's own install does this; the curated libdom build skips it).
  SVG_GENINC="$BUILD_DIR/geninc"
  mkdir -p "$SVG_GENINC/dom/bindings/xml"
  cp "$SVG_LIBDOM_DIR/bindings/xml/xmlparser.h" "$SVG_LIBDOM_DIR/bindings/xml/xmlerror.h" \
     "$SVG_GENINC/dom/bindings/xml/"
  # Generate the named-colour perfect-hash table (svgtiny.c #includes it).
  "$GPERF_BIN" --output-file="$SRC_DIR/src/autogenerated_colors.c" "$SRC_DIR/src/colors.gperf"
  NSLIB_CFLAGS="-I$SVG_SYSROOT/include -I$SVG_GENINC -I$SVG_EXPAT_INST/include -Wno-implicit-function-declaration"
}

# libdom XML binding (expat backend). Needs its sibling utils.h/xmlerror.h.
port_compile_extra() {
  nslib_cc "$SVG_LIBDOM_DIR/bindings/xml/expat_xmlparser.c" "-I$SVG_LIBDOM_DIR/bindings/xml"
}

port_install_headers() {
  cp "$SRC_DIR/include/svgtiny.h" "$INSTALL_DIR/include/"
}

port_post_install() {
  # Make sure libexpat.a is reachable in the netsurf sysroot for the final link.
  cp "$SVG_EXPAT_INST/lib/libexpat.a" "$SVG_SYSROOT/lib/" 2>/dev/null || true
}

. "$ROOT_DIR/tools/ports/drivers/nslib.sh"
