#!/bin/sh
# Build bmake — Simon Gerraty's portable NetBSD make (BSD 3-clause) — for b1nix.
#
# Ships as /bin/make, replacing the GNU Make 3.82 port that used to be built by
# the now-deleted tools/toolchain/build-make.sh. bmake speaks the same POSIX
# Makefile dialect the in-guest build harness (tools/inguest/Makefile) is
# written in, so the M26 self-host flow keeps working without GPL code.
#
# Cross-building is straightforward because bmake ships make-bootstrap.sh.in: a
# plain /bin/sh script (generated by configure) that compiles and links the
# whole program without needing a make at all — exactly what a make replacement
# has to offer when there is no make yet.
#
# Prints the install dir on stdout (the port-script convention).
set -eu
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
. "$ROOT_DIR/tools/ports/drivers/common.sh"

VER="${BMAKE_VERSION:-20260714}"
SRCNAME="bmake"
TARBALL="bmake-$VER.tar.gz"
URL="http://www.crufty.net/ftp/pub/sjg/$TARBALL"

SRC_PARENT="$ROOT_DIR/build/src/bmake-$VER"
SRC_DIR="$SRC_PARENT/$SRCNAME"
BUILD_DIR="$ROOT_DIR/build/$B1NIX_ARCH/ports/bmake"
INSTALL_DIR="$BUILD_DIR/install"
LOCKFILE="$BUILD_DIR/locks/build.lock"
CC_WRAPPER="$ROOT_DIR/tools/toolchain/bin/b1nix-musl-autotools-cc"

case "$B1NIX_ARCH" in
  x86) MACHINE_NAME=i386 ;;
  *)   MACHINE_NAME=x86_64 ;;
esac

mkdir -p "$SRC_PARENT" "$BUILD_DIR" "$INSTALL_DIR/bin" "$(dirname "$LOCKFILE")"

(
  flock -x 9
  if [ -x "$INSTALL_DIR/bin/bmake" ]; then
    echo "$INSTALL_DIR"
    exit 0
  fi

  : > "$BUILD_DIR/build.log"
  exec 2>>"$BUILD_DIR/build.log"

  port_fetch_tarball "$URL" "$SRC_PARENT/$TARBALL" "$SRC_PARENT" "$SRC_DIR"
  [ -d "$SRC_DIR" ] || { echo "build-bmake: source not found at $SRC_DIR" >&2; exit 1; }

  if [ ! -f "$(port_musl_lib)/libc.so" ]; then
    B1NIX_ARCH="$B1NIX_ARCH" sh "$ROOT_DIR/tools/ports/build-musl.sh" 1>&2
  fi

  # --without-meta / --without-filemon: the meta-mode build tracer needs
  # ktrace/filemon kernel support b1nix has no equivalent for, and it is not
  # needed to interpret a Makefile. MACHINE/MACHINE_ARCH must be forced or
  # configure runs the host's machine.sh and bakes the *host* identity in.
  ( cd "$BUILD_DIR"
    B1NIX_ARCH="$B1NIX_ARCH" "$SRC_DIR/configure" \
      --host="$B1NIX_TRIPLET" \
      --prefix=/usr \
      --with-default-sys-path=/usr/share/mk \
      --with-machine="$MACHINE_NAME" \
      --with-machine_arch="$MACHINE_NAME" \
      --without-meta --without-filemon \
      CC="$CC_WRAPPER" 1>&2 )

  ( cd "$BUILD_DIR" && B1NIX_ARCH="$B1NIX_ARCH" sh ./make-bootstrap.sh 1>&2 )
  [ -x "$BUILD_DIR/bmake" ] || { echo "build-bmake: bootstrap produced no bmake" >&2; exit 1; }
  cp -f "$BUILD_DIR/bmake" "$INSTALL_DIR/bin/bmake"

  # bmake resolves .include <bsd.*.mk> through _PATH_DEFSYSPATH (/usr/share/mk),
  # so the system makefiles have to ship next to the binary or every Makefile
  # that includes one fails on the target.
  mkdir -p "$INSTALL_DIR/share/mk"
  cp -f "$SRC_DIR"/mk/*.mk "$INSTALL_DIR/share/mk/" 2>/dev/null || true

  echo "$INSTALL_DIR"
) 9>"$LOCKFILE"
