#!/bin/sh
# Build libhubbub as a static libhubbub.a for the b1nix userspace ABI.
# Freestanding curated compile of the portable C sources (no autotools), like
# the other ports. libhubbub is NetSurf's HTML5 tokeniser + tree constructor;
# it parses input through libparserutils. Prints the install dir.
#
# M53 (NetSurf browser platform) — browser lib chain step 3. Depends on
# build-libparserutils.sh.
# Build logic lives in tools/ports/drivers/nslib.sh; this is the manifest.
set -eu
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

NSLIB_NAME=libhubbub
NSLIB_VERSION="${HUBBUB_VERSION:-0.3.8}"
NSLIB_ARCHIVE=libhubbub.a
NSLIB_DEPS="build-libparserutils.sh"
NSLIB_FIND_DIR=src
NSLIB_FIND_EXCLUDE='autogenerated-*.c'
NSLIB_CFLAGS="-DNDEBUG -Wno-implicit-function-declaration"
NSLIB_HEADERS="tree:include/hubbub"

# Named-entity table (perl) + element-type perfect-hash (gperf, then made static,
# exactly the upstream Makefile rules). The .inc/.c are fragments #included by
# their TUs, so they are never compiled on their own — hence excluded above.
port_pre_build() {
  PERL_BIN="${PERL:-$(command -v perl)}"
  GPERF_BIN="${GPERF:-$(command -v gperf)}"
  if [ ! -f "$SRC_DIR/src/tokeniser/entities.inc" ]; then
    ( cd "$SRC_DIR" && "$PERL_BIN" build/make-entities.pl ) 1>&2
  fi
  ELT_GEN="$SRC_DIR/src/treebuilder/autogenerated-element-type.c"
  if [ ! -f "$ELT_GEN" ]; then
    "$GPERF_BIN" --output-file="$ELT_GEN.tmp" "$SRC_DIR/src/treebuilder/element-type.gperf" 1>&2
    sed -e 's/^\(const struct element_type_map\)/static \1/' "$ELT_GEN.tmp" >"$ELT_GEN"
    rm -f "$ELT_GEN.tmp"
  fi
}

. "$ROOT_DIR/tools/ports/drivers/nslib.sh"
