/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef LKPI_LINUX_PROC_FS_H
#define LKPI_LINUX_PROC_FS_H

#include <linux/types.h>
#include <linux/fs.h>

/*
 * /proc entries created by a filesystem.
 *
 * ext4 publishes per-superblock statistics under /proc/fs/ext4/<dev>/ and btrfs
 * has a few of its own. b1nix's procfs is generated by the kernel rather than
 * registered into, so these create nothing.
 *
 * They return NULL, and that is safe precisely because upstream made it so:
 * every caller in both filesystems treats a NULL proc_dir_entry as "no /proc,
 * carry on" — the statistics are diagnostics, not state. The remove and lookup
 * calls accept NULL for the same reason.
 */

struct proc_dir_entry;
struct seq_file;
struct file_operations;
struct proc_ops;

static inline struct proc_dir_entry *proc_mkdir(const char *name,
                                                struct proc_dir_entry *parent)
{ (void)name; (void)parent; return NULL; }
static inline struct proc_dir_entry *proc_mkdir_data(const char *name,
                                                     umode_t mode,
                                                     struct proc_dir_entry *parent,
                                                     void *data)
{ (void)name; (void)mode; (void)parent; (void)data; return NULL; }
static inline struct proc_dir_entry *proc_create(const char *name, umode_t mode,
                                                 struct proc_dir_entry *parent,
                                                 const struct proc_ops *ops)
{ (void)name; (void)mode; (void)parent; (void)ops; return NULL; }
static inline struct proc_dir_entry *proc_create_data(const char *name,
                                                      umode_t mode,
                                                      struct proc_dir_entry *parent,
                                                      const struct proc_ops *ops,
                                                      void *data)
{ (void)name; (void)mode; (void)parent; (void)ops; (void)data; return NULL; }
static inline struct proc_dir_entry *proc_create_single_data(const char *name,
	umode_t mode, struct proc_dir_entry *parent,
	int (*show)(struct seq_file *, void *), void *data)
{ (void)name; (void)mode; (void)parent; (void)show; (void)data; return NULL; }
static inline void proc_remove(struct proc_dir_entry *de) { (void)de; }
static inline void remove_proc_entry(const char *name,
                                     struct proc_dir_entry *parent)
{ (void)name; (void)parent; }
static inline int remove_proc_subtree(const char *name,
                                      struct proc_dir_entry *parent)
{ (void)name; (void)parent; return 0; }
static inline void *pde_data(const struct inode *inode)
{ (void)inode; return NULL; }
static inline void proc_set_user(struct proc_dir_entry *de, kuid_t uid,
                                 kgid_t gid)
{ (void)de; (void)uid; (void)gid; }

static inline struct proc_dir_entry *proc_create_seq_data(const char *name,
	umode_t mode, struct proc_dir_entry *parent,
	const struct seq_operations *ops, void *data)
{ (void)name; (void)mode; (void)parent; (void)ops; (void)data; return NULL; }

/*
 * The operations vector a /proc file is created with.
 *
 * Separate from file_operations upstream since 5.6, because a proc file needs
 * only a handful of the members and the split keeps a proc file from
 * accidentally implementing mmap. jbd2 defines one for its per-journal
 * statistics; nothing here registers it, but the structure has to be complete
 * for the definition to compile.
 */
struct proc_ops {
	unsigned int proc_flags;
	int (*proc_open)(struct inode *, struct file *);
	ssize_t (*proc_read)(struct file *, char __user *, size_t, loff_t *);
	ssize_t (*proc_read_iter)(struct kiocb *, struct iov_iter *);
	ssize_t (*proc_write)(struct file *, const char __user *, size_t,
	                      loff_t *);
	loff_t (*proc_lseek)(struct file *, loff_t, int);
	int (*proc_release)(struct inode *, struct file *);
	__poll_t (*proc_poll)(struct file *, struct poll_table_struct *);
	long (*proc_ioctl)(struct file *, unsigned int, unsigned long);
	int (*proc_mmap)(struct file *, struct vm_area_struct *);
	unsigned long (*proc_get_unmapped_area)(struct file *, unsigned long,
	                                        unsigned long, unsigned long,
	                                        unsigned long);
};

#endif
