#include <b1nix/arch.h>
#include <b1nix/fw_cfg.h>
#include <b1nix/io.h>
#include <b1nix/bootinfo.h>
#include <b1nix/platform.h>
#include <b1nix/bcm2835.h>
#if defined(__aarch64__)
#include <b1nix/gicv3.h>
#endif
#include <b1nix/console.h>
#include <b1nix/kprintf.h>
#include <b1nix/ktime.h>
#include <b1nix/ftrace.h>
#include <b1nix/gdbstub.h>
#include <b1nix/initramfs.h>
#include <b1nix/mm.h>
#include <b1nix/net.h>
#include <b1nix/netproto.h>
#include <b1nix/module.h>
#include <b1nix/netdev.h>
#include <b1nix/panic.h>
#include <b1nix/panic_screen.h>
#include <b1nix/splash.h>
#include <b1nix/sched.h>
#include <b1nix/serial.h>
#include <b1nix/serial_tty.h>
#include <b1nix/user.h>
#include <b1nix/sysfs_attr.h>
#include <b1nix/cgroup.h>
#include <b1nix/vfs.h>
#include <b1nix/syscall.h>
#include <b1nix/blk.h>
#include <b1nix/page_cache.h>
#include <b1nix/tlb.h>
#include <b1nix/fat32.h>
#include <b1nix/exfat.h>
#include <b1nix/ntfs.h>
#include <b1nix/btrfs.h>
#include <b1nix/fuse.h>
#include <b1nix/fwcfgfs.h>
#include <b1nix/debugfs.h>
#include <b1nix/tarfs.h>
#include <b1nix/procfs.h>
#include <b1nix/ahci.h>
#include <b1nix/amdvi.h>
#include <b1nix/iommu.h>
#include <b1nix/smmuv3.h>
#include <b1nix/nvme.h>
#include <b1nix/ufs.h>
#include <lkpi/dma-mapping.h>
#include <b1nix/filelock.h>
#include <b1nix/errno.h>
#include <b1nix/isofs.h>
#include <b1nix/loop.h>
#include <b1nix/md.h>
#include <b1nix/mtd.h>
#include <b1nix/nbd.h>
#include <b1nix/vt.h>
#include <b1nix/rtc.h>
#include <b1nix/kmsg.h>
#include <b1nix/watchdog.h>
#include <b1nix/i2c.h>
#include <b1nix/vt.h>
#include <b1nix/kmsg.h>
#include <b1nix/watchdog.h>
#include <b1nix/i2c.h>
#include <b1nix/mqueue.h>
#include <b1nix/shm.h>
#include <b1nix/resource_caps.h>
#include <b1nix/sysv_ipc.h>
#include <b1nix/uidgid.h>
#include <b1nix/lapic.h>
#include <b1nix/video.h>
#include <b1nix/acpi.h>
#include <b1nix/ioapic.h>
#include <b1nix/ramdisk.h>
#include <b1nix/sound.h>
#include <b1nix/virtio_gpu.h>
#include <b1nix/virtio_9p.h>
#include <string.h>
#include <stdio.h>

extern void usb_selftest(void);
extern void ps2_kbd_init(void);
extern void ps2_mouse_init(void);
extern int xhci_probe(void);
extern void virtio_gpu_init(void);
#if defined(B1NIX_I915) && B1NIX_I915
/*
 * Generated by each module's own module_init() — see <linux/module.h>.
 *
 * Order is the dependency order, and it is not decorative: drm_dev_init()
 * refuses with "DRM core is not initialized" until drm_core_init() has run, and
 * i915 allocates its device through it. drm_core_bringup() is the core's
 * initcall behind an idempotent guard, because the KMS self-test calls it too.
 */
extern void drm_core_bringup(void);
/*
 * The DRM core's debug mask. Off by default because it is verbose, but it is
 * the only place the imported drivers explain what they decided and why — an
 * OpRegion that is not found, a port that is skipped, a link that fails to
 * train all say so through drm_dbg_kms(). Enable with b1nix.drm-debug on the
 * kernel command line.
 *
 * Bits are drm_debug_category: CORE, DRIVER, KMS.
 */
extern unsigned long __drm_debug;
#include <lkpi/drm_bridge.h>
struct drm_device;
struct drm_device *lkpi_drm_first_device(void);
void lkpi_i915_register_card(struct drm_device *dev);
/*
 * KMS only (DRM_UT_KMS). CORE and DRIVER together produce thousands of lines
 * per probe, and at 115200 baud the driver then does not finish inside a test's
 * timeout — the modeset messages are the ones worth having.
 */
#define B1NIX_DRM_DEBUG_MASK 0x04UL
extern int lkpi_initcall_gpu_buddy_module_init(void);
extern int lkpi_initcall_drm_display_helper_module_init(void);
extern int lkpi_initcall_i915_init(void);
extern void lkpi_i915_disable_display_power_saving(void);
static void i915_module_init(void)
{
	/*
	 * Keep the display power wells up so a commit never stalls waking one
	 * inside the vblank-evasion critical section. See the note on
	 * lkpi_i915_disable_display_power_saving(). Opt-in with b1nix.i915-no-dc
	 * until it is proven on the panel; it must run before the initcall below,
	 * which copies i915_modparams into the device.
	 */
	if (bootinfo_has_flag("b1nix.i915-no-dc"))
		lkpi_i915_disable_display_power_saving();
	/*
	 * The OpRegion first, because the driver reads it during probe and there is
	 * no second chance: the VBT inside is where the board's port wiring and
	 * signal parameters come from, and a driver that starts without it commits
	 * to defaults. QEMU offers one; nothing on this boot path has placed it.
	 * See kernel/dev/fw_cfg.c. The device is the assigned display at 00:02.0.
	 */
	(void)fw_cfg_place_igd_opregion(0, 2, 0);

	drm_core_bringup();
	(void)lkpi_initcall_gpu_buddy_module_init();
	(void)lkpi_initcall_drm_display_helper_module_init();
	(void)lkpi_initcall_i915_init();
}
#endif
extern void virtio_gpu_dev_init(void);
extern void virtio_input_init(void);
extern void virtio_console_init(void);

/* Visual boot markers — see b1nix/bootmark.h. */
#include <b1nix/bootmark.h>
#include <b1nix/fb_console.h>

/* Matches the console's own default; the phone build overrides both. */
#ifndef FB_CONSOLE_FONT_SCALE
#define FB_CONSOLE_FONT_SCALE 1
#endif
#define FB_CONSOLE_FONT_SCALE_DEFAULT FB_CONSOLE_FONT_SCALE

extern void fb_console_init(void);
extern int fb_console_ready(void);
extern void ac97_init(void);
extern void ac97_selftest(void);
extern void input_init(void);
extern void input_gfxtest_start(void);
extern void input_m47_inject_start(void);
extern void fb_dev_init(void);
extern void drm_dev_init(void);
extern void drm_card1_init(void);
extern void lkpi_cpuinfo_init(void);
#include <b1nix/dma_fence.h>
#include <b1nix/gpu_scheduler.h>
#include <b1nix/memtype.h>
#include <b1nix/netconsole.h>
#include <b1nix/pci.h>
#include <b1nix/vdso.h>
#include <lkpi/lkpi.h>


/* Case-insensitive compare for a UUID: the cmdline may spell it either way,
 * and blk_probe_uuid always prints lower case. */
static int uuid_equal(const char *a, const char *b) {
	for (usize i = 0;; i++) {
		char ca = a[i], cb = b[i];
		if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');
		if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');
		if (ca != cb) return 0;
		if (!ca) return 1;
	}
}

/* root=UUID=… / root=LABEL=… now ask the block layer what is on the device
 * rather than opening the ext superblock here: one implementation, and it
 * covers FAT and exFAT too (see blk_probe_uuid/blk_probe_label). */
static struct block_device *find_device_by_uuid(const char *expected_uuid) {
	char uuid[40];
	for (usize i = 0; i < blk_count(); i++) {
		struct block_device *dev = blk_at(i);
		if (!dev || dev->block_size != 512 || dev->block_count < 4)
			continue;
		if (blk_probe_uuid(dev, uuid, sizeof(uuid)) == 0 &&
		    uuid_equal(uuid, expected_uuid))
			return dev;
	}
	return 0;
}

/* The live medium is whichever block device actually carries the boot image —
 * decided by mounting it and looking, never by what the device is called. USB
 * storage is an ordinary sd* disk now, so a name prefix could not identify it
 * even in principle. Returns the device and the filesystem that mounted it,
 * leaving it mounted at /mnt/iso; NULL if no device carries the image. */
static struct block_device *find_live_medium(const char **fstype_out) {
	static const char *const fs_types[] = {"iso9660", "exfat"};

	/* Removable media first — a live USB is the common case and trying it
	 * first keeps the boot quick — then everything else, because a live
	 * image on an internal disk or an emulated CD is just as valid. */
	for (int removable_first = 1; removable_first >= 0; removable_first--) {
		for (usize i = 0; i < blk_count(); i++) {
			struct block_device *dev = blk_at(i);

			if (!dev || !dev->name)
				continue;
			if (blk_is_removable(dev) != removable_first)
				continue;
			for (usize f = 0; f < sizeof(fs_types) / sizeof(fs_types[0]); f++) {
				struct vfs_node *image;

				if (vfs_mount(dev->name, "/mnt/iso", fs_types[f], 0) != 0)
					continue;
				image = vfs_find_node("/mnt/iso/boot/rootfs.img");
				if (!IS_ERR(image)) {
					vfs_node_put(image);
					if (fstype_out)
						*fstype_out = fs_types[f];
					return dev;
				}
				vfs_umount("/mnt/iso");
			}
		}
	}
	return 0;
}

/* Has any removable medium been enumerated yet? Bounds how long the live-ISO
 * search waits for a USB stick that is still coming up. */
static struct block_device *blk_first_removable(void) {
	for (usize i = 0; i < blk_count(); i++) {
		struct block_device *dev = blk_at(i);

		if (blk_is_removable(dev))
			return dev;
	}
	return 0;
}

/* What the boot actually settled on: which filesystem became /, and which
 * program became PID 1.
 *
 * Both are printed when they happen, near the top of a boot -- which on a board
 * whose only console is a scrolling panel means they are gone by the time
 * anything goes wrong. The stall watchdog reprints this at the bottom of its
 * dump, where it is still readable. "root=initramfs" there is the whole
 * diagnosis for a machine that came up with none of its userspace: the real
 * root never mounted and PID 1 came out of the embedded file set. */
static char g_boot_root[64] = "initramfs";
static char g_boot_init[80] = "(not spawned)";

void boot_summary_set_root(const char *what) {
  strncpy(g_boot_root, what, sizeof(g_boot_root) - 1);
  g_boot_root[sizeof(g_boot_root) - 1] = '\0';
}

const char *boot_summary_root(void) { return g_boot_root; }
const char *boot_summary_init(void) { return g_boot_init; }

/* Mount `dev` at / as whatever its superblock says it is: the root image is
 * btrfs, older images and the boot modules are ext4. */
static int mount_root_as_probed(const char *dev_name, const char **type_out)
{
	static const char *const fallback[] = {"ext4", "ext3", "ext2"};
	struct block_device *dev = blk_get(dev_name);
	const char *probed = dev ? blk_probe_fstype(dev) : "-";

	if (probed[0] != '-' && vfs_mount(dev_name, "/", probed, 0) == 0) {
		*type_out = probed;
		return 0;
	}
	for (usize i = 0; i < sizeof(fallback) / sizeof(fallback[0]); i++) {
		if (strcmp(fallback[i], probed) != 0 &&
		    vfs_mount(dev_name, "/", fallback[i], 0) == 0) {
			*type_out = fallback[i];
			return 0;
		}
	}
	return -1;
}

static struct block_device *find_device_by_label(const char *expected_label) {
	char label[64];
	for (usize i = 0; i < blk_count(); i++) {
		struct block_device *dev = blk_at(i);
		if (!dev || dev->block_size != 512 || dev->block_count < 4)
			continue;
		if (blk_probe_label(dev, label, sizeof(label)) == 0 &&
		    strcmp(label, expected_label) == 0)
			return dev;
	}
	return 0;
}

static struct block_device *find_root_device(const char *root_val) {
	if (strncmp(root_val, "UUID=", 5) == 0) {
		return find_device_by_uuid(root_val + 5);
	} else if (strncmp(root_val, "LABEL=", 6) == 0) {
		const char *label_str = root_val + 6;
		return find_device_by_label(label_str);
	} else {
		const char *dev_name = root_val;
		if (strncmp(dev_name, "/dev/", 5) == 0) {
			dev_name += 5;
		}
		return blk_get(dev_name);
	}
}

/* M26 native-Clang kernel self-host: orchestration moved to userspace
 * (/bin/selfhost-build). The kernel just mounts the toolchain ext4 and
 * spawns the userspace builder. See userspace/bin/selfhost_build.c. */

/* Repeats the i915 port dump for as long as the machine runs. See the note at
 * its only caller. */
static unsigned g_port_watch_period;

static void __attribute__((unused)) port_watch_thread(void *arg)
{
	extern void lkpi_i915_dump_port_state_pub(void) __attribute__((weak));

	(void)arg;
	for (;;) {
		scheduler_sleep_ticks((u64)g_port_watch_period * 100);
		if (lkpi_i915_dump_port_state_pub)
			lkpi_i915_dump_port_state_pub();
	}
}

/* Names a call into the imported DRM core that has not come back. Its only
 * caller is the DRM debug path below; see lkpi_diag_watch_report(). */
/* Everything the scheduler knows, every half minute. For a run where a
 * userspace program stops making progress and says nothing: the task list with
 * each task's wait channel and kernel callers is usually enough to name what
 * it is waiting for. */
static void task_watch_thread(void *arg)
{
	(void)arg;
	for (;;) {
		/* Ten seconds, counted in ticks the scheduler is actually
		 * running at. Written as a constant this slept for thirty
		 * seconds at 100 Hz and for three at 1 kHz — the interval of a
		 * diagnostic must not change because the timer was reprogrammed. */
		scheduler_sleep_ticks(SCHED_MS_TO_TICKS(10000));
		scheduler_dump_tasks();
	}
}

static void __attribute__((unused)) drm_stuck_watch_thread(void *arg)
{
	extern int lkpi_diag_watch_report(u64 min_ms) __attribute__((weak));

	(void)arg;
	for (;;) {
		/* Half a second between looks, and a second of patience before a
		 * call is called slow. The old pair — two seconds and four — could
		 * not see a submission that takes two: EXECBUFFER2 on this GPU
		 * returns in about 2.1 s and was therefore never once reported,
		 * which is why the compositor's stall looked like it had no cause. */
		scheduler_sleep_ticks(SCHED_MS_TO_TICKS(500));
		if (lkpi_diag_watch_report && lkpi_diag_watch_report(1000)) {
			extern void lkpi_shmem_counts(u64 *calls, u64 *ns)
				__attribute__((weak));
			u64 calls = 0, ns = 0;

			/* Printed only alongside a slow call, so the numbers describe
			 * the stall rather than the boot as a whole. */
			if (lkpi_shmem_counts) {
				lkpi_shmem_counts(&calls, &ns);
				console_write("lkpi: shmem folios=");
				console_write_dec(calls);
				console_write(" total_ms=");
				console_write_dec(ns / 1000000ull);
				console_write("\n");
			}
		}
	}
}

/* Mount the first virtio disk that carries a filesystem.
 *
 * "vda" used to be hardcoded here, which held only while a board had exactly
 * one virtio disk. Attach a second one and QEMU may well give the newcomer the
 * lower mmio slot — the scratch disk became vda, the root became vdb, and the
 * machine booted onto the initramfs with a perfectly good rootfs sitting one
 * letter away. Try each in turn instead; a disk with no filesystem simply
 * fails to mount, which is the same answer by a shorter route. */
static int mount_first_virtio_root(void)
{
	for (usize i = 0;; i++) {
		struct block_device *dev = blk_nth_on_bus(BLK_BUS_VIRTIO, i);

		if (!dev || !dev->name)
			return -1;
		const char *type;

		if (mount_root_as_probed(dev->name, &type) == 0) {
			char buf[64];

			snprintf(buf, sizeof(buf), "rootfs: %s mounted at / as %s\n", dev->name, type);
			console_write(buf);
			vfs_repopulate_after_root_mount();
			return 0;
		}
	}
}

/* See b1nix.prof-at. */
static void prof_dump_thread(void *arg)
{
	extern void b1nix_prof_dump_all(void);
	u32 seconds = (u32)(usize)arg;

	scheduler_sleep_ticks((u64)seconds * (u64)sched_tick_hz());
	console_write("prof: dump at b1nix.prof-at\n");
	b1nix_prof_dump_all();
}

void kernel_main(usize arg0, usize arg1)
{
#ifdef __x86_64__
	/* Before the first console_write or frame allocation: both ask which CPU
	 * they are on, and the answer must be "none yet", not a stray word. */
	arch_gs_base_early();
#endif
	/* Before anything else that can go deep: the boot stack is still shallow
	 * here, so this is the only point at which the unused part of it can be
	 * painted and its high-water mark made measurable. */
	boot_stack_paint();

#ifdef __aarch64__
	/* And before anything can print: this is what fills in the UART and GIC
	 * base addresses for the board actually underneath us. */
	platform_detect(arg0);
#endif

	serial_init();
	serial_tty_init();
	console_init();
	console_write("\n========================================\n");
	console_write(" b1nix kernel booting on ");
#ifdef __aarch64__
	console_write(platform_name());
	console_write(" (aarch64)");
#else
	console_write("PC (x86_64)");
#endif
	console_write("\n========================================\n");

#ifdef __aarch64__
	console_write("[boot] Scanning FDT at 0x");
	console_write_hex64(arg0);
	console_write("...\n");
	bootinfo_fdt_scan(arg0);
	console_write("[boot] Rebuilding page tables...\n");
	aarch64_boot_map_rebuild();
	console_write("[boot] Boot map rebuild done!\n");
#endif


#ifndef __aarch64__
	console_write("arg0 (magic): 0x");
	console_write_hex32((u32)arg0);
	console_write("\n");
	console_write("arg1 (info):  0x");
	console_write_hex32((u32)arg1);
	console_write("\n");

	if (arg0 != 0x36d76289) {
		console_write("Warning: Multiboot2 magic mismatch\n");
	}
#endif

	/* The command line is parsed before the first line is printed, because it
	 * is what decides whether that line is printed at all: `loglevel=` and
	 * `quiet` cannot filter output that has already gone out. Nothing above
	 * prints, so nothing is lost by doing this first — and a boot that dies in
	 * here still speaks, because the console holds anything printed before this
	 * point and the panic path releases it. */
#ifdef __aarch64__
	bootinfo_init_from_fdt(arg0);
	/* Before anything else can take longer than the bark timeout: a board
	 * whose bootloader left a watchdog armed resets mid-boot otherwise. */
	{
		extern u32 aarch64_platform_watchdog_disable(void);
		extern void fb_boot_num(int row, int value);
		const struct boot_info *bi = bootinfo_get();
		u32 wdt_en = aarch64_platform_watchdog_disable();

		/* Ground truth, kept on screen next to the milestone: did the kernel
		 * recognise this machine at all? Row 1 is platform_type() (1 = QEMU
		 * virt, 2 = RPi4, 3 = SM8150); row 2 is the top byte of the first RAM
		 * bank (0x40 = 64 is QEMU virt's fallback, 0xa9 = 169 is the window
		 * chosen for this phone, 0x80 = 128 means the bootloader's own map got
		 * through). Every platform-specific decision this kernel makes hangs
		 * off the first of those, and nothing else on screen reports it. */
		fb_boot_num(1, platform_type());
		fb_boot_num(2, bi->memory_region_count ?
		                   (int)(bi->memory_regions[0].base >> 24) : 0);
		/* Row 3: WDT_EN read back after being cleared. 0 = the watchdog is
		 * ours and off; 1 = the write was ignored, so the reset that ends
		 * every boot is firmware's and not something this kernel did. */
		fb_boot_num(3, (int)wdt_en);
	}
#else
	bootinfo_init_from_multiboot2((u32)arg0, (u32)arg1);
#endif
	console_log_init();
	BOOTMARK(0);	/* white:   kernel_main entered */

	k_info(NULL, "b1nix kernel starting...");
#ifndef __aarch64__
	k_info("boot", "multiboot2 magic 0x%08x, info at 0x%08x", (u32)arg0,
	       (u32)arg1);

	if (arg0 != 0x36d76289) {
		k_warn("boot", "Warning: Multiboot2 magic mismatch");
	}
#else
	k_info("boot", "FDT blob at 0x%016lx", (u64)arg0);
#endif

	k_info(NULL, "Step 1: Bootinfo parsed");
	/* The command line as the kernel actually received it. Every flag in this
	 * file is read from it, and a run that behaves as though a flag were absent
	 * is indistinguishable from a bug in what the flag controls until this is
	 * on the record. */
	console_write("cmdline: ");
	console_write(bootinfo_cmdline() ? bootinfo_cmdline() : "(none)");
	console_write("\n");

	/* Initialize the BSP per-CPU area (sets the GS base) FIRST: current_task is
	 * now a per-CPU accessor (get_percpu()->cur_task), and pmm/kheap diagnostics
	 * read current_task, so GS must be valid before any of that runs. */
	percpu_init();
	BOOTMARK(1);	/* red:     per-CPU areas up */

	pmm_init(bootinfo_get());
	k_info(NULL, "Step 2: PMM initialized");
	BOOTMARK(2);	/* orange:  PMM initialised */

	/* M77: runtime-tunable global resource caps (TCP slots, pipes, SHMMAX,
	 * coredump). Sized from usable RAM here, after PMM knows how much memory
	 * exists; subsystems read the values back at allocation time. */
	resource_caps_init();

	vmm_init();
	k_info(NULL, "Step 3: VMM initialized");
	BOOTMARK(3);	/* yellow:  VMM initialised */

	kheap_init();
	k_info(NULL, "Step 4: KHeap initialized");
	/* The vDSO's frames, while memory is plentiful and before anything the
	 * clock code publishes into its data page. */
	vdso_init();
	/* Linux's xarray allocates its nodes from the radix-tree node cache, which
	 * this creates from the heap. Before anything stores into an xarray, idr
	 * or page cache — the imported filesystems register and mount long before
	 * the rest of linuxkpi starts. */
	{
		extern void radix_tree_init(void);
		extern void maple_tree_init(void);
		radix_tree_init();
		/* And the maple tree's node cache, which btrfs's lru cache (send,
		 * backref walks) allocates from. */
		maple_tree_init();
	}
	BOOTMARK(4);	/* green:   kernel heap up */

	kheap_use_direct_map();
	/* Symbol lookups stop scanning the whole table now that they can index it:
	 * every %p in a kernel printf used to walk tens of thousands of bytes. */
	ksym_index_init();
	k_info(NULL, "Step 5: KHeap switched to direct map");

	/* Machines whose framebuffer the bootloader already set up. On one whose
	 * display is a device this finds nothing and the second call, after
	 * virtio_gpu_init(), is the one that takes. */
	fb_console_init();
	if (fb_console_ready())
		k_info(NULL, "Step 6: FB Console & Splash initialized");

	/* The splash goes HERE, not at the top of kernel_main where it used to
	 * live: up there the framebuffer console does not exist yet, so every
	 * character went to the log ring and the serial port and none of it was
	 * ever drawn. On a board whose only console is the panel that made the
	 * banner invisible on the one machine it was drawn for. */
	if (!bootinfo_has_flag("b1nix.nosplash")) {
		b1nix_splash_show();
	}
	BOOTMARK(5);	/* cyan:    past fb_console_init */

	scheduler_init();
	k_info(NULL, "Step 7: Scheduler initialized");
	BOOTMARK(6);	/* blue:    scheduler initialised */

	uidgid_init();
	arch_init();
	k_info(NULL, "Step 8: Architecture core initialized");
	BOOTMARK(7);	/* arch_init */
	/* Hand the monotonic clock over to the architecture's fine counter as soon
	 * as one exists. This lived inside the x86_64 block below, next to the
	 * lapic_init that calibrates the TSC -- so on aarch64, where CNTVCT_EL0
	 * needs no calibration at all and arch_tsc_clock_ready() had been
	 * answering yes since boot, the clock stayed on the 100 Hz tick for the
	 * life of the machine. Every timestamp was a multiple of 10 ms, which is
	 * not a cosmetic problem: two directory changes inside one tick got
	 * identical mtimes, and anything that re-reads a directory only when its
	 * mtime moved could not see the second one. No-ops where the counter is
	 * not ready yet; x86_64 calls it again after lapic_init calibrates. */
	ktime_switch_to_tsc();
#if defined(__x86_64__)
	/* Discover CPU + interrupt topology from ACPI (RSDP -> RSDT/XSDT -> MADT)
	 * before LAPIC bring-up: smp_boot_aps prefers the MADT CPU list to the
	 * CPUID guess. Silently no-ops on platforms without ACPI. */
	acpi_init();
	lapic_init();
	/* The TSC is calibrated by lapic_init; hand the monotonic clock over to it
	 * so log timestamps and /proc/uptime gain microsecond resolution. */
	ktime_switch_to_tsc();
	/* Switch IRQ routing from the 8259 PIC to the IOAPIC discovered via
	 * ACPI. No-op (PIC stays in charge) when no IOAPIC was reported. */
	ioapic_init();

	if (lapic_timer_start_periodic_ms(1)) {
		k_info("timer", "LAPIC periodic timer armed at 1 kHz; masking PIT IRQ0");
		ioapic_mask_irq(0);
	} else {
		k_warn("timer", "LAPIC calibration unavailable, keeping PIT IRQ0 active");
	}
#endif

	/* Every PCI function, one stamped line each, before any driver claims
	 * one. pci_init() existed and had no caller, so hardware b1nix has no
	 * driver for was invisible in a boot log — the first thing anyone asks
	 * for when a machine does not work. */
	pci_init();
	/* Publish the bus topology while the enumeration is fresh. The registry
	 * holds it until /sys is mounted, so this does not depend on mount order:
	 * a device with no node in /sys/devices has no parent for udev to match a
	 * rule against, and libdrm cannot answer what bus a card sits on. */
	pci_sysfs_publish_all();
	k_info(NULL, "Step 9: Bus & device discovery");

	blk_cache_init();
	BOOTMARK(8);	/* block cache */
	/* Before initramfs and the filesystems, not after: the page cache's hash
	 * and bucket locks are allocated here now rather than being static arrays,
	 * so anything that reads a file has to run after this point. It needs only
	 * the PMM and the heap, both of which are already up. */
	page_cache_init();
	BOOTMARK(9);	/* page cache */

	initramfs_init();
	BOOTMARK(10);	/* initramfs */
	fuse_init();
	BOOTMARK(40);	/* fuse_init returned */
	k_info(NULL, "Step 10: Initramfs & FUSE initialized");
	BOOTMARK(41);	/* one console line printed — proves printing is not the wall */

	/* M100a: reserve the DMA bounce pool here — early, while nothing has
	 * fragmented the free lists. A bounce block must be physically contiguous,
	 * and taking it at map time would make a mapping's success depend on what
	 * every other allocation did. Needs kheap (for the frame map) and nothing
	 * else, and must precede every driver that could map for DMA. Nothing in
	 * it is x86: a device whose address window misses its buffer needs the
	 * same copy on either arch. */
	dma_bounce_pool_init();
	BOOTMARK(11);	/* DMA bounce pool */

#if defined(__x86_64__)
	/* M100b: bring up DMA remapping before any driver programs a device. Every
	 * function starts in pass-through, so this changes nothing for a driver
	 * that has not asked for translation. */
	iommu_init();
	amdvi_init();
#elif defined(__aarch64__)
	/* M100e: the same thing this board's architecture spells SMMUv3. Same
	 * placement and the same reason — every stream starts bypassing, so a
	 * driver that has not asked for translation sees no difference. Silent
	 * (well, one line) on a machine whose device tree has no such unit, which
	 * is plain `virt` without `iommu=smmuv3`. */
	smmuv3_init();
	BOOTMARK(12);	/* SMMUv3 */
#endif

	vfs_init();
	BOOTMARK(13);	/* VFS */
	fat32_init();
	BOOTMARK(14);	/* PCI bus already discovered at Step 9 */
	/* Both are PCI devices driven through MMIO, and this port has a PCI bus
	 * now (kernel/dev/pci.c over the ECAM window), so they probe on every
	 * arch. On a machine that has no such controller the probe simply finds
	 * nothing. */
	ahci_init();
	BOOTMARK(15);	/* AHCI */
	nvme_init();
	BOOTMARK(16);	/* NVMe */
	/* UFS: QEMU's PCI controller, or a phone's internal storage (the
	 * Qualcomm node, opt-in with b1nix.ufs). Before the root mount, so a
	 * partition labelled b1nix-root on it can become /. */
	ufs_init();
#ifdef __aarch64__
	{
		/* After the log mirror is up, so a watchdog reset leaves a log. */
		extern void aarch64_platform_watchdog_arm(void);
		aarch64_platform_watchdog_arm();
	}
#endif
	ufs_selftest();
	exfat_init();
	tmpfs_init();
	cgroup_init();   /* cgroup v2 — systemd mounts it before anything else */
	procfs_init();
	sysfs_init();
	virtio_9p_init();
	p9_fs_init();
	fwcfgfs_init();
	b1nix_debugfs_init();
	tarfs_init();
#ifdef B1NIX_FS_IMPORT
	/*
	 * The imported btrfs.
	 *
	 * Its own entry point is `static` and reachable only through the wrapper
	 * <linux/init.h> emits from its late_initcall — see the note there. It
	 * registers the filesystem type, allocates its caches and creates
	 * /sys/fs/btrfs; nothing is mounted by it.
	 *
	 * After sysfs_init, because it publishes into /sys, and after
	 * blk_cache_init, because a mount will read through the block cache.
	 */
	{
		extern int lkpi_initcall_init_btrfs_fs(void);
		int rc = lkpi_initcall_init_btrfs_fs();

#if B1NIX_FS_IMPORT_EXT4
		/*
		 * ext4, and the two things it stands on: jbd2 (its journal) and
		 * mbcache (the xattr block deduplication its own registration
		 * expects to be there). Order matters — ext4's init registers with
		 * both.
		 */
		{
			extern int lkpi_initcall_journal_init(void);
			extern int lkpi_initcall_mbcache_init(void);
			extern int lkpi_initcall_ext4_init_fs(void);
			extern int lkpi_initcall_dquot_init(void);
			extern int lkpi_initcall_init_v2_quota_format(void);
			int jrc = lkpi_initcall_journal_init();
			int mrc = lkpi_initcall_mbcache_init();

			/*
			 * Quotas, before ext4: a filesystem with the quota feature turns
			 * them on during its own mount, and it can only find the v2
			 * format if that format has already registered itself.
			 */
			{
				int qrc = lkpi_initcall_dquot_init();
				int frc = lkpi_initcall_init_v2_quota_format();

				if (qrc != 0 || frc != 0)
					klog_warn("lkpi-fs: quota core init failed");
			}
			int erc = (jrc == 0 && mrc == 0) ? lkpi_initcall_ext4_init_fs()
			                                 : -22;

			if (erc != 0)
				klog_error("lkpi-fs: imported ext4 failed to initialise");
			else
				klog_info("lkpi-fs: imported ext4 registered");
		}
#endif

		if (rc != 0) {
			klog_error("lkpi-fs: imported btrfs failed to initialise");
		} else {
			extern void lkpifs_init(void);

			klog_info("lkpi-fs: imported btrfs registered");
			/* And the bridge, which is what lets an ordinary
			 * `mount -t btrfs` serve paths from it. */
			lkpifs_init();
		}
	}
#endif
	BOOTMARK(17);	/* sysfs */
	/* module_init_builtin_deps() used to be called here. It now runs after the
	 * root is mounted (see the note at its remaining call site): the modules
	 * live in /lib/modules, which is only readable once that root is there. */
	BOOTMARK(50);
	filelock_init();
	BOOTMARK(51);
	mqueue_init();
	BOOTMARK(52);
	shm_init();
	BOOTMARK(53);
	sysv_ipc_init(); /* SysV semaphores + message queues */
	BOOTMARK(54);
	swap_init();
	BOOTMARK(55);
	net_init();
	BOOTMARK(18);	/* net */
	/* klog over UDP (b1nix.netconsole=<ip>:<port>): a network interface and a
	 * UDP socket, nothing architectural. */
	netconsole_init();
	/* M79: the Intel 82801AA AC'97 controller (/dev/dsp1). A PCI card, so it
	 * is not an x86 device even though its registers sit behind an I/O BAR:
	 * on a machine with no port-I/O instructions those accesses go through
	 * the host bridge's I/O window instead (kernel/arch/aarch64/io.c). */
	ac97_init();
	BOOTMARK(19);	/* ac97 */
#if defined(__x86_64__)
	ps2_kbd_init();
	ps2_mouse_init();
	/* M102a: the boot CPU's family/model and cache geometry, read before any
	 * driver probes — a quirk keyed on model must not match a zeroed struct,
	 * and the cache line size is a divisor in imported flush loops. This used
	 * to run after the GPU drivers and the flush loops spun on a zero. It reads
	 * CPUID, so it lives inside this guard with the rest. */
	lkpi_cpuinfo_init();
	video_init();
#elif defined(__aarch64__)
	bcm2835_mbox_init();
	bcm2835_gpio_init();
	bcm2835_systimer_init();
	bcm2835_pm_init();
	BOOTMARK(20);	/* bcm2835 block */
#endif
	/* M37: the xHCI controller is PCI + MMIO, and this arch reaches PCI through
	 * its ECAM window, so the USB stack is not x86-only; its HID keys go
	 * through the same scancode translation the PS/2 driver owns.
	 *
	 * It probes HERE, not with ahci/nvme before sysfs_init(). Moving it earlier
	 * did put the USB stick into /sys/block, but on the one lane that has a USB
	 * *disk* the early registration walked into an unfinished block layer and
	 * took the machine down with an unknown-EC fault in module space. A
	 * removable disk missing from /sys/block is a reporting gap; this was a
	 * dead lane. */
	xhci_probe();
	BOOTMARK(21);	/* xHCI probe */
	input_init(); /* M47: /dev/input/event* (PS/2 kbd + mouse event streams) */
	BOOTMARK(22);	/* input */
	if (bootinfo_has_flag("b1nix.gfxtest=1"))
		input_gfxtest_start(); /* diagnostic: headless window-drag injector */
	if (bootinfo_has_flag("b1nix.test=1"))
		input_m47_inject_start(); /* M47 smoke: mouse event burst for readers */
	virtio_gpu_init();
	BOOTMARK(23);	/* virtio-gpu */
	fb_console_init(); /* a virtio-gpu display can carry the text console */
	if (bootinfo_has_flag("b1nix.test=1")) {
		extern void fb_console_selftest(void);
		fb_console_selftest();
	}
	if (!bootinfo_has_flag("b1nix.nosplash")) {
		b1nix_splash_show();
	}
#ifdef B1NIX_FS_IMPORT
	/*
	 * The imported filesystem's proof: mount a real btrfs image.
	 *
	 * Here rather than beside the registration above because it needs the
	 * block devices, and those are probed later in this function. The device
	 * is named on the command line so the harness can attach whichever disk
	 * it made — hard-coding one would tie the test to the harness's ordering.
	 */
	{
		static char lkpi_fs_dev[32];

		/* Returns 1 on a match, not 0: the value is copied only then. */
		if (bootinfo_get_kv("b1nix.lkpi-btrfs-test", lkpi_fs_dev,
		                    sizeof(lkpi_fs_dev)) == 1) {
			extern void lkpi_btrfs_mount_test_thread(void *arg);
			extern void lkpi_btrfs_mount_watch_thread(void *arg);

			/*
			 * In a thread, not inline.
			 *
			 * Mounting a btrfs filesystem starts its worker threads and waits
			 * for them — open_ctree reads the chunk tree through its own
			 * workers — and nothing can wait for a thread before the
			 * scheduler is running. Called from here directly, the mount
			 * reached the superblock and then stopped forever.
			 *
			 * The buffer is static for the same reason: the thread outlives
			 * this stack frame.
			 */
			if (kthread_create("lkpi-btrfs-test",
			                   lkpi_btrfs_mount_test_thread,
			                   lkpi_fs_dev) < 0)
				klog_error("lkpi-fs: could not start the btrfs mount test");
			/*
			 * A watchdog beside it: if the mount has not finished after
			 * twenty seconds it is wedged, and the profile says where. A
			 * wedged mount otherwise reports nothing at all — the thread is
			 * running, so no wait shows up in the task dump.
			 */
			if (kthread_create("lkpi-btrfs-watch",
			                   lkpi_btrfs_mount_watch_thread, 0) < 0)
				klog_error("lkpi-fs: could not start the mount watchdog");
		}
	}
#endif
#if defined(B1NIX_I915) && B1NIX_I915
	/*
	 * M102a: Intel i915. The driver's module init registers its PCI driver,
	 * and pci_register_driver() is what walks the bus and probes — see the
	 * note there. Nothing happens on a machine with no Intel GPU: the id
	 * table matches nothing and registration reports success.
	 *
	 * After virtio_gpu_init() on purpose. On a machine with both, the one
	 * that came up first keeps card0, and virtio-gpu is the one M101 is
	 * proved against.
	 */
	if (bootinfo_has_flag("b1nix.drm-debug")) {
		__drm_debug = B1NIX_DRM_DEBUG_MASK;
		if (kthread_create("drm-stuck-watch", drm_stuck_watch_thread, 0) < 0)
			k_err("drm-stuck-watch", "thread refused");
	}
	/* The atomic and state categories as well, when asked. KMS alone shows what
	 * a modeset was computed to be; these show what the commit then did with
	 * it, which is the difference between "the driver planned to enable a pipe"
	 * and "the driver enabled it". */
	if (bootinfo_has_flag("b1nix.drm-debug-atomic"))
		__drm_debug |= 0x04UL | 0x10UL | 0x40UL;
	i915_module_init();
	/*
	 * Publish the driver's card to b1nix's DRM bridge, so userspace can open
	 * and mmap its objects. Harmless when i915 did not bind: the lookup finds
	 * no device and registers nothing.
	 */
	{
		struct drm_device *card = lkpi_drm_first_device();

		if (card)
			lkpi_i915_register_card(card);
		if (card && bootinfo_has_flag("b1nix.i915-mmio-bench")) {
			extern void lkpi_i915_mmio_bench(struct drm_device *d);
			lkpi_i915_mmio_bench(card);
		}
		/* And, when asked, whether the GT behind that card will run
		 * anything: engines, address space, and one empty request per
		 * engine taken to retirement. Costs nothing when the flag is
		 * absent, and nothing at all when i915 did not bind. */
		{
			extern void lkpi_i915_gt_probe(struct drm_device *dev)
				__attribute__((weak));

			if (card && lkpi_i915_gt_probe)
				lkpi_i915_gt_probe(card);
		}
	}
	/*
	 * Stop here when the boot exists only to exercise the display.
	 *
	 * Everything past this point — filesystems, init, the test suite — takes
	 * minutes and touches nothing the display path uses. Bringing a GPU up is
	 * an edit-run loop, and a loop whose slowest step is unrelated to what is
	 * being changed stops being one. This ends the boot the moment the picture
	 * has been produced, so the answer arrives while the question is still in
	 * hand.
	 *
	 * The same ports the reboot syscall writes, for the same reason: QEMU
	 * versions disagree about which one shuts the machine down, so all three
	 * are tried before falling back to halting.
	 */
	/* Defined by the DRM mirror when the imported stack is built in. */
	extern void lkpi_i915_dump_port_state_pub(void) __attribute__((weak));

	/*
	 * Watch the port while userspace runs.
	 *
	 * The display probes above all run before init, which answers what the
	 * kernel's own client did and nothing about what a compositor does later.
	 * b1nix.port-watch=<seconds> repeats the port dump from a thread, so a
	 * modeset issued from userspace — or the absence of one — is visible in the
	 * same log as the compositor's own messages.
	 */
	{
		char pw[8];

		if (bootinfo_get_kv("b1nix.port-watch", pw, sizeof(pw)) &&
		    !lkpi_i915_dump_port_state_pub)
			k_info("port-watch", "no i915 dump in this build");
		if (lkpi_i915_dump_port_state_pub &&
		    bootinfo_get_kv("b1nix.port-watch", pw, sizeof(pw))) {
			unsigned n = 0;

			for (const char *p = pw; *p >= '0' && *p <= '9'; p++)
				n = n * 10u + (unsigned)(*p - '0');
			g_port_watch_period = n ? n : 10;
			console_write("port-watch: every ");
			console_write_dec((u64)g_port_watch_period);
			console_write("s\n");
			if (kthread_create("port-watch", port_watch_thread, 0) < 0)
				k_err("port-watch", "thread refused");
		}
	}

	if (bootinfo_has_flag("b1nix.gfx-only")) {
		/*
		 * The boot exists only to bring the display up: stop before init.
		 *
		 * It used to hold the frame on the wire for a while first, because the
		 * only witness to a modeset was a person watching the screen and the
		 * picture vanished at power-off. It is not the witness any more — the
		 * compositor's own run photographs the panel and reads the registers
		 * back — so the hold, and the flags that tuned it, are gone.
		 */
		k_info(NULL, "B1NIX-GFX: done");
		outw(0x604, 0x2000);
		outw(0xB004, 0x2000);
		outw(0x4004, 0x3400);
		arch_halt();
	}
#endif
	virtio_input_init(); /* absolute pointer (virtio-tablet) — grab-free mouse */
	virtio_console_init(); /* /dev/hvc0, console=hvc0 */








	fb_dev_init(); /* M47: /dev/fb0 mmap-able framebuffer (needs fb_console) */
	nbd_init();    /* /dev/nbd0.. present and empty until a client attaches */
	md_init();     /* /dev/md0.. present and empty until raidautorun fills one */
	mtd_init();    /* CFI NOR flash, when b1nix.mtd asks for the probe */
	BOOTMARK(24);	/* /dev/fb0 */
	drm_dev_init(); /* M50: minimal DRM/KMS dumb-buffer device over virtio-gpu */
	BOOTMARK(25);	/* DRM */
	/* M101t: the imported core comes up here rather than in the test block —
	 * /dev/dri/card1 is a device userspace opens, not a self-test. The order
	 * matters: the node is only registered once a device exists behind it.
	 */
	drm_kms_device_init();
	BOOTMARK(26);	/* drm_kms_device_init */
	drm_card1_init();
	BOOTMARK(27);	/* drm_card1_init */
	virtio_gpu_dev_init(); /* M53: /dev/virtio-gpu userspace VirGL 3D transport */
	BOOTMARK(28);	/* virtio_gpu_dev_init */
	ramdisk_init();
	BOOTMARK(29);	/* ramdisk_init */
	loop_init();            /* loop block devices + /dev/loop-control */
	BOOTMARK(30);	/* loop_init */
	vt_init();              /* M107 virtual terminals + console font/keymap */
	BOOTMARK(31);	/* magenta: device init survived, VTs up */
	kmsg_init();            /* M107 /dev/kmsg record ring */
	rtc_dev_init();         /* M107 /dev/rtc0 */
	watchdog_init();        /* M107 /dev/watchdog */
	i2c_init();             /* M107 SMBus host controller, if one exists */
	blk_create_dev_nodes(); /* /dev/<blkdev> nodes for blkid/fdisk/loopN */
	if (bootinfo_has_flag("b1nix.diskbench")) {
		const char *db_argv[] = {"diskbench", 0};
		user_spawn("/bin/diskbench", 1, db_argv);
	}

	/* M92 musl smoke test: must run BEFORE rootfs mount because the binary
	 * lives in the initramfs which gets hidden when ram0 ext4 is mounted at /.
	 * userspace_init() just registers builtins — safe to call early. */
	if (bootinfo_has_flag("b1nix.muslrun")) {
		userspace_init();
		char musl_buf[64];
		/* Run raw diagnostic first, then hello, then full smoke test. */
		const char *raw_argv[] = {"m92-musl-raw-diag", 0};
		int raw_pid = user_spawn("/bin/m92-musl-raw-diag", 1, raw_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-raw-diag: %d\n", raw_pid);
		console_write(musl_buf);
		if (raw_pid > 0) {
			int musl_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)raw_pid, (u64)(usize)&musl_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-raw-diag exit=%d\n", musl_st);
			console_write(musl_buf);
		}
		const char *hello_argv[] = {"m92-musl-hello", 0};
		int hello_pid = user_spawn("/bin/m92-musl-hello", 1, hello_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-hello: %d\n", hello_pid);
		console_write(musl_buf);
		if (hello_pid > 0) {
			int musl_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)hello_pid, (u64)(usize)&musl_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-hello exit=%d\n", musl_st);
			console_write(musl_buf);
		}
		const char *step2_argv[] = {"m92-musl-step2", 0};
		int step2_pid = user_spawn("/bin/m92-musl-step2", 1, step2_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-step2: %d\n", step2_pid);
		console_write(musl_buf);
		if (step2_pid > 0) {
			int musl_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)step2_pid, (u64)(usize)&musl_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-step2 exit=%d\n", musl_st);
			console_write(musl_buf);
		}
		/* M92 dynamic musl test — PIE/ET_DYN linked against ld-musl-x86_64.so.1 */
		const char *musl_dyn_argv[] = {"m92-musl-dyn-smoke", 0};
		int musl_dyn_pid = user_spawn("/bin/m92-musl-dyn-smoke", 1, musl_dyn_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-dyn-smoke: %d\n", musl_dyn_pid);
		console_write(musl_buf);
		if (musl_dyn_pid > 0) {
			int musl_dyn_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)musl_dyn_pid, (u64)(usize)&musl_dyn_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-dyn-smoke exit=%d\n", musl_dyn_st);
			console_write(musl_buf);
		}
		/* M92-LDSO (musl-port.md): PT_INTERP =
		 * /lib/ld-musl-x86_64.so.1. The kernel loads only the interpreter's own
		 * segments and jumps into it; musl's real ld.so links this binary
		 * itself — no in-kernel eager linker involved. */
		const char *musl_ldso_argv[] = {"m92-musl-ldso-smoke", 0};
		int musl_ldso_pid = user_spawn("/bin/m92-musl-ldso-smoke", 1, musl_ldso_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-ldso-smoke: %d\n", musl_ldso_pid);
		console_write(musl_buf);
		if (musl_ldso_pid > 0) {
			int musl_ldso_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)musl_ldso_pid, (u64)(usize)&musl_ldso_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-ldso-smoke exit=%d\n", musl_ldso_st);
			console_write(musl_buf);
		}
		/* M92-POSIX: musl POSIX smoke test — compiled with LINK=musl against
		 * musl's libc.so via /lib/ld-musl-x86_64.so.1 real interpreter. */
		const char *musl_posix_argv[] = {"musl-posix-smoke", 0};
		int musl_posix_pid = user_spawn("/bin/musl-posix-smoke", 1, musl_posix_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn musl-posix-smoke: %d\n", musl_posix_pid);
		console_write(musl_buf);
		if (musl_posix_pid > 0) {
			int musl_posix_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)musl_posix_pid, (u64)(usize)&musl_posix_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: musl-posix-smoke exit=%d\n", musl_posix_st);
			console_write(musl_buf);
		}
	}

	/* Prefer a real ext4 root over the bootstrap initramfs.  Native runs use
	 * vda (aarch64 registers its virtio-mmio disk under the same name);
	 * Live CD boots use the multiboot ramdisk block device ram0.
	 * In test mode the smoke suite owns the drives, so keep initramfs as /. */
	{
		int rc = -1;
		char root_val[64];
		if (bootinfo_get_kv("root", root_val, sizeof(root_val))) {
			if (strcmp(root_val, "initramfs") == 0) {
				/* Keep the RAM filesystem as /, the way Linux does before an
				 * initramfs hands over with switch_root. The boot then has a
				 * real root to move onto / itself, rather than one the kernel
				 * already mounted there. */
				console_write("rootfs: staying on the initramfs (root=initramfs)\n");
				rc = 0;
				vfs_repopulate_after_root_mount();
			} else if (strcmp(root_val, "liveiso") == 0) {
				k_info("rootfs", "liveiso mount requested, searching for the boot medium...");
				const char *iso_fstype = 0;
				char mounted_iso_name[64];
				mounted_iso_name[0] = '\0';
				/* USB enumeration is asynchronous, so the medium may not be
				 * registered yet. Retry while no removable device has shown up
				 * at all; once one has, one search over every device settles
				 * it — waiting longer would not change the answer. */
				struct block_device *iso_dev = 0;
				for (int retries = 0; retries < 50; retries++) {
					iso_dev = find_live_medium(&iso_fstype);
					if (iso_dev)
						break;
					if (blk_first_removable())
						break;
					scheduler_sleep_ticks(SCHED_MS_TO_TICKS(100));
				}

				int is_exfat = 0;
				if (iso_dev) {
					rc = 0;
					is_exfat = strcmp(iso_fstype, "exfat") == 0;
					snprintf(mounted_iso_name, sizeof(mounted_iso_name), "%s", iso_dev->name);
					console_write(is_exfat ? "exfat: mounted " : "isofs: mounted ");
					console_write(iso_dev->name);
					console_write(" at /mnt/iso\n");
				}

				if (rc == 0) {
					struct block_device *loop_dev = loop_register_file("/mnt/iso/boot/rootfs.img");
					if (loop_dev && !IS_ERR(loop_dev)) {
						char loop_buf[96];
						snprintf(loop_buf, sizeof(loop_buf), "%s: %s backing /boot/rootfs.img\n",
							 is_exfat ? "livefile" : "loop", loop_dev->name);
						console_write(loop_buf);
						/* If we are running in test/smoke mode, we mount at /mnt/root
						 * to keep the bootstrap initramfs as active root.
						 * Otherwise (on real hardware or normal boots), we mount
						 * loop0 as the primary rootfs at /. */
						{ const char *loop_type; rc = mount_root_as_probed(loop_dev->name, &loop_type); }
						if (rc == 0) {
							snprintf(loop_buf, sizeof(loop_buf), "rootfs: %s mounted at /\n", loop_dev->name);
							console_write(loop_buf);
							vfs_repopulate_after_root_mount();
								if (mounted_iso_name[0] != '\0') {
									int remount_rc = vfs_mount(mounted_iso_name, "/mnt/iso", is_exfat ? "exfat" : "iso9660", 0);
									if (remount_rc == 0) {
										if (is_exfat) {
											console_write("exfat: remounted at /mnt/iso after root switch\n");
										} else {
											k_info("isofs", "remounted at /mnt/iso after root switch");
										}
									} else {
										char err_buf[80];
										snprintf(err_buf, sizeof(err_buf), "%s: remount after root switch failed: %d\n", is_exfat ? "exfat" : "isofs", remount_rc);
										console_write(err_buf);
									}
								}
							if (is_exfat) {
								console_write("M37-LIVEFILE: ok exfat-loop-root\n");
							} else {
								k_info(NULL, "M37-LIVEISO: ok isofs-loop-root");
							}
						}
					} else {
						rc = -1;
					}
				}

				if (rc != 0) {
					k_err("rootfs", "liveiso mount failed, falling back to ram0...");
					{ const char *ram_type; rc = mount_root_as_probed("ram0", &ram_type); }
					if (rc == 0) {
						k_warn("rootfs", "ram0 mounted at / (Live CD fallback)");
						vfs_repopulate_after_root_mount();
					} else {
						char mount_err_buf[64];
						snprintf(mount_err_buf, sizeof(mount_err_buf), "rootfs: fallback mount failed: %d\n", rc);
						console_write(mount_err_buf);
						vfs_repopulate_after_root_mount();
					}
				}
			} else {
				char fstype_val[32] = {0};
				bootinfo_get_kv("rootfstype", fstype_val, sizeof(fstype_val));

				if (strcmp(root_val, "9p") == 0 || strcmp(root_val, "hostshare") == 0 || strcmp(fstype_val, "9p") == 0) {
					rc = vfs_mount(root_val[0] ? root_val : "hostshare", "/", "9p", 0);
					if (rc == 0) {
						console_write("rootfs: mounted on / as 9p (fast host pass-through)\n");
						boot_summary_set_root("hostshare (9p)");
						vfs_repopulate_after_root_mount();
					}
				} else {
					struct block_device *root_dev = find_root_device(root_val);
					if (!root_dev) {
						console_write("rootfs: waiting for root device ");
						console_write(root_val);
						console_write("...\n");
						int retries = 0;
						while (retries < 50) {
							scheduler_sleep_ticks(SCHED_MS_TO_TICKS(100));
							root_dev = find_root_device(root_val);
							if (root_dev) {
								break;
							}
							retries++;
						}
					}
					if (root_dev) {
						if (fstype_val[0]) {
							rc = vfs_mount(root_dev->name, "/", fstype_val, 0);
							if (rc == 0) {
								char mounted_buf[96];
								snprintf(mounted_buf, sizeof(mounted_buf), "rootfs: %s mounted at / as %s\n", root_dev->name, fstype_val);
								console_write(mounted_buf);
								vfs_repopulate_after_root_mount();
							}
						}
						if (rc != 0) {
							const char *type = "tarfs";

							rc = mount_root_as_probed(root_dev->name, &type);
							if (rc != 0)
								rc = vfs_mount(root_dev->name, "/", "tarfs", 0);
							if (rc == 0) {
								char mounted_buf[96];
								snprintf(mounted_buf, sizeof(mounted_buf), "rootfs: %s mounted at / as %s\n", root_dev->name, type);
								console_write(mounted_buf);
								vfs_repopulate_after_root_mount();
							}
						}
					}
					if (rc != 0) {
						char mount_err_buf[96];
						snprintf(mount_err_buf, sizeof(mount_err_buf), "rootfs: staying on initramfs, failed to mount root: %s\n", root_val);
						console_write(mount_err_buf);
						vfs_repopulate_after_root_mount();
					}
				}
			}
		} else {
			/*
			 * No root= on the command line: choose by what the filesystem says
			 * it is (labelled disk 'b1nix-root'), ram0, or virtio block.
			 */
			rc = -1;
			{
				struct block_device *labelled = find_device_by_label("b1nix-root");

				if (labelled) {
					const char *type = "?";

					rc = mount_root_as_probed(labelled->name, &type);
					if (rc == 0) {
						char buf[96];

						snprintf(buf, sizeof(buf),
						         "rootfs: %s (label b1nix-root) mounted at / as %s\n",
						         labelled->name, type);
						console_write(buf);
						boot_summary_set_root(labelled->name);
						vfs_repopulate_after_root_mount();
					}
				}
			}
			if (rc != 0) {
				{ const char *ram_type; rc = mount_root_as_probed("ram0", &ram_type); }
				if (rc == 0) {
					console_write("rootfs: ram0 mounted at /\n");
					boot_summary_set_root("ram0");
					vfs_repopulate_after_root_mount();
				}
			}
			if (rc == 0) {
				/* mounted above */
			} else if ((rc = mount_first_virtio_root()) == 0) {
				/* named inside the helper */
			} else {
				/* Try finding a block device by default label 'b1nix-root' (e.g. USB flash drive) */
				struct block_device *root_dev = find_device_by_label("b1nix-root");
				if (root_dev) {
					const char *type = "?";

					rc = mount_root_as_probed(root_dev->name, &type);
					if (rc == 0) {
						char mounted_buf[96];
						snprintf(mounted_buf, sizeof(mounted_buf), "rootfs: %s (label b1nix-root) mounted at / as %s\n", root_dev->name, type);
						console_write(mounted_buf);
						vfs_repopulate_after_root_mount();
					}
				}
				if (rc != 0) {
					{ const char *ram_type; rc = mount_root_as_probed("ram0", &ram_type); }
					if (rc == 0) {
						console_write("rootfs: ram0 mounted at /\n");
						boot_summary_set_root("ram0");
						vfs_repopulate_after_root_mount();
					} else {
						char mount_err_buf[64];
						snprintf(mount_err_buf, sizeof(mount_err_buf), "rootfs: staying on initramfs, mount failed: %d\n", rc);
						console_write(mount_err_buf);
						vfs_repopulate_after_root_mount();
					}
				}
			}
		}
	}

	/* M34: mount synthetic filesystems after the final root is selected, so
	 * they sit on top of /proc and /sys in the real root image. */
	vfs_mkdir("/proc", 0555);
	if (vfs_mount("proc", "/proc", "procfs", 0) == 0)
		console_write("procfs: mounted at /proc\n");
	vfs_mkdir("/sys", 0555);
	if (vfs_mount("sys", "/sys", "sysfs", 0) == 0)
		k_info("sysfs", "mounted at /sys");
	/* BusyBox sysctl chdirs to /proc/sys; point at /sys where the actual
	 * files live (kernel.osrelease → /sys/kernel/osrelease). */
	vfs_symlink("/sys", "/proc/sys");
	if (bootinfo_has_flag("b1nix.task-watch") &&
	    kthread_create("task-watch", task_watch_thread, 0) < 0)
		k_err("task-watch", "thread refused");
	/* M95: load the optional filesystems, the HDA sound driver and the IPv6
	 * protocol modules from /lib/modules. Each is optional — the kernel boots
	 * and passes its tests with any of them absent.
	 *
	 * After the root filesystem is mounted, not before. They live in
	 * /lib/modules, and while the root arrived as a boot module already in
	 * memory that was available from the first instant; served off a disk it
	 * is not, and every one of them failed to load with ENOENT. Nothing
	 * earlier in the boot needs them — they are optional filesystems, a sound
	 * driver and a network protocol — so the load belongs on this side of the
	 * mount. */
	module_init_builtin_deps();

	k_info(NULL, "Step 11: Drivers initialized");
	/* The splash again, for a framebuffer that only a driver provided. */
	if (!bootinfo_has_flag("b1nix.nosplash")) {
		b1nix_splash_show();
	}

#if defined(__aarch64__)
	/* The secondary CPUs, over PSCI. They run stealable kernel workers only
	 * for now (kernel/arch/aarch64/smp.c says what is still missing before
	 * userspace can run on one), which is what the M24b work-stealing and
	 * M28 heap-benchmark checks exercise. */
	BOOTMARK(69);
	smp_boot_aps();
	BOOTMARK(70);
#endif

#if defined(__x86_64__)
	/* Bring up Application Processors */
	smp_boot_aps();

	/* Each AP turns CR4.SMEP on for itself and stays quiet about it (its line
	 * would land inside the one smp_boot_aps is writing). Report the tally here
	 * instead, so the bit is accounted for on every core and not just the one
	 * that printed at arch_init. */
	{
		extern int arch_smep_cpu_count(void);
		int smep_cpus = arch_smep_cpu_count();

		char smep_line[64];

		/* One write: an AP's message printed between the pieces of a
		 * multi-call line ended up in the middle of it. */
		snprintf(smep_line, sizeof(smep_line), "smep: active on %d of %d CPUs\n",
		         smep_cpus, (int)get_online_cpu_count());
		console_write(smep_line);
	}

	/* Do the cores agree about what a page-table entry means?
	 *
	 * They did not: the AP trampoline set CR4.PGE and boot.S did not, so bit 8
	 * of a leaf entry was a software flag on the boot CPU and the GLOBAL bit on
	 * every other one. Nothing was in a position to notice, because no check
	 * had ever compared one core's control registers against another's. This
	 * is that check, and it runs on every boot rather than in test mode: a
	 * divergence here silently changes the memory model.
	 */
	{
		extern int x86_check_cpu_state_uniform(void);

		(void)x86_check_cpu_state_uniform();
	}

	/* M28 T4: enable cross-CPU TLB shootdown. With BKL out of syscall_entry.S
	 * (T4), two CPUs can simultaneously execute vmm_unmap_page on different
	 * pml4s; without shootdown, the stale TLB entry on another CPU lets a
	 * write hit the freed-and-reused physical frame. Safe to enable here
	 * because all APs have come up and have functional LAPICs to ACK IPIs. */
	tlb_shootdown_set_enabled(1);
#endif

	/* M101: reserve the lkpi vmap window's page-table path. Must happen before
	 * any process is created, so every address space inherits the entry. */
	lkpi_page_init();
	BOOTMARK(71);

	/* M101: start RCU's deferred-callback thread. After the APs are up, since
	 * it creates a worker thread, and before any driver can call call_rcu. */
	rcu_init();
	BOOTMARK(72);

	/* Both linuxkpi work pools, here rather than on first use. Created lazily,
	 * the second one is allocated from inside a work item that is already
	 * waiting on it, and its thread never gets to run — see the note in
	 * kernel/lkpi/workqueue.c. Starting them from ordinary kernel context is
	 * also what Linux does. */
	(void)lkpi_system_wq();
	(void)lkpi_system_unbound_wq();

	/* In-kernel SMP self-tests. These run BEFORE g_ap_userspace_enabled: they
	 * need the APs still parked in the work-stealing-only loop (that loop is
	 * the only path that knows how to execute a stealable worker). The init.c
	 * rewrite dropped these three calls, which silently removed the
	 * M24B-SMP/M28-BENCH markers — the SMP instance then had no done-pattern
	 * to match and ran the whole suite until the host stall watchdog shot it.
	 * All three are no-ops outside b1nix.test=1 / on single-CPU systems. */
	smp_selftest_run();
	BOOTMARK(73);
	m28_heapbench_run();
	BOOTMARK(74);
	m28_ctxbench_run();
	BOOTMARK(75);
	/* M101: the RCU grace-period proof belongs here for the same reason. It
	 * needs a reader running on another CPU at the same moment as the writer,
	 * and a stealable worker picked up by a parked AP is the only placement
	 * this kernel guarantees. Later, once the APs run the ordinary scheduler,
	 * the reader lands wherever it lands — in practice back on the BSP, where
	 * it cannot overlap the writer at all. */
	lkpi_rcu_smp_selftest();
	BOOTMARK(76);

	/* M37 device self-tests. Their only caller used to be the in-kernel test
	 * driver in kernel/user/programs.c, deleted with the ring-3 migration —
	 * which silently dropped the whole M37-E1000 marker set and the USB
	 * HID-translate check (the xHCI markers that do appear come from the
	 * driver's own probe, not from this test). Both are no-ops outside
	 * b1nix.test=1 / without the hardware. */
	if (bootinfo_has_flag("b1nix.test=1")) {
		/* Both drivers are MMIO over PCI and both come up on this arch now
		 * (M37), so their self-tests belong to both. Each is a no-op when its
		 * device is absent. */
		e1000_selftest();
		usb_selftest();
		/* M38/M79 audio device self-tests. Both are no-ops outside
		 * b1nix.test=1 / without the device. Re-register the /dev/dsp*
		 * nodes here too: the nodes created at early boot land on the
		 * initramfs root, which becomes unreachable once the ext4 root is
		 * mounted, so this second registration is what makes /dev/dsp and
		 * /dev/dsp1 visible to userspace.
		 *
		 * Both run on both arches. AC'97 reaches its registers through I/O
		 * ports, which an AArch64 CPU does not have - so there they are
		 * accesses into the host bridge's I/O window instead
		 * (kernel/arch/aarch64/io.c), and the card answers the same. */
		sound_module_dev_init();
		sound_module_selftest();
		ac97_dev_init();
		ac97_selftest();
		/* ioprio(2): the block layer's admission policy — better priority
		 * first, and a starving idle-class request ages past a stream of
		 * best-effort ones. Drives the real chooser with synthetic waiters. */
		{
			extern int blk_io_gate_selftest(void);
			int io_rc = blk_io_gate_selftest();
			if (io_rc == 0) {
				k_info(NULL, "M40-IOPRIO: ok elevator-order");
			} else {
				console_write("M40-IOPRIO: FAIL elevator-order check=");
				console_write_dec((u64)io_rc);
				console_write("\n");
			}
		}
		m36_gdb_selftest();
		m36_ftrace_selftest();
		/* M98 memory typing and cache maintenance. Both arches implement it,
		 * spelled differently (IA32_PAT + CLFLUSH vs an MAIR slot + DC CIVAC /
		 * a set/way walk) — see kernel/arch/aarch64/memtype.c. The PAT-MSR
		 * readback is the one check with no counterpart there, and the harness
		 * skips that one alone rather than the whole group. */
		memtype_selftest();
		/* M98 modern PCI: BAR sizing, capability walk, bus master, MSI/MSI-X,
		 * Intel stolen memory. This used to sit behind the x86_64 guard above
		 * because "this port has no PCI host bridge" — it has one now (ECAM on
		 * QEMU virt, which is how e1000/xHCI/NVMe are found here), so the
		 * bus-level half of the test applies to both arches. The Intel-only
		 * parts detect their own absence and say so. */
		pci_selftest();
		/* The wall clock's civil-date conversion, against known answers.
		 * Calendar arithmetic, so it runs on both arches (kernel/dev/rtc_dev.c). */
		rtc_selftest();
		/* btrfs, when a disk carrying one is attached: read a filesystem
		 * mkfs.btrfs wrote and check what comes back. */
		btrfs_selftest();
		/* The block cache under a concurrent reader and writer, checked
		 * against the medium; only with the disk tests/smoke.sh marks. */
		blk_cache_selftest();
#ifdef B1NIX_FS_IMPORT
		/* The same thing through the bridge: b1nix's VFS mounting an
		 * imported filesystem and serving paths from it. Here rather than
		 * beside the import's own registration because it mounts by PATH,
		 * and there is no /mnt until the root filesystem is up. */
		{
			static char lkpi_bridge_dev[32];

			if (bootinfo_get_kv("b1nix.lkpi-bridge-test", lkpi_bridge_dev,
			                    sizeof(lkpi_bridge_dev)) == 1) {
				extern void lkpifs_selftest(const char *dev);

				lkpifs_selftest(lkpi_bridge_dev);
			}
#if B1NIX_FS_IMPORT_EXT4
			/* And the same over ext4, on its own device. */
			if (bootinfo_get_kv("b1nix.lkpi-ext4-test", lkpi_bridge_dev,
			                    sizeof(lkpi_bridge_dev)) == 1) {
				extern void lkpifs_selftest_type(const char *dev,
				                                 const char *fstype,
				                                 const char *mnt);
				extern void lkpi_btrfs_mount_watch_thread(void *arg);

				/* The same watchdog the btrfs self-test uses: a mount that
				 * wedges reports nothing on its own, and this turns "it
				 * hangs" into a function name. */
				kthread_create("lkpi-mount-watch",
				               lkpi_btrfs_mount_watch_thread, 0);
				lkpifs_selftest_type(lkpi_bridge_dev, "ext4",
				                     "/mnt/lkpi-ext4");
			}
#endif
		}
#endif
		/* The nice/stride weighting, where the numbers live: the M46
		 * userspace test can only observe the bias statistically. */
		sched_nice_selftest();
		/* netconsole is the klog ring over UDP — protocol, not hardware.
		 * It only sat behind the x86_64 guard because it was written next
		 * to the PAT/PCI tests above. */
		netconsole_selftest();

		/* Boot-log format: timestamps, the severity filter and the
		 * agreement between the console and the dmesg ring. */
		log_format_selftest();

		/* The rest of this group is protocol logic, not hardware, and
		 * belongs on every arch — it was only ever inside the x86_64
		 * guard because it was written next to the PCI/PAT tests above.
		 * On aarch64 that silently dropped every M84 marker.
		 *
		 * M32/M96: IPv6 self-tests (loopback ::1 ICMPv6 + MLD, SLAAC and
		 * ping over usernet) run through the protocol registry — they
		 * live in ipv6.ko and are absent when it is not loaded.
		 * M84: IPv4 FIB (longest-prefix-match, host routes, metric
		 * tie-break) and TCP robustness (option parsing, window scaling,
		 * out-of-order reassembly). */
		net_proto_selftest();
		route_smoke();
		tcp_robustness_smoke();
		dhcpv6_smoke();

		/* M94: init-path parsing self-test. Verify bootinfo_get_kv
		 * correctly extracts the `init=` parameter (or falls back to
		 * /sbin/init). */
		{
			char m94_path[128];
			int m94_got = bootinfo_get_kv("init", m94_path,
			                              sizeof(m94_path));
			if (m94_got && m94_path[0] != '\0') {
				console_write("M94-INIT: ok init=");
				console_write(m94_path);
				console_write("\n");
			} else {
				k_info(NULL, "M94-INIT: ok default /sbin/init");
			}
			/* Verify flag detection (flags are absent in normal test boot). */
			int m94_single = bootinfo_has_flag("b1nix.single");
			if (m94_single) {
				k_info(NULL, "M94-INIT: ok single-flag");
			} else {
				k_info(NULL, "M94-INIT: ok no-override-flags");
			}
		}
	}

	/* The work-stealing self-test is done; let APs leave the work-stealing-only
	 * loop and run the full cooperative scheduler (ordinary userspace processes)
	 * under the Big Kernel Lock. From here, userspace runs on Application
	 * Processors too.
	 *
	 * aarch64 too, since 2026-09-19: the suite that used to score 900-1300
	 * of ~1370 with userspace on the secondaries (a CPU found executing on
	 * another task's kernel stack) now matches the one-CPU run exactly, twice
	 * over, with a process verifiably running on cpu 1. b1nix.no-ap-userspace
	 * keeps the secondaries on kernel workers, should it come back. */
#if defined(__aarch64__)
	if (bootinfo_has_flag("b1nix.no-ap-userspace"))
		console_write("smp: secondaries stay on kernel workers "
		              "(b1nix.no-ap-userspace)\n");
	else
		g_ap_userspace_enabled = 1;
#else
	g_ap_userspace_enabled = 1;
#endif

	/* Variant B: start background reclaim now that the scheduler, page cache and
	 * filesystems are up — kswapd keeps a free-frame headroom so userspace
	 * allocations rarely stall in synchronous reclaim. */
	kswapd_init();
	scheduler_start_reaper();
	vfs_start_writeback();
	/* b1nix.prof-at=<seconds>: print the profile once, by itself, for a guest
	 * that will never read /proc/b1nix-prof. */
	{
		u32 at = bootinfo_get_u32("b1nix.prof-at", 0);

		if (at)
			kthread_create("profdump", prof_dump_thread,
			               (void *)(usize)at);
	}
	fb_console_start_flusher();

	/* b1nix.panic-demo: show the panic screen on purpose, with the machine
	 * fully up (tasks, kallsyms, display) so every part of it has content. */
	panic_screen_demo();

	/* M99/M100 self-tests run here rather than in the block above: they create
	 * kernel threads and park on wait channels, which needs the full
	 * cooperative scheduler (the earlier block runs while the APs are still
	 * confined to the work-stealing-only loop). */
	if (bootinfo_has_flag("b1nix.test=1")) {
		/* M98: MSI-X delivery. Needs the full scheduler (the completion wait
		 * blocks) and a controller that has finished initialising, so it runs
		 * here rather than in the early self-test block with the rest of M98.
		 * Not x86-only any more: aarch64 delivers a message interrupt through
		 * the GICv3 ITS (kernel/arch/aarch64/gicv3_its.c). The test itself
		 * reports "skip" on a board whose controller has no MSI-X, which is
		 * what a GICv2 machine looks like from here. */
#if defined(__aarch64__)
		/* The controller's own half of an MSI, before any device is involved:
		 * see kernel/arch/aarch64/gicv3_its.c. */
		its_selftest();
		bcm2835_mbox_selftest();
		bcm2835_gpio_selftest();
		bcm2835_systimer_selftest();
#endif
		nvme_msix_selftest();
#if defined(__x86_64__)
		iommu_selftest();     /* M100b/M100c: VT-d, domains, groups, IR */
		amdvi_selftest();     /* M100d: AMD-Vi */
		/* Whichever unit came up, put a real device behind it and move data
		 * through its own domain. The check names the unit's milestone. */
		nvme_iommu_selftest();
#elif defined(__aarch64__)
		/* M100e: the aarch64 half of the same claim — the unit comes up, a
		 * translation is installed and read back out of its own tables, and
		 * a real device runs in a domain that only holds what it was granted
		 * (nvme_iommu_selftest, below). */
		smmuv3_selftest();
		nvme_iommu_selftest();
#endif
		/* M14: the fsync/sync durability path — the device cache-flush command
		 * each disk claims, and a write that survives a flush plus a full
		 * block-cache drop. Needs the full scheduler because the flush blocks
		 * on its completion. Not x86-only: the flush is a command each driver
		 * already implements, and the scratch write now picks a disk nothing
		 * has mounted (see blk_durability_selftest). */
		/* Which smoke lane this boot is, if any: some self-tests below are
		 * graded from one lane's log and cost the others time for nothing. */
		char smoke_lane[16] = "";

		if (bootinfo_get_kv("b1nix.smoke", smoke_lane, sizeof(smoke_lane)) <= 0)
			smoke_lane[0] = '\0';
		/* Graded from the blk lane alone; a flush through every other lane's
		 * disk was up to 3.7 s of an aarch64 boot. */
		if (!smoke_lane[0] || strcmp(smoke_lane, "blk") == 0)
			blk_durability_selftest();
		/* The block cache under concurrent readers, writers and evictions. */
		blk_cache_torture_test();
		/* linuxkpi and the DRM core are shim layers over this kernel's own
		 * allocator, scheduler and VMM — there is nothing x86 in an idr, a
		 * workqueue, a dma-fence or the GPU scheduler, and their sources are
		 * built for both arches. They were only inside the guard above
		 * because the IOMMU tests they sat next to are genuinely x86. */
		/* Once per smoke run, not once per lane. These exercise the shim
		 * layers themselves, whatever devices a lane attaches, and their
		 * markers are graded from the combined log; repeating them in every
		 * instance was 0.75 s of each x86_64 boot and 2.6 s of each aarch64
		 * one (TCG). The sys lane runs them, and so does any test boot that
		 * names no lane. The GPU interrupt test depends on the lane's device
		 * and stays everywhere. */
		int shim_selftests = !smoke_lane[0] || strcmp(smoke_lane, "sys") == 0;
		if (shim_selftests) {
			lkpi_selftest();      /* M99: idr, completion, workqueue, sg, dma, fw */
			dma_fence_selftest(); /* M100: dma-fence */
			drm_sched_selftest(); /* M100: GPU scheduler + scatter-gather BOs */
			lkpi_selftest_m101(); /* M101: kref, waitqueue, ww_mutex, rbtree, RCU */
		}
		virtio_gpu_irq_selftest(); /* the scanout's completion interrupt */
		if (shim_selftests) {
			drm_import_selftest(); /* M101: the imported DRM core actually runs */
			drm_kms_selftest();    /* M101: a device on it, rendering to the scanout */
			kheap_selftest();      /* the allocator splits blocks it reuses */
			sysfs_attr_selftest(); /* M101: its /sys and debugfs files, read back */
		}

		/* How much of the boot CPU's stack the whole of kernel_main actually
		 * used, reported last so it covers every probe and self-test above.
		 *
		 * This is the check that was missing. The boot stack used to be
		 * 64 KiB and the boot path needed more than that on the deepest
		 * configuration, but an overflow wrote into ordinary .bss and nothing
		 * faulted, so the only evidence was a networking pointer going bad in
		 * one boot out of five. A used/total pair in the log turns that into
		 * an arithmetic fact anyone can read; the smoke suite fails the run if
		 * the peak passes 75% of the stack, well before the guard page. */
		{
			u64 used = boot_stack_peak_bytes();
			u64 total = boot_stack_size_bytes();
			char buf[96];
			snprintf(buf, sizeof(buf),
			         "BOOT-STACK: peak=%lu total=%lu pct=%lu\n",
			         (unsigned long)used, (unsigned long)total,
			         (unsigned long)(total ? (used * 100) / total : 0));
			console_write(buf);
		}
		/* And the same for the APs, which had the same defect for longer: a
		 * 16 KiB stack against a syscall path carrying a 28,584-byte frame.
		 * They only exist on SMP, which is why the corruption they caused only
		 * ever showed up there. */
		{
			extern u64 ap_stack_peak(u64 *total_out);
			u64 total = 0;
			u64 used = ap_stack_peak(&total);
			char buf[96];

			if (total) {
				snprintf(buf, sizeof(buf),
				         "AP-STACK: peak=%lu total=%lu pct=%lu\n",
				         (unsigned long)used, (unsigned long)total,
				         (unsigned long)((used * 100) / total));
				console_write(buf);
			}
		}
	}

	userspace_init();

	/* M94: Generic init path — honour `init=/path` from kernel cmdline.
	 * Default PID 1 is /sbin/init, which is BusyBox's `init` applet (the
	 * symlink is stamped by tools/packages/stage-busybox.sh) — Alpine's layout.
	 * BusyBox init supervises (reaps orphans, respawns getty, runs the
	 * sysinit/shutdown phases) and /etc/inittab hands the service graph to
	 * OpenRC, which stays the high-level init: `openrc sysinit`, `openrc boot`,
	 * `openrc default`.
	 * `b1nix.single` maps to `init=/bin/sh` (standard single-user mode).
	 * The old test orchestrator `/bin/init` can be selected via `init=/bin/init`. */
	char init_path_buf[128];
	const char *init_path = "/sbin/init";
	if (bootinfo_get_kv("init", init_path_buf, sizeof(init_path_buf)) &&
	    init_path_buf[0] != '\0') {
		init_path = init_path_buf;
	} else if (bootinfo_has_flag("b1nix.single")) {
		init_path = "/bin/sh";
	}

	char init_log[160];
	/* init must be PID 1: real init systems (openrc-init, sysvinit) bail out
	 * with `if (getpid() != 1) return 1;`. The boot task is PID 0 and ids from
	 * 2 up went to the kernel threads started above, so 1 is still free. */
	/* No clock older than the system it runs. A board with no RTC driver (the
	 * Xperia 5) starts at 1970, and OpenRC's first act is to find /etc/init.d
	 * written in the future: "clock skew detected" on every boot, before its
	 * own swclock could run. So the clock is lifted to that directory's mtime
	 * if it is behind -- what systemd does with its build-time epoch and
	 * fake-hwclock with a saved stamp. A real RTC is already past it. */
	{
		struct b1nix_stat st;

		if (vfs_stat("/etc/init.d", &st) == 0 &&
		    wallclock_now_ns() / 1000000000ull < st.st_mtim.tv_sec)
			wallclock_set_ns(st.st_mtim.tv_sec * 1000000000ull);
	}
	scheduler_reserve_init_pid();
	int init_pid = user_spawn(init_path, 0, 0);
	if (init_pid > 0)
		scheduler_set_init_pid((usize)init_pid);
	/* The cmdline is echoed again here, next to the spawn it decided. It is
	 * printed once near the top of the boot too, but that has long scrolled
	 * away by now — and on a board where the only console is a panel, "which
	 * cmdline actually won" is exactly the question this line answers. The
	 * bootloader replaces /chosen/bootargs with the boot image header's copy,
	 * so neither the compiled-in default nor the tree's own property is
	 * necessarily what got through. */
	snprintf(init_log, sizeof(init_log), "init: %s pid=%d\ncmdline: %s\n",
	         init_path, init_pid,
	         bootinfo_cmdline() ? bootinfo_cmdline() : "(none)");
	console_write(init_log);
	snprintf(g_boot_init, sizeof(g_boot_init), "%s pid=%d", init_path, init_pid);

	/*
	 * PID 1 is up: the kernel stops being the printer.
	 *
	 * Linux keeps its messages in a ring and lets userspace read them
	 * (/dev/kmsg, journald, dmesg); the console is for what someone must see
	 * even when nothing else runs. This kernel instead drew every info line
	 * itself, on the console and, when the console lives on a DRM display,
	 * into the same panel a compositor is using -- 1.8 M cycles a line with
	 * interrupts off, for output the guest's own init is already collecting.
	 *
	 * From here the console carries warnings and worse. Everything is still
	 * in the ring, /dev/kmsg still serves it, panics still print, and
	 * `loglevel=` or a test boot (b1nix.test=1, whose whole grading is the
	 * serial log) keeps whatever it asked for.
	 */
	if (init_pid > 0) {
		k_info(NULL, "Step 12: Handing over to init (PID %d)", (int)init_pid);
		b1nix_splash_dismiss();
	}
	/* A measurement asked for on the command line is output someone is
	 * waiting to read, so those flags keep the console as it was. */
	if (init_pid > 0 && !bootinfo_has_flag("b1nix.test=1") &&
	    !bootinfo_get_kv("loglevel", 0, 0) &&
	    !bootinfo_has_flag("b1nix.console-verbose") &&
	    !bootinfo_has_flag("b1nix.drm-fps") &&
	    !bootinfo_has_flag("b1nix.drm-tearwatch") &&
	    !bootinfo_has_flag("b1nix.drm-paintwatch") &&
	    !bootinfo_has_flag("b1nix.drm-crcwatch") &&
	    !bootinfo_has_flag("b1nix.drm-bandwatch") &&
	    !bootinfo_has_flag("b1nix.drm-scanwatch") &&
	    !bootinfo_has_flag("b1nix.drm-eventwatch") &&
	    !bootinfo_has_flag("b1nix.drm-bindwatch") &&
	    !bootinfo_has_flag("b1nix.drm-gsmtrap") &&
	    !bootinfo_has_flag("b1nix.drm-cadence") &&
	    !bootinfo_get_u32("b1nix.drm-framedump", 0) &&
	    !bootinfo_has_flag("b1nix.drm-framedump-key") &&
	    !bootinfo_has_flag("b1nix.sysprof") &&
	    !bootinfo_has_flag("b1nix.trace-sysfs") &&
	    !bootinfo_has_flag("b1nix.trace-open")) {
		console_write("init: the console is userspace's now; the kernel keeps "
		              "warnings (b1nix.console-verbose keeps it all)\n");
		console_loglevel_set(CONSOLE_LOGLEVEL_QUIET);
	}

	/* A PID 1 that never started must say so, loudly, right here.
	 *
	 * Both early failures inside user_spawn return a bare error and print
	 * nothing: the file is missing, or it is not executable by us. The boot
	 * then continues, the machine goes quiet with no userspace on it at all,
	 * and from the outside that is indistinguishable from a userspace program
	 * that hung — which is exactly how this board was read for several rounds.
	 *
	 * The most likely cause is also the one the message can settle on the spot:
	 * when the real root fails to mount, / is still the bootstrap initramfs,
	 * which carries smoke binaries and no init and no shell. So report whether
	 * the usual suspects exist, rather than only that the spawn failed. */
	if (init_pid <= 0) {
		static const char *probe[] = {"/sbin/init", "/bin/sh", "/bin/busybox",
		                              "/lib/libc.so", 0};

		snprintf(init_log, sizeof(init_log),
		         "init: SPAWN FAILED rc=%d — no userspace will run\n", init_pid);
		console_write(init_log);
		console_write("init: present:");
		for (int i = 0; probe[i]; i++) {
			struct vfs_node *n = vfs_find_node(probe[i]);
			int here = n && !IS_ERR(n);

			if (here)
				vfs_node_put(n);
			console_write(" ");
			console_write(probe[i]);
			console_write(here ? "=yes" : "=NO");
		}
		console_write("\n");
		/* Almost always the same story: the real root did not mount, so / is
		 * still the initramfs. Print what ram0 actually holds, next to the
		 * failure it caused. */
		ramdisk_report();
	}

	/* M68 native-Rust proof: the rustc ELF + librustc_driver.so (LLVM folded in) +
	 * the std sysroot (~hundreds of MB) are far too big for the
	 * xxd-embedded initramfs, so — like d8 above — they ship as a
	 * Multiboot2 module (limine.conf `module_path .../rust.img`) exposed as the ram0
	 * ext4 block device. With b1nix.rustrun the kernel mounts it and launches
	 * /bin/rustc. rustc has librustc_driver.so/libLLVM.so as DT_NEEDED (no
	 * PT_INTERP), so just loading the binary exercises the M69 recursive
	 * exec-time dynamic linker across the whole ~325MB .so graph. Running
	 * `rustc --version` then proves the loaded compiler actually executes on
	 * b1nix (it prints its real version string to serial). Gated by a cmdline
	 * flag so it never fires in the ordinary smoke suite. */
	if (bootinfo_has_flag("b1nix.rustrun")) {
		vfs_mkdir("/mnt/rust", 0755);
		int rust_mrc = vfs_mount("ram0", "/mnt/rust", "ext4", 0);
		char rust_buf[96];
		snprintf(rust_buf, sizeof(rust_buf), "rust: mount ram0 -> /mnt/rust: %d\n", rust_mrc);
		console_write(rust_buf);
		if (rust_mrc == 0) {
			const char *rust_argv[] = {"rustc", "--version", 0};
			int rust_pid = user_spawn("/mnt/rust/bin/rustc", 2, rust_argv);
			snprintf(rust_buf, sizeof(rust_buf), "rust: rustc spawn result: %d\n", rust_pid);
			console_write(rust_buf);
			/* A valid pid means user_load_elf64 resolved and relocated the whole
			 * rustc -> librustc_driver.so (LLVM folded) -> libc.so.1 graph
			 * (~250MB) through the M69 exec-time dynamic linker. rustc then prints
			 * its real version banner ("rustc 1.x ...") when it runs — that banner
			 * is the execution proof the smoke runner checks for. */
			if (rust_pid > 0)
				console_write("M68-RUST: ok rustc-load\n");
			else
				k_info(NULL, "M68-RUST: fail rustc-load");
		}
	}

	/* M64 native self-host Clang. The b1nix-native clang-22 (a ~94MB ELF that
	 * statically links LLVM + libstdc++, NEEDED only libc.so.1) ships inside a
	 * self-contained ISO as a Multiboot2 module (ext4) exposed as ram0 —
	 * exactly like rustc/d8 above. With b1nix.clangrun the kernel mounts ram0
	 * -> /mnt/clang and exercises the compiler two ways: `clang --version`
	 * proves the loaded compiler executes on b1nix (it prints its real version
	 * banner to serial — the load proof), and `clang -cc1 -emit-obj hello.c`
	 * proves the frontend+backend+integrated-assembler produce a valid b1nix
	 * object natively (the kernel then checks the emitted hello.o for the ELF
	 * magic — the compile proof). Gated by a cmdline flag so it never fires in
	 * the ordinary smoke suite. */
	if (bootinfo_has_flag("b1nix.clangrun")) {
		vfs_mkdir("/mnt/clang", 0755);
		int clang_mrc = vfs_mount("ram0", "/mnt/clang", "ext4", 0);
		char clang_buf[96];
		snprintf(clang_buf, sizeof(clang_buf), "clang: mount ram0 -> /mnt/clang: %d\n", clang_mrc);
		console_write(clang_buf);
		if (clang_mrc == 0) {
			/* (1) Load + run proof: clang prints its real version banner. A
			 * valid pid means the M69 exec-time loader resolved clang-22 ->
			 * libc.so.1 and relocated the whole image; SYS_WAIT lets it run to
			 * completion so the banner reaches serial before we mark it. */
			const char *ver_argv[] = {"clang", "--version", 0};
			int ver_pid = user_spawn("/mnt/clang/bin/clang", 2, ver_argv);
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang --version spawn: %d\n", ver_pid);
			console_write(clang_buf);
			if (ver_pid > 0) {
				int ver_st = 0;
				syscall_dispatch(SYS_WAIT, (u64)ver_pid, (u64)(usize)&ver_st, 0, 0, 0, 0);
				console_write("M64-NATIVE-CLANG: ok clang-load\n");
			} else {
				k_info(NULL, "M64-NATIVE-CLANG: fail clang-load");
			}

			/* (2) Compile proof: emit an object for the default x86_64-b1nix
			 * target from a header-free TU. Wait for clang to finish, then
			 * verify the ELF magic of the emitted object — only a genuinely
			 * running frontend+backend+assembler can produce it. */
			const char *cc_argv[] = {"clang", "-c", "/mnt/clang/hello.c",
			                         "-o", "/mnt/clang/hello.o", 0};
			int cc_pid = user_spawn("/mnt/clang/bin/clang", 5, cc_argv);
			int cc_st = -1;
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang -c spawn: %d\n", cc_pid);
			console_write(clang_buf);
			if (cc_pid > 0)
				syscall_dispatch(SYS_WAIT, (u64)cc_pid, (u64)(usize)&cc_st, 0, 0, 0, 0);
			unsigned char elfmag[4] = {0};
			int ofd = vfs_open("/mnt/clang/hello.o");
			if (ofd >= 0) {
				vfs_read(ofd, (char *)elfmag, sizeof(elfmag));
				vfs_close(ofd);
			}
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang -c exit=%d obj-magic=%02x%02x%02x%02x\n",
			         cc_st, elfmag[0], elfmag[1], elfmag[2], elfmag[3]);
			console_write(clang_buf);
			if (cc_pid > 0 && elfmag[0] == 0x7f && elfmag[1] == 'E' &&
			    elfmag[2] == 'L' && elfmag[3] == 'F')
				console_write("M64-NATIVE-CLANG: ok compile\n");
			else
				k_info(NULL, "M64-NATIVE-CLANG: fail compile");

			/* Diagnostic: also compile at -O2. The optimized path uses the
			 * greedy allocator and has no "must use fast regalloc" check, so a
			 * valid object here proves the dynamic libLLVM.so codegen+assembler
			 * work end to end (and bounds any -O0 fast-regalloc defect to that
			 * one path — the level llvmpipe never JITs at). */
			const char *cc2_argv[] = {"clang", "-O2", "-c", "/mnt/clang/hello.c",
			                          "-o", "/mnt/clang/hello2.o", 0};
			int cc2_pid = user_spawn("/mnt/clang/bin/clang", 6, cc2_argv);
			int cc2_st = -1;
			if (cc2_pid > 0)
				syscall_dispatch(SYS_WAIT, (u64)cc2_pid, (u64)(usize)&cc2_st, 0, 0, 0, 0);
			unsigned char elfmag2[4] = {0};
			int ofd2 = vfs_open("/mnt/clang/hello2.o");
			if (ofd2 >= 0) {
				vfs_read(ofd2, (char *)elfmag2, sizeof(elfmag2));
				vfs_close(ofd2);
			}
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang -O2 -c exit=%d obj-magic=%02x%02x%02x%02x\n",
			         cc2_st, elfmag2[0], elfmag2[1], elfmag2[2], elfmag2[3]);
			console_write(clang_buf);
			if (cc2_pid > 0 && elfmag2[0] == 0x7f && elfmag2[1] == 'E' &&
			    elfmag2[2] == 'L' && elfmag2[3] == 'F')
				console_write("M64-NATIVE-CLANG: ok compile-O2\n");
			else
				k_info(NULL, "M64-NATIVE-CLANG: fail compile-O2");
		}
	}

	/* M26 native-Clang KERNEL self-host. The self-host module (clang + ld.lld +
	 * kernel source + the flat TU list) ships as the ram0 ext4 Multiboot2 module. With
	 * b1nix.selfhostbuild the kernel mounts it and compiles+links its own kernel
	 * in-guest with its own clang+ld.lld (the same toolchain the host uses), the
	 * real M26 self-host. Gated by a cmdline flag so it never fires in the
	 * ordinary smoke suite. */
	if (bootinfo_has_flag("b1nix.selfhostbuild")) {
		vfs_mkdir("/mnt/build", 0755);
		/* b1nix.selfhostdisk sources the toolchain from a real SATA disk (sda)
		 * instead of the ram0 Multiboot2 module. The module is a ramdisk: its ~217 MB
		 * stay pinned in RAM for the whole build. A disk leaves that 217 MB free
		 * — the toolchain streams off AHCI through the (now read-ahead) block
		 * cache — so the self-host fits in far less RAM. */
		const char *sh_src =
		    bootinfo_has_flag("b1nix.selfhostdisk") ? "sda" : "ram0";
		struct block_device *sh_dev = blk_get(sh_src);
		const char *sh_type = sh_dev ? blk_probe_fstype(sh_dev) : "ext4";
		int sh_mrc = vfs_mount(sh_src, "/mnt/build", sh_type[0] == '-' ? "ext4" : sh_type, 0);
		char sh_buf[80];
		snprintf(sh_buf, sizeof(sh_buf), "selfhost: mount %s -> /mnt/build: %d\n",
		         sh_src, sh_mrc);
		console_write(sh_buf);
		if (sh_mrc == 0) {
			/* M93: self-host build orchestration moved to userspace.
			 * Spawn /bin/selfhost-build which reads srcs.txt, compiles
			 * each TU with clang, and links with ld.lld. */
			const char *sh_argv[] = {"/mnt/build/bin/selfhost-build", 0};
			int sh_pid = user_spawn("/mnt/build/bin/selfhost-build", 1, sh_argv);
			if (sh_pid > 0) {
				int sh_st = 0;
				syscall_dispatch(SYS_WAIT, (u64)sh_pid,
				                 (u64)(usize)&sh_st, 0, 0, 0, 0);
				char sh_res[80];
				snprintf(sh_res, sizeof(sh_res),
				         "selfhost: selfhost-build exit=%d\n", sh_st);
				console_write(sh_res);
			} else {
				console_write("selfhost: fail spawn selfhost-build\n");
			}
		}
	}

	/* BSP idle loop. The BKL is fully retired (M28 #7): kernel entry runs
	 * BKL-free and scheduler_yield no longer hands a lock across the context
	 * switch, so the idle loop just yields and parks when there is no work. */
	while (1) {
		int switched = scheduler_yield();
		if (!switched) {
			extern u64 g_idle_halts;

			g_idle_halts++;
#if defined(__x86_64__)
			__asm__ volatile("sti; hlt" : : : "memory");
#elif defined(__aarch64__)
			__asm__ volatile("msr daifclr, #2; wfi" : : : "memory");
#endif
		}
	}
}
