#include <b1nix/arch.h>
#include <b1nix/fw_cfg.h>
#include <b1nix/io.h>
#include <b1nix/bootinfo.h>
#include <b1nix/console.h>
#include <b1nix/kprintf.h>
#include <b1nix/ktime.h>
#include <b1nix/ftrace.h>
#include <b1nix/gdbstub.h>
#include <b1nix/initramfs.h>
#include <b1nix/mm.h>
#include <b1nix/net.h>
#include <b1nix/netproto.h>
#include <b1nix/module.h>
#include <b1nix/netdev.h>
#include <b1nix/panic.h>
#include <b1nix/sched.h>
#include <b1nix/serial.h>
#include <b1nix/serial_tty.h>
#include <b1nix/user.h>
#include <b1nix/sysfs_attr.h>
#include <b1nix/cgroup.h>
#include <b1nix/vfs.h>
#include <b1nix/syscall.h>
#include <b1nix/blk.h>
#include <b1nix/page_cache.h>
#include <b1nix/tlb.h>
#include <b1nix/ext2.h>
#include <b1nix/ext1.h>
#include <b1nix/fat32.h>
#include <b1nix/exfat.h>
#include <b1nix/ntfs.h>
#include <b1nix/ext3.h>
#include <b1nix/ext4.h>
#include <b1nix/btrfs.h>
#include <b1nix/fuse.h>
#include <b1nix/procfs.h>
#include <b1nix/ahci.h>
#include <b1nix/amdvi.h>
#include <b1nix/iommu.h>
#include <b1nix/nvme.h>
#include <lkpi/dma-mapping.h>
#include <b1nix/filelock.h>
#include <b1nix/errno.h>
#include <b1nix/isofs.h>
#include <b1nix/loop.h>
#include <b1nix/md.h>
#include <b1nix/mtd.h>
#include <b1nix/nbd.h>
#include <b1nix/vt.h>
#include <b1nix/rtc.h>
#include <b1nix/kmsg.h>
#include <b1nix/watchdog.h>
#include <b1nix/i2c.h>
#include <b1nix/vt.h>
#include <b1nix/kmsg.h>
#include <b1nix/watchdog.h>
#include <b1nix/i2c.h>
#include <b1nix/mqueue.h>
#include <b1nix/shm.h>
#include <b1nix/resource_caps.h>
#include <b1nix/sysv_ipc.h>
#include <b1nix/uidgid.h>
#include <b1nix/lapic.h>
#include <b1nix/video.h>
#include <b1nix/acpi.h>
#include <b1nix/ioapic.h>
#include <b1nix/ramdisk.h>
#include <b1nix/sound.h>
#include <b1nix/virtio_gpu.h>
#include <string.h>
#include <stdio.h>

extern void usb_selftest(void);
extern void ps2_kbd_init(void);
extern void ps2_mouse_init(void);
extern int xhci_probe(void);
extern void virtio_gpu_init(void);
#if defined(B1NIX_I915) && B1NIX_I915
/*
 * Generated by each module's own module_init() — see <linux/module.h>.
 *
 * Order is the dependency order, and it is not decorative: drm_dev_init()
 * refuses with "DRM core is not initialized" until drm_core_init() has run, and
 * i915 allocates its device through it. drm_core_bringup() is the core's
 * initcall behind an idempotent guard, because the KMS self-test calls it too.
 */
extern void drm_core_bringup(void);
/*
 * The DRM core's debug mask. Off by default because it is verbose, but it is
 * the only place the imported drivers explain what they decided and why — an
 * OpRegion that is not found, a port that is skipped, a link that fails to
 * train all say so through drm_dbg_kms(). Enable with b1nix.drm-debug on the
 * kernel command line.
 *
 * Bits are drm_debug_category: CORE, DRIVER, KMS.
 */
extern unsigned long __drm_debug;
#include <lkpi/drm_bridge.h>
struct drm_device;
struct drm_device *lkpi_drm_first_device(void);
void lkpi_i915_register_card(struct drm_device *dev);
/*
 * KMS only (DRM_UT_KMS). CORE and DRIVER together produce thousands of lines
 * per probe, and at 115200 baud the driver then does not finish inside a test's
 * timeout — the modeset messages are the ones worth having.
 */
#define B1NIX_DRM_DEBUG_MASK 0x04UL
extern int lkpi_initcall_drm_buddy_module_init(void);
extern int lkpi_initcall_drm_display_helper_module_init(void);
extern int lkpi_initcall_i915_init(void);
static void i915_module_init(void)
{
	/*
	 * The OpRegion first, because the driver reads it during probe and there is
	 * no second chance: the VBT inside is where the board's port wiring and
	 * signal parameters come from, and a driver that starts without it commits
	 * to defaults. QEMU offers one; nothing on this boot path has placed it.
	 * See kernel/dev/fw_cfg.c. The device is the assigned display at 00:02.0.
	 */
	(void)fw_cfg_place_igd_opregion(0, 2, 0);

	drm_core_bringup();
	(void)lkpi_initcall_drm_buddy_module_init();
	(void)lkpi_initcall_drm_display_helper_module_init();
	(void)lkpi_initcall_i915_init();
}
#endif
extern void virtio_gpu_dev_init(void);
extern void virtio_input_init(void);
extern void fb_console_init(void);
extern void ac97_init(void);
extern void ac97_selftest(void);
extern void input_init(void);
extern void input_gfxtest_start(void);
extern void input_m47_inject_start(void);
extern void fb_dev_init(void);
extern void drm_dev_init(void);
extern void drm_card1_init(void);
extern void lkpi_cpuinfo_init(void);
#include <b1nix/dma_fence.h>
#include <b1nix/gpu_scheduler.h>
#include <b1nix/memtype.h>
#include <b1nix/netconsole.h>
#include <b1nix/pci.h>
#include <lkpi/lkpi.h>

extern void bootinfo_init_from_fdt(u64 dtb_address);

/* Case-insensitive compare for a UUID: the cmdline may spell it either way,
 * and blk_probe_uuid always prints lower case. */
static int uuid_equal(const char *a, const char *b) {
	for (usize i = 0;; i++) {
		char ca = a[i], cb = b[i];
		if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');
		if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');
		if (ca != cb) return 0;
		if (!ca) return 1;
	}
}

/* root=UUID=… / root=LABEL=… now ask the block layer what is on the device
 * rather than opening the ext superblock here: one implementation, and it
 * covers FAT and exFAT too (see blk_probe_uuid/blk_probe_label). */
static struct block_device *find_device_by_uuid(const char *expected_uuid) {
	char uuid[40];
	for (usize i = 0; i < blk_count(); i++) {
		struct block_device *dev = blk_at(i);
		if (!dev || dev->block_size != 512 || dev->block_count < 4)
			continue;
		if (blk_probe_uuid(dev, uuid, sizeof(uuid)) == 0 &&
		    uuid_equal(uuid, expected_uuid))
			return dev;
	}
	return 0;
}

/* The live medium is whichever block device actually carries the boot image —
 * decided by mounting it and looking, never by what the device is called. USB
 * storage is an ordinary sd* disk now, so a name prefix could not identify it
 * even in principle. Returns the device and the filesystem that mounted it,
 * leaving it mounted at /mnt/iso; NULL if no device carries the image. */
static struct block_device *find_live_medium(const char **fstype_out) {
	static const char *const fs_types[] = {"iso9660", "exfat"};

	/* Removable media first — a live USB is the common case and trying it
	 * first keeps the boot quick — then everything else, because a live
	 * image on an internal disk or an emulated CD is just as valid. */
	for (int removable_first = 1; removable_first >= 0; removable_first--) {
		for (usize i = 0; i < blk_count(); i++) {
			struct block_device *dev = blk_at(i);

			if (!dev || !dev->name)
				continue;
			if (blk_is_removable(dev) != removable_first)
				continue;
			for (usize f = 0; f < sizeof(fs_types) / sizeof(fs_types[0]); f++) {
				struct vfs_node *image;

				if (vfs_mount(dev->name, "/mnt/iso", fs_types[f], 0) != 0)
					continue;
				image = vfs_find_node("/mnt/iso/boot/rootfs.img");
				if (!IS_ERR(image)) {
					vfs_node_put(image);
					if (fstype_out)
						*fstype_out = fs_types[f];
					return dev;
				}
				vfs_umount("/mnt/iso");
			}
		}
	}
	return 0;
}

/* Has any removable medium been enumerated yet? Bounds how long the live-ISO
 * search waits for a USB stick that is still coming up. */
static struct block_device *blk_first_removable(void) {
	for (usize i = 0; i < blk_count(); i++) {
		struct block_device *dev = blk_at(i);

		if (blk_is_removable(dev))
			return dev;
	}
	return 0;
}

static struct block_device *find_device_by_label(const char *expected_label) {
	char label[64];
	for (usize i = 0; i < blk_count(); i++) {
		struct block_device *dev = blk_at(i);
		if (!dev || dev->block_size != 512 || dev->block_count < 4)
			continue;
		if (blk_probe_label(dev, label, sizeof(label)) == 0 &&
		    strcmp(label, expected_label) == 0)
			return dev;
	}
	return 0;
}

static struct block_device *find_root_device(const char *root_val) {
	if (strncmp(root_val, "UUID=", 5) == 0) {
		return find_device_by_uuid(root_val + 5);
	} else if (strncmp(root_val, "LABEL=", 6) == 0) {
		const char *label_str = root_val + 6;
		return find_device_by_label(label_str);
	} else {
		const char *dev_name = root_val;
		if (strncmp(dev_name, "/dev/", 5) == 0) {
			dev_name += 5;
		}
		return blk_get(dev_name);
	}
}

/* M26 native-Clang kernel self-host: orchestration moved to userspace
 * (/bin/selfhost-build). The kernel just mounts the toolchain ext4 and
 * spawns the userspace builder. See userspace/bin/selfhost_build.c. */

/* Repeats the i915 port dump for as long as the machine runs. See the note at
 * its only caller. */
static unsigned g_port_watch_period;

static void port_watch_thread(void *arg)
{
	extern void lkpi_i915_dump_port_state_pub(void) __attribute__((weak));

	(void)arg;
	for (;;) {
		scheduler_sleep_ticks((u64)g_port_watch_period * 100);
		if (lkpi_i915_dump_port_state_pub)
			lkpi_i915_dump_port_state_pub();
	}
}

/* Names a call into the imported DRM core that has not come back. Its only
 * caller is the DRM debug path below; see lkpi_diag_watch_report(). */
/* Everything the scheduler knows, every half minute. For a run where a
 * userspace program stops making progress and says nothing: the task list with
 * each task's wait channel and kernel callers is usually enough to name what
 * it is waiting for. */
static void task_watch_thread(void *arg)
{
	(void)arg;
	for (;;) {
		/* Ten seconds, counted in ticks the scheduler is actually
		 * running at. Written as a constant this slept for thirty
		 * seconds at 100 Hz and for three at 1 kHz — the interval of a
		 * diagnostic must not change because the timer was reprogrammed. */
		scheduler_sleep_ticks(SCHED_MS_TO_TICKS(10000));
		scheduler_dump_tasks();
	}
}

static void drm_stuck_watch_thread(void *arg)
{
	extern int lkpi_diag_watch_report(u64 min_ms) __attribute__((weak));

	(void)arg;
	for (;;) {
		/* Half a second between looks, and a second of patience before a
		 * call is called slow. The old pair — two seconds and four — could
		 * not see a submission that takes two: EXECBUFFER2 on this GPU
		 * returns in about 2.1 s and was therefore never once reported,
		 * which is why the compositor's stall looked like it had no cause. */
		scheduler_sleep_ticks(SCHED_MS_TO_TICKS(500));
		if (lkpi_diag_watch_report && lkpi_diag_watch_report(1000)) {
			extern void lkpi_shmem_counts(u64 *calls, u64 *ns)
				__attribute__((weak));
			u64 calls = 0, ns = 0;

			/* Printed only alongside a slow call, so the numbers describe
			 * the stall rather than the boot as a whole. */
			if (lkpi_shmem_counts) {
				lkpi_shmem_counts(&calls, &ns);
				console_write("lkpi: shmem folios=");
				console_write_dec(calls);
				console_write(" total_ms=");
				console_write_dec(ns / 1000000ull);
				console_write("\n");
			}
		}
	}
}

void kernel_main(usize arg0, usize arg1)
{
	/* Before anything else that can go deep: the boot stack is still shallow
	 * here, so this is the only point at which the unused part of it can be
	 * painted and its high-water mark made measurable. */
	boot_stack_paint();

	serial_init();
	serial_tty_init();
	console_init();

	/* The command line is parsed before the first line is printed, because it
	 * is what decides whether that line is printed at all: `loglevel=` and
	 * `quiet` cannot filter output that has already gone out. Nothing above
	 * prints, so nothing is lost by doing this first — and a boot that dies in
	 * here still speaks, because the console holds anything printed before this
	 * point and the panic path releases it. */
#ifdef __aarch64__
	bootinfo_init_from_fdt(arg0);
#else
	bootinfo_init_from_multiboot2((u32)arg0, (u32)arg1);
#endif
	console_log_init();

	k_info(NULL, "b1nix kernel starting...");
	k_info(NULL, "boot: multiboot2 magic 0x%08x, info at 0x%08x", (u32)arg0,
	       (u32)arg1);

	if (arg0 != 0x36d76289) {
		k_warn(NULL, "Warning: Multiboot2 magic mismatch");
	}

	k_info(NULL, "Step 1: Bootinfo parsed");
	/* The command line as the kernel actually received it. Every flag in this
	 * file is read from it, and a run that behaves as though a flag were absent
	 * is indistinguishable from a bug in what the flag controls until this is
	 * on the record. */
	console_write("cmdline: ");
	console_write(bootinfo_cmdline() ? bootinfo_cmdline() : "(none)");
	console_write("\n");

	/* Initialize the BSP per-CPU area (sets the GS base) FIRST: current_task is
	 * now a per-CPU accessor (get_percpu()->cur_task), and pmm/kheap diagnostics
	 * read current_task, so GS must be valid before any of that runs. */
	percpu_init();

	pmm_init(bootinfo_get());
	k_info(NULL, "Step 2: PMM initialized");

	/* M77: runtime-tunable global resource caps (TCP slots, pipes, SHMMAX,
	 * coredump). Sized from usable RAM here, after PMM knows how much memory
	 * exists; subsystems read the values back at allocation time. */
	resource_caps_init();

	u64 frame = pmm_alloc_frame();
	console_write("Step 3: PMM probe frame: 0x");
	console_write_hex64(frame);
	console_write("\n");

	vmm_init();
	k_info(NULL, "Step 3.5: VMM initialized");

	kheap_init();
	k_info(NULL, "Step 4: KHeap initialized");

	void *heap_probe = kzalloc(64);
	console_write("Step 5: KHeap probe allocation: 0x");
	console_write_hex64((u64)(usize)heap_probe);
	console_write("\n");


	kheap_use_direct_map();
	k_info(NULL, "Step 7: KHeap switched to direct map");

#ifndef __aarch64__
	if (bootinfo_get()->has_framebuffer) {
		fb_console_init();
		k_info(NULL, "Step 8: FB Console initialized");
	}
#endif

	scheduler_init();
	k_info(NULL, "Step 9: Scheduler initialized");

	uidgid_init();
	arch_init();
	/* Discover CPU + interrupt topology from ACPI (RSDP -> RSDT/XSDT -> MADT)
	 * before LAPIC bring-up: smp_boot_aps prefers the MADT CPU list to the
	 * CPUID guess. Silently no-ops on platforms without ACPI. */
	acpi_init();
	lapic_init();
	/* The TSC is calibrated by lapic_init; hand the monotonic clock over to it
	 * so log timestamps and /proc/uptime gain microsecond resolution. */
	ktime_switch_to_tsc();
	/* Switch IRQ routing from the 8259 PIC to the IOAPIC discovered via
	 * ACPI. No-op (PIC stays in charge) when no IOAPIC was reported. */
	ioapic_init();

	/* Every PCI function, one stamped line each, before any driver claims
	 * one. pci_init() existed and had no caller, so hardware b1nix has no
	 * driver for was invisible in a boot log — the first thing anyone asks
	 * for when a machine does not work. */
	pci_init();
	/* Publish the bus topology while the enumeration is fresh. The registry
	 * holds it until /sys is mounted, so this does not depend on mount order:
	 * a device with no node in /sys/devices has no parent for udev to match a
	 * rule against, and libdrm cannot answer what bus a card sits on. */
	pci_sysfs_publish_all();

	/* M28-A: switch the BSP scheduler tick from PIT IRQ0 (vector 32) to the
	 * per-CPU LAPIC timer (vector 64) at 100 Hz. APs arm the same timer when
	 * they enter the cooperative phase in ap_main, so every core now ticks
	 * itself instead of relying on the BSP-only PIT route. */
	/* One millisecond, not ten.
	 *
	 * The tick is the finest deadline the kernel can honour: a sleep, a
	 * timeout, a poll interval can be no shorter and no more precise. At
	 * 100 Hz the smallest of them was ten milliseconds, so a usleep(500) — or
	 * any of the countless short waits a threaded program makes — cost twenty
	 * times what it asked, and a five-hundred-iteration handoff took seven and
	 * a half seconds instead of half a second. Linux ships 250 or 1000 Hz for
	 * the same reason.
	 *
	 * The cost is the interrupt itself, ten times as often. It is a timer
	 * interrupt on a calibrated LAPIC — a few hundred cycles — against
	 * millisecond-scale waits it makes honest, and the rate is programmed
	 * here and read back through sched_tick_hz() by everything that converts
	 * between time and ticks, so nothing else has to be told. */
	if (lapic_timer_start_periodic_ms(1)) {
		k_info("timer", "LAPIC periodic timer armed at 1 kHz; masking PIT IRQ0");
		ioapic_mask_irq(0);
	} else {
		k_warn("timer", "LAPIC calibration unavailable, keeping PIT IRQ0 active");
	}
	blk_cache_init();
	/* Before initramfs and the filesystems, not after: the page cache's hash
	 * and bucket locks are allocated here now rather than being static arrays,
	 * so anything that reads a file has to run after this point. It needs only
	 * the PMM and the heap, both of which are already up. */
	page_cache_init();

	initramfs_init();
	fuse_init();
	k_info(NULL, "Step 10: Initramfs & FUSE initialized");

#ifndef __aarch64__
	/* M100a: reserve the DMA bounce pool here — early, while nothing has
	 * fragmented the free lists. A bounce block must be physically contiguous,
	 * and taking it at map time would make a mapping's success depend on what
	 * every other allocation did. Needs kheap (for the frame map) and nothing
	 * else, and must precede every driver that could map for DMA. */
	dma_bounce_pool_init();

	/* M100b: bring up DMA remapping before any driver programs a device. Every
	 * function starts in pass-through, so this changes nothing for a driver
	 * that has not asked for translation. */
	iommu_init();
	amdvi_init();

	vfs_init();
	ext2_init();
	ext1_init();
	ext3_init();
	fat32_init();
	ext4_init();
	ahci_init();
	nvme_init();
	exfat_init();
	tmpfs_init();
	cgroup_init();   /* cgroup v2 — systemd mounts it before anything else */
	procfs_init();
	sysfs_init();
	filelock_init();
	mqueue_init();
	shm_init();
	sysv_ipc_init(); /* SysV semaphores + message queues */
	swap_init();
	net_init();
	netconsole_init(); /* M98: klog over UDP, b1nix.netconsole=<ip>:<port> */
	ps2_kbd_init();
	ps2_mouse_init();
	input_init(); /* M47: /dev/input/event* (PS/2 kbd + mouse event streams) */
	if (bootinfo_has_flag("b1nix.gfxtest=1"))
		input_gfxtest_start(); /* diagnostic: headless window-drag injector */
	if (bootinfo_has_flag("b1nix.test=1"))
		input_m47_inject_start(); /* M47 smoke: mouse event burst for readers */
	xhci_probe(); /* M37: USB xHCI controller + HID boot keyboard (real-HW input) */
	ac97_init();  /* M79: Intel 82801AA AC'97 controller (/dev/dsp1) */
	/* M102a: the boot CPU's family/model and cache geometry, read before any
	 * driver probes — a quirk keyed on model must not match a zeroed struct,
	 * and the cache line size is a divisor in imported flush loops. This used
	 * to run after the GPU drivers and the flush loops spun on a zero. */
	lkpi_cpuinfo_init();
	video_init();
	virtio_gpu_init();
#if defined(B1NIX_I915) && B1NIX_I915
	/*
	 * M102a: Intel i915. The driver's module init registers its PCI driver,
	 * and pci_register_driver() is what walks the bus and probes — see the
	 * note there. Nothing happens on a machine with no Intel GPU: the id
	 * table matches nothing and registration reports success.
	 *
	 * After virtio_gpu_init() on purpose. On a machine with both, the one
	 * that came up first keeps card0, and virtio-gpu is the one M101 is
	 * proved against.
	 */
	if (bootinfo_has_flag("b1nix.drm-debug")) {
		__drm_debug = B1NIX_DRM_DEBUG_MASK;
		if (kthread_create("drm-stuck-watch", drm_stuck_watch_thread, 0) < 0)
			k_err("drm-stuck-watch", "thread refused");
	}
	/* The atomic and state categories as well, when asked. KMS alone shows what
	 * a modeset was computed to be; these show what the commit then did with
	 * it, which is the difference between "the driver planned to enable a pipe"
	 * and "the driver enabled it". */
	if (bootinfo_has_flag("b1nix.drm-debug-atomic"))
		__drm_debug |= 0x04UL | 0x10UL | 0x40UL;
	i915_module_init();
	/*
	 * Publish the driver's card to b1nix's DRM bridge, so userspace can open
	 * and mmap its objects. Harmless when i915 did not bind: the lookup finds
	 * no device and registers nothing.
	 */
	{
		struct drm_device *card = lkpi_drm_first_device();

		if (card)
			lkpi_i915_register_card(card);
		/* And, when asked, whether the GT behind that card will run
		 * anything: engines, address space, and one empty request per
		 * engine taken to retirement. Costs nothing when the flag is
		 * absent, and nothing at all when i915 did not bind. */
		{
			extern void lkpi_i915_gt_probe(struct drm_device *dev)
				__attribute__((weak));

			if (card && lkpi_i915_gt_probe)
				lkpi_i915_gt_probe(card);
		}
	}
	/*
	 * Stop here when the boot exists only to exercise the display.
	 *
	 * Everything past this point — filesystems, init, the test suite — takes
	 * minutes and touches nothing the display path uses. Bringing a GPU up is
	 * an edit-run loop, and a loop whose slowest step is unrelated to what is
	 * being changed stops being one. This ends the boot the moment the picture
	 * has been produced, so the answer arrives while the question is still in
	 * hand.
	 *
	 * The same ports the reboot syscall writes, for the same reason: QEMU
	 * versions disagree about which one shuts the machine down, so all three
	 * are tried before falling back to halting.
	 */
	/* Defined by the DRM mirror when the imported stack is built in. */
	extern void lkpi_i915_dump_port_state_pub(void) __attribute__((weak));

	/*
	 * Watch the port while userspace runs.
	 *
	 * The display probes above all run before init, which answers what the
	 * kernel's own client did and nothing about what a compositor does later.
	 * b1nix.port-watch=<seconds> repeats the port dump from a thread, so a
	 * modeset issued from userspace — or the absence of one — is visible in the
	 * same log as the compositor's own messages.
	 */
	{
		char pw[8];

		if (bootinfo_get_kv("b1nix.port-watch", pw, sizeof(pw)) &&
		    !lkpi_i915_dump_port_state_pub)
			k_info("port-watch", "no i915 dump in this build");
		if (lkpi_i915_dump_port_state_pub &&
		    bootinfo_get_kv("b1nix.port-watch", pw, sizeof(pw))) {
			unsigned n = 0;

			for (const char *p = pw; *p >= '0' && *p <= '9'; p++)
				n = n * 10u + (unsigned)(*p - '0');
			g_port_watch_period = n ? n : 10;
			console_write("port-watch: every ");
			console_write_dec((u64)g_port_watch_period);
			console_write("s\n");
			if (kthread_create("port-watch", port_watch_thread, 0) < 0)
				k_err("port-watch", "thread refused");
		}
	}

	if (bootinfo_has_flag("b1nix.gfx-only")) {
		/*
		 * The boot exists only to bring the display up: stop before init.
		 *
		 * It used to hold the frame on the wire for a while first, because the
		 * only witness to a modeset was a person watching the screen and the
		 * picture vanished at power-off. It is not the witness any more — the
		 * compositor's own run photographs the panel and reads the registers
		 * back — so the hold, and the flags that tuned it, are gone.
		 */
		k_info(NULL, "B1NIX-GFX: done");
		outw(0x604, 0x2000);
		outw(0xB004, 0x2000);
		outw(0x4004, 0x3400);
		arch_halt();
	}
#endif
	virtio_input_init(); /* absolute pointer (virtio-tablet) — grab-free mouse */
	fb_dev_init(); /* M47: /dev/fb0 mmap-able framebuffer (needs fb_console) */
	nbd_init();    /* /dev/nbd0.. present and empty until a client attaches */
	md_init();     /* /dev/md0.. present and empty until raidautorun fills one */
	mtd_init();    /* CFI NOR flash, when b1nix.mtd asks for the probe */
	drm_dev_init(); /* M50: minimal DRM/KMS dumb-buffer device over virtio-gpu */
	/* M101t: the imported core comes up here rather than in the test block —
	 * /dev/dri/card1 is a device userspace opens, not a self-test. The order
	 * matters: the node is only registered once a device exists behind it. */
	drm_kms_device_init();
	drm_card1_init();
	virtio_gpu_dev_init(); /* M53: /dev/virtio-gpu userspace VirGL 3D transport */
	ramdisk_init();
	loop_init();            /* loop block devices + /dev/loop-control */
	vt_init();              /* M107 virtual terminals + console font/keymap */
	kmsg_init();            /* M107 /dev/kmsg record ring */
	rtc_dev_init();         /* M107 /dev/rtc0 */
	watchdog_init();        /* M107 /dev/watchdog */
	i2c_init();             /* M107 SMBus host controller, if one exists */
	blk_create_dev_nodes(); /* /dev/<blkdev> nodes for blkid/fdisk/loopN */
	if (bootinfo_has_flag("b1nix.diskbench")) {
		const char *db_argv[] = {"diskbench", 0};
		user_spawn("/bin/diskbench", 1, db_argv);
	}
#endif

	/* M92 musl smoke test: must run BEFORE rootfs mount because the binary
	 * lives in the initramfs which gets hidden when ram0 ext4 is mounted at /.
	 * userspace_init() just registers builtins — safe to call early. */
	if (bootinfo_has_flag("b1nix.muslrun")) {
		userspace_init();
		char musl_buf[64];
		/* Run raw diagnostic first, then hello, then full smoke test. */
		const char *raw_argv[] = {"m92-musl-raw-diag", 0};
		int raw_pid = user_spawn("/bin/m92-musl-raw-diag", 1, raw_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-raw-diag: %d\n", raw_pid);
		console_write(musl_buf);
		if (raw_pid > 0) {
			int musl_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)raw_pid, (u64)(usize)&musl_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-raw-diag exit=%d\n", musl_st);
			console_write(musl_buf);
		}
		const char *hello_argv[] = {"m92-musl-hello", 0};
		int hello_pid = user_spawn("/bin/m92-musl-hello", 1, hello_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-hello: %d\n", hello_pid);
		console_write(musl_buf);
		if (hello_pid > 0) {
			int musl_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)hello_pid, (u64)(usize)&musl_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-hello exit=%d\n", musl_st);
			console_write(musl_buf);
		}
		const char *step2_argv[] = {"m92-musl-step2", 0};
		int step2_pid = user_spawn("/bin/m92-musl-step2", 1, step2_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-step2: %d\n", step2_pid);
		console_write(musl_buf);
		if (step2_pid > 0) {
			int musl_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)step2_pid, (u64)(usize)&musl_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-step2 exit=%d\n", musl_st);
			console_write(musl_buf);
		}
		/* M92 dynamic musl test — PIE/ET_DYN linked against ld-musl-x86_64.so.1 */
		const char *musl_dyn_argv[] = {"m92-musl-dyn-smoke", 0};
		int musl_dyn_pid = user_spawn("/bin/m92-musl-dyn-smoke", 1, musl_dyn_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-dyn-smoke: %d\n", musl_dyn_pid);
		console_write(musl_buf);
		if (musl_dyn_pid > 0) {
			int musl_dyn_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)musl_dyn_pid, (u64)(usize)&musl_dyn_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-dyn-smoke exit=%d\n", musl_dyn_st);
			console_write(musl_buf);
		}
		/* M92-LDSO (musl-port.md): PT_INTERP =
		 * /lib/ld-musl-x86_64.so.1. The kernel loads only the interpreter's own
		 * segments and jumps into it; musl's real ld.so links this binary
		 * itself — no in-kernel eager linker involved. */
		const char *musl_ldso_argv[] = {"m92-musl-ldso-smoke", 0};
		int musl_ldso_pid = user_spawn("/bin/m92-musl-ldso-smoke", 1, musl_ldso_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn m92-musl-ldso-smoke: %d\n", musl_ldso_pid);
		console_write(musl_buf);
		if (musl_ldso_pid > 0) {
			int musl_ldso_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)musl_ldso_pid, (u64)(usize)&musl_ldso_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: m92-musl-ldso-smoke exit=%d\n", musl_ldso_st);
			console_write(musl_buf);
		}
		/* M92-POSIX: musl POSIX smoke test — compiled with LINK=musl against
		 * musl's libc.so via /lib/ld-musl-x86_64.so.1 real interpreter. */
		const char *musl_posix_argv[] = {"musl-posix-smoke", 0};
		int musl_posix_pid = user_spawn("/bin/musl-posix-smoke", 1, musl_posix_argv);
		snprintf(musl_buf, sizeof(musl_buf), "musl: spawn musl-posix-smoke: %d\n", musl_posix_pid);
		console_write(musl_buf);
		if (musl_posix_pid > 0) {
			int musl_posix_st = 0;
			syscall_dispatch(SYS_WAIT, (u64)musl_posix_pid, (u64)(usize)&musl_posix_st, 0, 0, 0, 0);
			snprintf(musl_buf, sizeof(musl_buf), "musl: musl-posix-smoke exit=%d\n", musl_posix_st);
			console_write(musl_buf);
		}
	}

#ifndef __aarch64__
	/* Prefer a real ext4 root over the bootstrap initramfs.  Native runs use
	 * vda; Live CD boots use the multiboot ramdisk block device ram0.
	 * In test mode the smoke suite owns the drives, so keep initramfs as /. */
	{
		int rc = -1;
		char root_val[64];
		if (bootinfo_get_kv("root", root_val, sizeof(root_val))) {
			if (strcmp(root_val, "initramfs") == 0) {
				/* Keep the RAM filesystem as /, the way Linux does before an
				 * initramfs hands over with switch_root. The boot then has a
				 * real root to move onto / itself, rather than one the kernel
				 * already mounted there. */
				console_write("rootfs: staying on the initramfs (root=initramfs)\n");
				rc = 0;
				vfs_repopulate_after_root_mount();
			} else if (strcmp(root_val, "liveiso") == 0) {
				k_info("rootfs", "liveiso mount requested, searching for the boot medium...");
				const char *iso_fstype = 0;
				char mounted_iso_name[64];
				mounted_iso_name[0] = '\0';
				/* USB enumeration is asynchronous, so the medium may not be
				 * registered yet. Retry while no removable device has shown up
				 * at all; once one has, one search over every device settles
				 * it — waiting longer would not change the answer. */
				struct block_device *iso_dev = 0;
				for (int retries = 0; retries < 50; retries++) {
					iso_dev = find_live_medium(&iso_fstype);
					if (iso_dev)
						break;
					if (blk_first_removable())
						break;
					scheduler_sleep_ticks(SCHED_MS_TO_TICKS(100));
				}

				int is_exfat = 0;
				if (iso_dev) {
					rc = 0;
					is_exfat = strcmp(iso_fstype, "exfat") == 0;
					snprintf(mounted_iso_name, sizeof(mounted_iso_name), "%s", iso_dev->name);
					console_write(is_exfat ? "exfat: mounted " : "isofs: mounted ");
					console_write(iso_dev->name);
					console_write(" at /mnt/iso\n");
				}

				if (rc == 0) {
					struct block_device *loop_dev = loop_register_file("/mnt/iso/boot/rootfs.img");
					if (loop_dev && !IS_ERR(loop_dev)) {
						char loop_buf[96];
						snprintf(loop_buf, sizeof(loop_buf), "%s: %s backing /boot/rootfs.img\n",
							 is_exfat ? "livefile" : "loop", loop_dev->name);
						console_write(loop_buf);
						/* If we are running in test/smoke mode, we mount at /mnt/root
						 * to keep the bootstrap initramfs as active root.
						 * Otherwise (on real hardware or normal boots), we mount
						 * loop0 as the primary rootfs at /. */
						rc = vfs_mount(loop_dev->name, "/", "ext4", 0);
						if (rc == 0) {
							snprintf(loop_buf, sizeof(loop_buf), "rootfs: %s mounted at / as ext4\n", loop_dev->name);
							console_write(loop_buf);
							vfs_repopulate_after_root_mount();
								if (mounted_iso_name[0] != '\0') {
									int remount_rc = vfs_mount(mounted_iso_name, "/mnt/iso", is_exfat ? "exfat" : "iso9660", 0);
									if (remount_rc == 0) {
										if (is_exfat) {
											console_write("exfat: remounted at /mnt/iso after root switch\n");
										} else {
											k_info("isofs", "remounted at /mnt/iso after root switch");
										}
									} else {
										char err_buf[80];
										snprintf(err_buf, sizeof(err_buf), "%s: remount after root switch failed: %d\n", is_exfat ? "exfat" : "isofs", remount_rc);
										console_write(err_buf);
									}
								}
							if (is_exfat) {
								console_write("M37-LIVEFILE: ok exfat-loop-root\n");
							} else {
								k_info(NULL, "M37-LIVEISO: ok isofs-loop-root");
							}
						}
					} else {
						rc = -1;
					}
				}

				if (rc != 0) {
					k_err("rootfs", "liveiso mount failed, falling back to ram0...");
					rc = vfs_mount("ram0", "/", "ext4", 0);
					if (rc == 0) {
						k_warn("rootfs", "ram0 mounted at / (Live CD fallback)");
						vfs_repopulate_after_root_mount();
					} else {
						char mount_err_buf[64];
						snprintf(mount_err_buf, sizeof(mount_err_buf), "rootfs: fallback mount failed: %d\n", rc);
						console_write(mount_err_buf);
						vfs_repopulate_after_root_mount();
					}
				}
			} else {
				struct block_device *root_dev = find_root_device(root_val);
				if (!root_dev) {
					console_write("rootfs: waiting for root device ");
					console_write(root_val);
					console_write("...\n");
					int retries = 0;
					while (retries < 50) {
						scheduler_sleep_ticks(SCHED_MS_TO_TICKS(100));
						root_dev = find_root_device(root_val);
						if (root_dev) {
							break;
						}
						retries++;
					}
				}
				if (root_dev) {
					const char *fs_types[] = {"ext4", "ext3", "ext2"};
					for (int i = 0; i < 3; i++) {
						rc = vfs_mount(root_dev->name, "/", fs_types[i], 0);
						if (rc == 0) {
							char mounted_buf[96];
							snprintf(mounted_buf, sizeof(mounted_buf), "rootfs: %s mounted at / as %s\n", root_dev->name, fs_types[i]);
							console_write(mounted_buf);
							vfs_repopulate_after_root_mount();
							break;
						}
					}
				}
				if (rc != 0) {
					char mount_err_buf[96];
					snprintf(mount_err_buf, sizeof(mount_err_buf), "rootfs: staying on initramfs, failed to mount root: %s\n", root_val);
					console_write(mount_err_buf);
					vfs_repopulate_after_root_mount();
				}
			}
		} else {
			/*
			 * No root= on the command line: choose by what the filesystem says
			 * it is, not by where it happens to be plugged in.
			 *
			 * Taking the first virtio disk unconditionally meant any disk attached for
			 * any other purpose became the root — a package cache handed to the
			 * guest for speed was mounted at / and the real filesystem never
			 * appeared. The label comes first, then the image the boot loader
			 * handed us, and only then a bare disk.
			 */
			rc = -1;
			{
				struct block_device *labelled = find_device_by_label("b1nix-root");

				if (labelled) {
					const char *fs_types[] = {"ext4", "ext3", "ext2"};

					for (int i = 0; i < 3 && rc != 0; i++)
						rc = vfs_mount(labelled->name, "/", fs_types[i], 0);
					if (rc == 0) {
						char buf[96];

						snprintf(buf, sizeof(buf),
						         "rootfs: %s (label b1nix-root) mounted at /\n",
						         labelled->name);
						console_write(buf);
						vfs_repopulate_after_root_mount();
					}
				}
			}
			if (rc != 0) {
				rc = vfs_mount("ram0", "/", "ext4", 0);
				if (rc == 0) {
					console_write("rootfs: ram0 mounted at / as ext4\n");
					vfs_repopulate_after_root_mount();
				}
			}
			if (rc == 0) {
				/* mounted above */
			} else if ((rc = vfs_mount("vda", "/", "ext4", 0)) == 0) {
				k_info("rootfs", "vda mounted at /");
				vfs_repopulate_after_root_mount();
			} else {
				/* Try finding a block device by default label 'b1nix-root' (e.g. USB flash drive) */
				struct block_device *root_dev = find_device_by_label("b1nix-root");
				if (root_dev) {
					const char *fs_types[] = {"ext4", "ext3", "ext2"};
					for (int i = 0; i < 3; i++) {
						rc = vfs_mount(root_dev->name, "/", fs_types[i], 0);
						if (rc == 0) {
							char mounted_buf[96];
							snprintf(mounted_buf, sizeof(mounted_buf), "rootfs: %s (label b1nix-root) mounted at / as %s\n", root_dev->name, fs_types[i]);
							console_write(mounted_buf);
							vfs_repopulate_after_root_mount();
							break;
						}
					}
				}
				if (rc != 0) {
					rc = vfs_mount("ram0", "/", "ext4", 0);
					if (rc == 0) {
						console_write("rootfs: ram0 mounted at / as ext4\n");
						vfs_repopulate_after_root_mount();
					} else {
						char mount_err_buf[64];
						snprintf(mount_err_buf, sizeof(mount_err_buf), "rootfs: staying on initramfs, mount failed: %d\n", rc);
						console_write(mount_err_buf);
						vfs_repopulate_after_root_mount();
					}
				}
			}
		}
	}

	/* M34: mount synthetic filesystems after the final root is selected, so
	 * they sit on top of /proc and /sys in the real root image. */
	vfs_mkdir("/proc", 0555);
	if (vfs_mount("proc", "/proc", "procfs", 0) == 0)
		console_write("procfs: mounted at /proc\n");
	vfs_mkdir("/sys", 0555);
	if (vfs_mount("sys", "/sys", "sysfs", 0) == 0)
		k_info("sysfs", "mounted at /sys");
	/* BusyBox sysctl chdirs to /proc/sys; point at /sys where the actual
	 * files live (kernel.osrelease → /sys/kernel/osrelease). */
	vfs_symlink("/sys", "/proc/sys");
#endif
	if (bootinfo_has_flag("b1nix.task-watch") &&
	    kthread_create("task-watch", task_watch_thread, 0) < 0)
		k_err("task-watch", "thread refused");
	/* M95: load the optional filesystems, the HDA sound driver and the IPv6
	 * protocol modules from /lib/modules. Each is optional — the kernel boots
	 * and passes its tests with any of them absent.
	 *
	 * After the root filesystem is mounted, not before. They live in
	 * /lib/modules, and while the root arrived as a boot module already in
	 * memory that was available from the first instant; served off a disk it
	 * is not, and every one of them failed to load with ENOENT. Nothing
	 * earlier in the boot needs them — they are optional filesystems, a sound
	 * driver and a network protocol — so the load belongs on this side of the
	 * mount. */
	module_init_builtin_deps();

	k_info(NULL, "Step 11: Drivers initialized");

	/* Bring up Application Processors */
	smp_boot_aps();

	/* Each AP turns CR4.SMEP on for itself and stays quiet about it (its line
	 * would land inside the one smp_boot_aps is writing). Report the tally here
	 * instead, so the bit is accounted for on every core and not just the one
	 * that printed at arch_init. */
	{
		extern int arch_smep_cpu_count(void);
		int smep_cpus = arch_smep_cpu_count();

		console_write("smep: active on ");
		console_write_dec((u32)smep_cpus);
		console_write(" of ");
		console_write_dec((u32)get_online_cpu_count());
		console_write(" CPUs\n");
	}

	/* Do the cores agree about what a page-table entry means?
	 *
	 * They did not: the AP trampoline set CR4.PGE and boot.S did not, so bit 8
	 * of a leaf entry was a software flag on the boot CPU and the GLOBAL bit on
	 * every other one. Nothing was in a position to notice, because no check
	 * had ever compared one core's control registers against another's. This
	 * is that check, and it runs on every boot rather than in test mode: a
	 * divergence here silently changes the memory model.
	 */
	{
		extern int x86_check_cpu_state_uniform(void);

		(void)x86_check_cpu_state_uniform();
	}

	/* M28 T4: enable cross-CPU TLB shootdown. With BKL out of syscall_entry.S
	 * (T4), two CPUs can simultaneously execute vmm_unmap_page on different
	 * pml4s; without shootdown, the stale TLB entry on another CPU lets a
	 * write hit the freed-and-reused physical frame. Safe to enable here
	 * because all APs have come up and have functional LAPICs to ACK IPIs. */
	tlb_shootdown_set_enabled(1);

	/* M101: reserve the lkpi vmap window's page-table path. Must happen before
	 * any process is created, so every address space inherits the entry. */
	lkpi_page_init();

	/* M101: start RCU's deferred-callback thread. After the APs are up, since
	 * it creates a worker thread, and before any driver can call call_rcu. */
	rcu_init();

	/* In-kernel SMP self-tests. These run BEFORE g_ap_userspace_enabled: they
	 * need the APs still parked in the work-stealing-only loop (that loop is
	 * the only path that knows how to execute a stealable worker). The init.c
	 * rewrite dropped these three calls, which silently removed the
	 * M24B-SMP/M28-BENCH markers — the SMP instance then had no done-pattern
	 * to match and ran the whole suite until the host stall watchdog shot it.
	 * All three are no-ops outside b1nix.test=1 / on single-CPU systems. */
	smp_selftest_run();
	m28_heapbench_run();
	m28_ctxbench_run();
	/* M101: the RCU grace-period proof belongs here for the same reason. It
	 * needs a reader running on another CPU at the same moment as the writer,
	 * and a stealable worker picked up by a parked AP is the only placement
	 * this kernel guarantees. Later, once the APs run the ordinary scheduler,
	 * the reader lands wherever it lands — in practice back on the BSP, where
	 * it cannot overlap the writer at all. */
	lkpi_rcu_smp_selftest();

	/* M37 device self-tests. Their only caller used to be the in-kernel test
	 * driver in kernel/user/programs.c, deleted with the ring-3 migration —
	 * which silently dropped the whole M37-E1000 marker set and the USB
	 * HID-translate check (the xHCI markers that do appear come from the
	 * driver's own probe, not from this test). Both are no-ops outside
	 * b1nix.test=1 / without the hardware. */
	if (bootinfo_has_flag("b1nix.test=1")) {
		e1000_selftest();
		usb_selftest();
		/* M38/M79 audio device self-tests. Dropped with the ring-3
		 * migration's kernel/user/programs.c test driver, which silenced
		 * the whole M38-SOUND marker set; revived here. Both are no-ops
		 * outside b1nix.test=1 / without the device.  Re-register the
		 * /dev/dsp* nodes here too: the nodes created at early boot land
		 * on the initramfs root which becomes unreachable after the ext4
		 * root is mounted, so a second vfs_add_node here (on the live
		 * root) is what makes /dev/dsp /dev/dsp1 visible to userspace. */
		sound_module_dev_init();
		ac97_dev_init();
		sound_module_selftest();
		ac97_selftest();
		/* ioprio(2): the block layer's admission policy — better priority
		 * first, and a starving idle-class request ages past a stream of
		 * best-effort ones. Drives the real chooser with synthetic waiters. */
		{
			extern int blk_io_gate_selftest(void);
			int io_rc = blk_io_gate_selftest();
			if (io_rc == 0) {
				k_info(NULL, "M40-IOPRIO: ok elevator-order");
			} else {
				console_write("M40-IOPRIO: FAIL elevator-order check=");
				console_write_dec((u64)io_rc);
				console_write("\n");
			}
		}
		m36_gdb_selftest();
		m36_ftrace_selftest();
		/* M98 driver infrastructure: PAT/write-combining, modern PCI
		 * (BAR sizing, capability walk, bus master, MSI/MSI-X, Intel
		 * stolen memory) and the netconsole UDP log path. */
		memtype_selftest();
		pci_selftest();
		netconsole_selftest();
		/* M32 IPv6 self-tests: loopback (::1) ICMPv6 + MLD, and real-link
		 * SLAAC + ping over QEMU usernet.  Both were in kernel/user/
		 * programs.c before the ring-3 migration; with that file gone
		 * they run here alongside the other hardware self-tests. */
		/* M96: run through the protocol registry — the IPv6 self-tests
		 * live in ipv6.ko and are absent when it is not loaded. */
		net_proto_selftest();

		/* M84: IPv4 FIB (longest-prefix-match, host routes, metric
		 * tie-break) and TCP robustness (option parsing, window
		 * scaling, out-of-order reassembly). */
		/* Boot-log format: timestamps, the severity filter and the
		 * agreement between the console and the dmesg ring. */
		log_format_selftest();

		route_smoke();
		tcp_robustness_smoke();
		dhcpv6_smoke();

		/* M94: init-path parsing self-test. Verify bootinfo_get_kv
		 * correctly extracts the `init=` parameter (or falls back to
		 * /sbin/init). */
		{
			char m94_path[128];
			int m94_got = bootinfo_get_kv("init", m94_path,
			                              sizeof(m94_path));
			if (m94_got && m94_path[0] != '\0') {
				console_write("M94-INIT: ok init=");
				console_write(m94_path);
				console_write("\n");
			} else {
				k_info(NULL, "M94-INIT: ok default /sbin/init");
			}
			/* Verify flag detection (flags are absent in normal test boot). */
			int m94_single = bootinfo_has_flag("b1nix.single");
			if (m94_single) {
				k_info(NULL, "M94-INIT: ok single-flag");
			} else {
				k_info(NULL, "M94-INIT: ok no-override-flags");
			}
		}
	}

	/* The work-stealing self-test is done; let APs leave the work-stealing-only
	 * loop and run the full cooperative scheduler (ordinary userspace processes)
	 * under the Big Kernel Lock. From here, userspace runs on Application
	 * Processors too. */
	g_ap_userspace_enabled = 1;

	/* Variant B: start background reclaim now that the scheduler, page cache and
	 * filesystems are up — kswapd keeps a free-frame headroom so userspace
	 * allocations rarely stall in synchronous reclaim. */
	kswapd_init();

	/* M99/M100 self-tests run here rather than in the block above: they create
	 * kernel threads and park on wait channels, which needs the full
	 * cooperative scheduler (the earlier block runs while the APs are still
	 * confined to the work-stealing-only loop). */
	if (bootinfo_has_flag("b1nix.test=1")) {
		/* M98: MSI-X delivery. Needs the full scheduler (the completion wait
		 * blocks) and a controller that has finished initialising, so it runs
		 * here rather than in the early self-test block with the rest of M98. */
		nvme_msix_selftest();
		/* M14: the fsync/sync durability path — the device cache-flush
		 * command each disk claims, and a write that survives a flush plus
		 * a full block-cache drop. Needs the full scheduler because the
		 * flush command blocks on its completion. */
		blk_durability_selftest();
		iommu_selftest();     /* M100b/M100c: VT-d, domains, groups, IR */
		amdvi_selftest();     /* M100d: AMD-Vi */
		/* Whichever unit came up, put a real device behind it and move data
		 * through its own domain. The check names the unit's milestone. */
		nvme_iommu_selftest();
		lkpi_selftest();      /* M99: idr, completion, workqueue, sg, dma, fw */
		lkpi_selftest_m101(); /* M101: kref, waitqueue, ww_mutex, rbtree, RCU */
		dma_fence_selftest(); /* M100: dma-fence */
		drm_sched_selftest(); /* M100: GPU scheduler + scatter-gather BOs */
		virtio_gpu_irq_selftest(); /* the scanout's completion interrupt */
		drm_import_selftest(); /* M101: the imported DRM core actually runs */
		drm_kms_selftest();    /* M101: a device on it, rendering to the scanout */
		kheap_selftest();      /* the allocator splits blocks it reuses */
		sysfs_attr_selftest(); /* M101: its /sys and debugfs files, read back */

		/* How much of the boot CPU's stack the whole of kernel_main actually
		 * used, reported last so it covers every probe and self-test above.
		 *
		 * This is the check that was missing. The boot stack used to be
		 * 64 KiB and the boot path needed more than that on the deepest
		 * configuration, but an overflow wrote into ordinary .bss and nothing
		 * faulted, so the only evidence was a networking pointer going bad in
		 * one boot out of five. A used/total pair in the log turns that into
		 * an arithmetic fact anyone can read; the smoke suite fails the run if
		 * the peak passes 75% of the stack, well before the guard page. */
		{
			u64 used = boot_stack_peak_bytes();
			u64 total = boot_stack_size_bytes();
			char buf[96];
			snprintf(buf, sizeof(buf),
			         "BOOT-STACK: peak=%lu total=%lu pct=%lu\n",
			         (unsigned long)used, (unsigned long)total,
			         (unsigned long)(total ? (used * 100) / total : 0));
			console_write(buf);
		}
		/* And the same for the APs, which had the same defect for longer: a
		 * 16 KiB stack against a syscall path carrying a 28,584-byte frame.
		 * They only exist on SMP, which is why the corruption they caused only
		 * ever showed up there. */
		{
			extern u64 ap_stack_peak(u64 *total_out);
			u64 total = 0;
			u64 used = ap_stack_peak(&total);
			char buf[96];

			if (total) {
				snprintf(buf, sizeof(buf),
				         "AP-STACK: peak=%lu total=%lu pct=%lu\n",
				         (unsigned long)used, (unsigned long)total,
				         (unsigned long)((used * 100) / total));
				console_write(buf);
			}
		}
	}

	userspace_init();

	/* M94: Generic init path — honour `init=/path` from kernel cmdline.
	 * Default PID 1 is /sbin/init, which is BusyBox's `init` applet (the
	 * symlink is stamped by tools/ports/build-busybox.sh) — Alpine's layout.
	 * BusyBox init supervises (reaps orphans, respawns getty, runs the
	 * sysinit/shutdown phases) and /etc/inittab hands the service graph to
	 * OpenRC, which stays the high-level init: `openrc sysinit`, `openrc boot`,
	 * `openrc default`. OpenRC's own PID 1, /sbin/openrc-init, remains a
	 * bootable configuration through `init=/sbin/openrc-init` (it owns the
	 * /run/openrc/init.ctl control channel that openrc-shutdown and telinit
	 * talk to), and is exercised by the `openrc` smoke instance.
	 * `b1nix.single` maps to `init=/bin/sh` (standard single-user mode).
	 * The old test orchestrator `/bin/init` can be selected via `init=/bin/init`. */
	char init_path_buf[128];
	const char *init_path = "/sbin/init";
	if (bootinfo_get_kv("init", init_path_buf, sizeof(init_path_buf)) &&
	    init_path_buf[0] != '\0') {
		init_path = init_path_buf;
	} else if (bootinfo_has_flag("b1nix.single")) {
		init_path = "/bin/sh";
	}

	char init_log[160];
	/* init must be PID 1: real init systems (openrc-init, sysvinit) bail out
	 * with `if (getpid() != 1) return 1;`. The boot task is PID 0 and ids from
	 * 2 up went to the kernel threads started above, so 1 is still free. */
	scheduler_reserve_init_pid();
	int init_pid = user_spawn(init_path, 0, 0);
	if (init_pid > 0)
		scheduler_set_init_pid((usize)init_pid);
	snprintf(init_log, sizeof(init_log), "init: %s pid=%d\n",
	         init_path, init_pid);
	console_write(init_log);

	/* M68 native-Rust proof: the rustc ELF + librustc_driver.so (LLVM folded in) +
	 * the std sysroot (~hundreds of MB) are far too big for the
	 * xxd-embedded initramfs, so — like d8 above — they ship as a
	 * Multiboot2 module (limine.conf `module_path .../rust.img`) exposed as the ram0
	 * ext4 block device. With b1nix.rustrun the kernel mounts it and launches
	 * /bin/rustc. rustc has librustc_driver.so/libLLVM.so as DT_NEEDED (no
	 * PT_INTERP), so just loading the binary exercises the M69 recursive
	 * exec-time dynamic linker across the whole ~325MB .so graph. Running
	 * `rustc --version` then proves the loaded compiler actually executes on
	 * b1nix (it prints its real version string to serial). Gated by a cmdline
	 * flag so it never fires in the ordinary smoke suite. */
	if (bootinfo_has_flag("b1nix.rustrun")) {
		vfs_mkdir("/mnt/rust", 0755);
		int rust_mrc = vfs_mount("ram0", "/mnt/rust", "ext4", 0);
		char rust_buf[96];
		snprintf(rust_buf, sizeof(rust_buf), "rust: mount ram0 -> /mnt/rust: %d\n", rust_mrc);
		console_write(rust_buf);
		if (rust_mrc == 0) {
			const char *rust_argv[] = {"rustc", "--version", 0};
			int rust_pid = user_spawn("/mnt/rust/bin/rustc", 2, rust_argv);
			snprintf(rust_buf, sizeof(rust_buf), "rust: rustc spawn result: %d\n", rust_pid);
			console_write(rust_buf);
			/* A valid pid means user_load_elf64 resolved and relocated the whole
			 * rustc -> librustc_driver.so (LLVM folded) -> libc.so.1 graph
			 * (~250MB) through the M69 exec-time dynamic linker. rustc then prints
			 * its real version banner ("rustc 1.x ...") when it runs — that banner
			 * is the execution proof the smoke runner checks for. */
			if (rust_pid > 0)
				console_write("M68-RUST: ok rustc-load\n");
			else
				k_info(NULL, "M68-RUST: fail rustc-load");
		}
	}

	/* M64 native self-host Clang. The b1nix-native clang-22 (a ~94MB ELF that
	 * statically links LLVM + libstdc++, NEEDED only libc.so.1) ships inside a
	 * self-contained ISO as a Multiboot2 module (ext4) exposed as ram0 —
	 * exactly like rustc/d8 above. With b1nix.clangrun the kernel mounts ram0
	 * -> /mnt/clang and exercises the compiler two ways: `clang --version`
	 * proves the loaded compiler executes on b1nix (it prints its real version
	 * banner to serial — the load proof), and `clang -cc1 -emit-obj hello.c`
	 * proves the frontend+backend+integrated-assembler produce a valid b1nix
	 * object natively (the kernel then checks the emitted hello.o for the ELF
	 * magic — the compile proof). Gated by a cmdline flag so it never fires in
	 * the ordinary smoke suite. */
	if (bootinfo_has_flag("b1nix.clangrun")) {
		vfs_mkdir("/mnt/clang", 0755);
		int clang_mrc = vfs_mount("ram0", "/mnt/clang", "ext4", 0);
		char clang_buf[96];
		snprintf(clang_buf, sizeof(clang_buf), "clang: mount ram0 -> /mnt/clang: %d\n", clang_mrc);
		console_write(clang_buf);
		if (clang_mrc == 0) {
			/* (1) Load + run proof: clang prints its real version banner. A
			 * valid pid means the M69 exec-time loader resolved clang-22 ->
			 * libc.so.1 and relocated the whole image; SYS_WAIT lets it run to
			 * completion so the banner reaches serial before we mark it. */
			const char *ver_argv[] = {"clang", "--version", 0};
			int ver_pid = user_spawn("/mnt/clang/bin/clang", 2, ver_argv);
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang --version spawn: %d\n", ver_pid);
			console_write(clang_buf);
			if (ver_pid > 0) {
				int ver_st = 0;
				syscall_dispatch(SYS_WAIT, (u64)ver_pid, (u64)(usize)&ver_st, 0, 0, 0, 0);
				console_write("M64-NATIVE-CLANG: ok clang-load\n");
			} else {
				k_info(NULL, "M64-NATIVE-CLANG: fail clang-load");
			}

			/* (2) Compile proof: emit an object for the default x86_64-b1nix
			 * target from a header-free TU. Wait for clang to finish, then
			 * verify the ELF magic of the emitted object — only a genuinely
			 * running frontend+backend+assembler can produce it. */
			const char *cc_argv[] = {"clang", "-c", "/mnt/clang/hello.c",
			                         "-o", "/mnt/clang/hello.o", 0};
			int cc_pid = user_spawn("/mnt/clang/bin/clang", 5, cc_argv);
			int cc_st = -1;
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang -c spawn: %d\n", cc_pid);
			console_write(clang_buf);
			if (cc_pid > 0)
				syscall_dispatch(SYS_WAIT, (u64)cc_pid, (u64)(usize)&cc_st, 0, 0, 0, 0);
			unsigned char elfmag[4] = {0};
			int ofd = vfs_open("/mnt/clang/hello.o");
			if (ofd >= 0) {
				vfs_read(ofd, (char *)elfmag, sizeof(elfmag));
				vfs_close(ofd);
			}
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang -c exit=%d obj-magic=%02x%02x%02x%02x\n",
			         cc_st, elfmag[0], elfmag[1], elfmag[2], elfmag[3]);
			console_write(clang_buf);
			if (cc_pid > 0 && elfmag[0] == 0x7f && elfmag[1] == 'E' &&
			    elfmag[2] == 'L' && elfmag[3] == 'F')
				console_write("M64-NATIVE-CLANG: ok compile\n");
			else
				k_info(NULL, "M64-NATIVE-CLANG: fail compile");

			/* Diagnostic: also compile at -O2. The optimized path uses the
			 * greedy allocator and has no "must use fast regalloc" check, so a
			 * valid object here proves the dynamic libLLVM.so codegen+assembler
			 * work end to end (and bounds any -O0 fast-regalloc defect to that
			 * one path — the level llvmpipe never JITs at). */
			const char *cc2_argv[] = {"clang", "-O2", "-c", "/mnt/clang/hello.c",
			                          "-o", "/mnt/clang/hello2.o", 0};
			int cc2_pid = user_spawn("/mnt/clang/bin/clang", 6, cc2_argv);
			int cc2_st = -1;
			if (cc2_pid > 0)
				syscall_dispatch(SYS_WAIT, (u64)cc2_pid, (u64)(usize)&cc2_st, 0, 0, 0, 0);
			unsigned char elfmag2[4] = {0};
			int ofd2 = vfs_open("/mnt/clang/hello2.o");
			if (ofd2 >= 0) {
				vfs_read(ofd2, (char *)elfmag2, sizeof(elfmag2));
				vfs_close(ofd2);
			}
			snprintf(clang_buf, sizeof(clang_buf), "clang: clang -O2 -c exit=%d obj-magic=%02x%02x%02x%02x\n",
			         cc2_st, elfmag2[0], elfmag2[1], elfmag2[2], elfmag2[3]);
			console_write(clang_buf);
			if (cc2_pid > 0 && elfmag2[0] == 0x7f && elfmag2[1] == 'E' &&
			    elfmag2[2] == 'L' && elfmag2[3] == 'F')
				console_write("M64-NATIVE-CLANG: ok compile-O2\n");
			else
				k_info(NULL, "M64-NATIVE-CLANG: fail compile-O2");
		}
	}

	/* M26 native-Clang KERNEL self-host. The self-host module (clang + ld.lld +
	 * kernel source + the flat TU list) ships as the ram0 ext4 Multiboot2 module. With
	 * b1nix.selfhostbuild the kernel mounts it and compiles+links its own kernel
	 * in-guest with its own clang+ld.lld (the same toolchain the host uses), the
	 * real M26 self-host. Gated by a cmdline flag so it never fires in the
	 * ordinary smoke suite. */
	if (bootinfo_has_flag("b1nix.selfhostbuild")) {
		vfs_mkdir("/mnt/build", 0755);
		/* b1nix.selfhostdisk sources the toolchain from a real SATA disk (sda)
		 * instead of the ram0 Multiboot2 module. The module is a ramdisk: its ~217 MB
		 * stay pinned in RAM for the whole build. A disk leaves that 217 MB free
		 * — the toolchain streams off AHCI through the (now read-ahead) block
		 * cache — so the self-host fits in far less RAM. */
		const char *sh_src =
		    bootinfo_has_flag("b1nix.selfhostdisk") ? "sda" : "ram0";
		int sh_mrc = vfs_mount(sh_src, "/mnt/build", "ext4", 0);
		char sh_buf[80];
		snprintf(sh_buf, sizeof(sh_buf), "selfhost: mount %s -> /mnt/build: %d\n",
		         sh_src, sh_mrc);
		console_write(sh_buf);
		if (sh_mrc == 0) {
			/* M93: self-host build orchestration moved to userspace.
			 * Spawn /bin/selfhost-build which reads srcs.txt, compiles
			 * each TU with clang, and links with ld.lld. */
			const char *sh_argv[] = {"/mnt/build/bin/selfhost-build", 0};
			int sh_pid = user_spawn("/mnt/build/bin/selfhost-build", 1, sh_argv);
			if (sh_pid > 0) {
				int sh_st = 0;
				syscall_dispatch(SYS_WAIT, (u64)sh_pid,
				                 (u64)(usize)&sh_st, 0, 0, 0, 0);
				char sh_res[80];
				snprintf(sh_res, sizeof(sh_res),
				         "selfhost: selfhost-build exit=%d\n", sh_st);
				console_write(sh_res);
			} else {
				console_write("selfhost: fail spawn selfhost-build\n");
			}
		}
	}

	/* BSP idle loop. The BKL is fully retired (M28 #7): kernel entry runs
	 * BKL-free and scheduler_yield no longer hands a lock across the context
	 * switch, so the idle loop just yields and parks when there is no work. */
	while (scheduler_task_count() > 1) {
		int switched = scheduler_yield();
		if (!switched) {
			__asm__ volatile("sti; hlt" : : : "memory");
		}
	}

	k_info(NULL, "\nM6 network layer demo complete");
	arch_halt();
}
