#!/bin/sh
# AUTO-GENERATED by smoke_run/_m26_gen_kbuild.sh (inguest). Flat (no loops).
echo KBUILD-START
/bin/mkdir -p /tmp/kbuild
echo KBUILD 1 kernel_arch_x86_arch
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/arch.c -o /tmp/kbuild/kernel_arch_x86_arch.o
echo KBUILD 2 kernel_arch_x86_boot
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/boot.S -o /tmp/kbuild/kernel_arch_x86_boot.o
echo KBUILD 3 kernel_arch_x86_console
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/console.c -o /tmp/kbuild/kernel_arch_x86_console.o
echo KBUILD 4 kernel_arch_x86_context_switch
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/context_switch.S -o /tmp/kbuild/kernel_arch_x86_context_switch.o
echo KBUILD 5 kernel_arch_x86_fb_console
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/fb_console.c -o /tmp/kbuild/kernel_arch_x86_fb_console.o
echo KBUILD 6 kernel_arch_x86_fpu
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/fpu.S -o /tmp/kbuild/kernel_arch_x86_fpu.o
echo KBUILD 7 kernel_arch_x86_interrupts
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/interrupts.c -o /tmp/kbuild/kernel_arch_x86_interrupts.o
echo KBUILD 8 kernel_arch_x86_io
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/io.c -o /tmp/kbuild/kernel_arch_x86_io.o
echo KBUILD 9 kernel_arch_x86_isr
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/isr.S -o /tmp/kbuild/kernel_arch_x86_isr.o
echo KBUILD 10 kernel_arch_x86_lapic
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/lapic.c -o /tmp/kbuild/kernel_arch_x86_lapic.o
echo KBUILD 11 kernel_arch_x86_paging
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/paging.c -o /tmp/kbuild/kernel_arch_x86_paging.o
echo KBUILD 12 kernel_arch_x86_rtc
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/rtc.c -o /tmp/kbuild/kernel_arch_x86_rtc.o
echo KBUILD 13 kernel_arch_x86_serial
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/serial.c -o /tmp/kbuild/kernel_arch_x86_serial.o
echo KBUILD 14 kernel_arch_x86_signal
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/signal.c -o /tmp/kbuild/kernel_arch_x86_signal.o
echo KBUILD 15 kernel_arch_x86_syscall_entry
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/syscall_entry.S -o /tmp/kbuild/kernel_arch_x86_syscall_entry.o
echo KBUILD 16 kernel_arch_x86_user_jump
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/arch/x86/user_jump.S -o /tmp/kbuild/kernel_arch_x86_user_jump.o
echo KBUILD 17 kernel_bootinfo_multiboot2
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/bootinfo/multiboot2.c -o /tmp/kbuild/kernel_bootinfo_multiboot2.o
echo KBUILD 18 kernel_dev_ahci
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/ahci.c -o /tmp/kbuild/kernel_dev_ahci.o
echo KBUILD 19 kernel_dev_blk
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/blk.c -o /tmp/kbuild/kernel_dev_blk.o
echo KBUILD 20 kernel_dev_compositor
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/compositor.c -o /tmp/kbuild/kernel_dev_compositor.o
echo KBUILD 21 kernel_dev_nvme
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/nvme.c -o /tmp/kbuild/kernel_dev_nvme.o
echo KBUILD 22 kernel_dev_pci
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/pci.c -o /tmp/kbuild/kernel_dev_pci.o
echo KBUILD 23 kernel_dev_ps2_kbd
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/ps2_kbd.c -o /tmp/kbuild/kernel_dev_ps2_kbd.o
echo KBUILD 24 kernel_dev_ps2_mouse
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/ps2_mouse.c -o /tmp/kbuild/kernel_dev_ps2_mouse.o
echo KBUILD 25 kernel_dev_video
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/video.c -o /tmp/kbuild/kernel_dev_video.o
echo KBUILD 26 kernel_dev_virtio_blk
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/virtio_blk.c -o /tmp/kbuild/kernel_dev_virtio_blk.o
echo KBUILD 27 kernel_dev_virtio_gpu
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/virtio_gpu.c -o /tmp/kbuild/kernel_dev_virtio_gpu.o
echo KBUILD 28 kernel_dev_virtio
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/dev/virtio.c -o /tmp/kbuild/kernel_dev_virtio.o
echo KBUILD 29 kernel_fs_aio
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/aio.c -o /tmp/kbuild/kernel_fs_aio.o
echo KBUILD 30 kernel_fs_btrfs
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/btrfs.c -o /tmp/kbuild/kernel_fs_btrfs.o
echo KBUILD 31 kernel_fs_ext1
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/ext1.c -o /tmp/kbuild/kernel_fs_ext1.o
echo KBUILD 32 kernel_fs_ext2
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/ext2.c -o /tmp/kbuild/kernel_fs_ext2.o
echo KBUILD 33 kernel_fs_ext3
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/ext3.c -o /tmp/kbuild/kernel_fs_ext3.o
echo KBUILD 34 kernel_fs_ext4
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/ext4.c -o /tmp/kbuild/kernel_fs_ext4.o
echo KBUILD 35 kernel_fs_fat32
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/fat32.c -o /tmp/kbuild/kernel_fs_fat32.o
echo KBUILD 36 kernel_fs_filelock
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/filelock.c -o /tmp/kbuild/kernel_fs_filelock.o
echo KBUILD 37 kernel_fs_initramfs
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/initramfs.c -o /tmp/kbuild/kernel_fs_initramfs.o
echo KBUILD 38 kernel_fs_journal
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/journal.c -o /tmp/kbuild/kernel_fs_journal.o
echo KBUILD 39 kernel_fs_pipe
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/pipe.c -o /tmp/kbuild/kernel_fs_pipe.o
echo KBUILD 40 kernel_fs_vfs
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/vfs.c -o /tmp/kbuild/kernel_fs_vfs.o
echo KBUILD 41 kernel_fs_vfs_slab
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/fs/vfs_slab.c -o /tmp/kbuild/kernel_fs_vfs_slab.o
echo KBUILD 42 kernel_ipc_mqueue
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/ipc/mqueue.c -o /tmp/kbuild/kernel_ipc_mqueue.o
echo KBUILD 43 kernel_ipc_shm
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/ipc/shm.c -o /tmp/kbuild/kernel_ipc_shm.o
echo KBUILD 44 kernel_lib_klog
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/lib/klog.c -o /tmp/kbuild/kernel_lib_klog.o
echo KBUILD 45 kernel_lib_stdio
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/lib/stdio.c -o /tmp/kbuild/kernel_lib_stdio.o
echo KBUILD 46 kernel_lib_stdlib
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/lib/stdlib.c -o /tmp/kbuild/kernel_lib_stdlib.o
echo KBUILD 47 kernel_lib_string
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/lib/string.c -o /tmp/kbuild/kernel_lib_string.o
echo KBUILD 48 kernel_lib_unistd
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/lib/unistd.c -o /tmp/kbuild/kernel_lib_unistd.o
echo KBUILD 49 kernel_main
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/main.c -o /tmp/kbuild/kernel_main.o
echo KBUILD 50 kernel_mm_eviction
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/mm/eviction.c -o /tmp/kbuild/kernel_mm_eviction.o
echo KBUILD 51 kernel_mm_kheap
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/mm/kheap.c -o /tmp/kbuild/kernel_mm_kheap.o
echo KBUILD 52 kernel_mm_page_cache
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/mm/page_cache.c -o /tmp/kbuild/kernel_mm_page_cache.o
echo KBUILD 53 kernel_mm_pmm
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/mm/pmm.c -o /tmp/kbuild/kernel_mm_pmm.o
echo KBUILD 54 kernel_mm_swap
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/mm/swap.c -o /tmp/kbuild/kernel_mm_swap.o
echo KBUILD 55 kernel_net_arp
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/arp.c -o /tmp/kbuild/kernel_net_arp.o
echo KBUILD 56 kernel_net_dhcp
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/dhcp.c -o /tmp/kbuild/kernel_net_dhcp.o
echo KBUILD 57 kernel_net_dns
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/dns.c -o /tmp/kbuild/kernel_net_dns.o
echo KBUILD 58 kernel_net_ethernet
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/ethernet.c -o /tmp/kbuild/kernel_net_ethernet.o
echo KBUILD 59 kernel_net_icmp
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/icmp.c -o /tmp/kbuild/kernel_net_icmp.o
echo KBUILD 60 kernel_net_ipv4
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/ipv4.c -o /tmp/kbuild/kernel_net_ipv4.o
echo KBUILD 61 kernel_net_net
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/net.c -o /tmp/kbuild/kernel_net_net.o
echo KBUILD 62 kernel_net_socket
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/socket.c -o /tmp/kbuild/kernel_net_socket.o
echo KBUILD 63 kernel_net_tcp
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/tcp.c -o /tmp/kbuild/kernel_net_tcp.o
echo KBUILD 64 kernel_net_udp
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/udp.c -o /tmp/kbuild/kernel_net_udp.o
echo KBUILD 65 kernel_net_unix
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/net/unix.c -o /tmp/kbuild/kernel_net_unix.o
echo KBUILD 66 kernel_sched_runqueue
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/sched/runqueue.c -o /tmp/kbuild/kernel_sched_runqueue.o
echo KBUILD 67 kernel_sched_scheduler
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/sched/scheduler.c -o /tmp/kbuild/kernel_sched_scheduler.o
echo KBUILD 68 kernel_sched_uidgid
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/sched/uidgid.c -o /tmp/kbuild/kernel_sched_uidgid.o
echo KBUILD 69 kernel_syscall_syscall
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/syscall/syscall.c -o /tmp/kbuild/kernel_syscall_syscall.o
echo KBUILD 70 kernel_user_busybox
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/user/busybox.c -o /tmp/kbuild/kernel_user_busybox.o
echo KBUILD 71 kernel_user_editor
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/user/editor.c -o /tmp/kbuild/kernel_user_editor.o
echo KBUILD 72 kernel_user_mc
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/user/mc.c -o /tmp/kbuild/kernel_user_mc.o
echo KBUILD 73 kernel_user_nmake
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/user/nmake.c -o /tmp/kbuild/kernel_user_nmake.o
echo KBUILD 74 kernel_user_process
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/user/process.c -o /tmp/kbuild/kernel_user_process.o
echo KBUILD 75 kernel_user_programs
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/user/programs.c -o /tmp/kbuild/kernel_user_programs.o
echo KBUILD 76 kernel_user_tui_common
/persist/bin/gcc -std=c11 -ffreestanding -fno-builtin -fno-stack-protector -fno-pic -mno-red-zone -I/persist/usr/src/b1nix/kernel/include -mcmodel=kernel -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -c /persist/usr/src/b1nix/kernel/user/tui_common.c -o /tmp/kbuild/kernel_user_tui_common.o
echo KBUILD-LINK
/persist/bin/ld -m elf_x86_64 -z max-page-size=0x1000 -T /persist/usr/src/b1nix/kernel/arch/x86/linker.ld -o /tmp/kernel.elf @/persist/usr/src/b1nix/tools/inguest/kernel.rsp
echo KBUILD-LINK-DONE
ls -l /tmp/kernel.elf
echo KBUILD-DONE
