---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - sudo
    - audio
    - video
    - plugdev
    - netdev
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true
passwordRequirements:
    minLength: 1
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: true
user:
  shell: /bin/bash
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "b1nix-${cpu}"
presets:
    fullName:
        editable: true
    loginName:
        editable: true
