---
showSupportUrl: false
showKnownIssuesUrl: true
showReleaseNotesUrl: false
requirements:
    requiredStorage:    8
    requiredRam:        1.0
    check:
      - storage
      - ram
      - root
    required:
      - storage
      - root
