#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Arm64 CPU feature-register tables, cut from the staged cpufeature.c.

    gen-arm64-ftr.py STAGED/arch/arm64/kernel/cpufeature.c OUT.c

arm64 KVM (M131) validates a guest's ID registers field by field against the
host's, through upstream's arm64_ftr_bits tables and the sanitised system-wide
values built from them. Those tables are data in cpufeature.c, next to a boot
path b1nix does not run; this takes the tables and the functions that only
read and combine them, unchanged, the way Kbuild's awk steps turn the sysreg
and cpucaps lists into headers. Every piece is found by its first line and
must be there: a release that moves one fails the build rather than
producing a partial file.
"""
import re
import sys


def block(lines, start_re, end_re):
    """Lines from the one matching start_re up to (not including) end_re."""
    for i, line in enumerate(lines):
        if re.match(start_re, line):
            for j in range(i + 1, len(lines)):
                if re.match(end_re, lines[j]):
                    return lines[i:j]
            break
    sys.exit("gen-arm64-ftr: no block from %r to %r" % (start_re, end_re))


def function(lines, head_re):
    """A function from its first line through the closing brace."""
    for i, line in enumerate(lines):
        if re.match(head_re, line):
            for j in range(i + 1, len(lines)):
                if lines[j] == "}":
                    return lines[i:j + 1]
            break
    sys.exit("gen-arm64-ftr: no function %r" % head_re)


def main():
    src, out = sys.argv[1], sys.argv[2]
    with open(src) as f:
        lines = f.read().split("\n")
    parts = [
        block(lines, r"#define __ARM64_MAX_POSITIVE", r"static void __init sort_ftr_regs\(void\)"),
        function(lines, r"static void init_cpu_ftr_reg\(u32 sys_reg, u64 new\)"),
        function(lines, r"static void update_cpu_ftr_reg\(struct arm64_ftr_reg \*reg, u64 new\)"),
        function(lines, r"u64 read_sanitised_ftr_reg\(u32 id\)"),
        block(lines, r"#define read_sysreg_case\(r\)", r"u64 __read_sysreg_by_encoding\(u32 sys_id\)"),
        function(lines, r"u64 __read_sysreg_by_encoding\(u32 sys_id\)"),
    ]
    text = [
        "// SPDX-License-Identifier: GPL-2.0-only",
        "/* Generated by tools/import/kvm/gen-arm64-ftr.py from",
        " * arch/arm64/kernel/cpufeature.c; do not edit. */",
        "#include <linux/bsearch.h>",
        "#include <linux/bug.h>",
        "#include <linux/minmax.h>",
        "#include <asm/cpufeature.h>",
        "#include <asm/sysreg.h>",
        "",
    ]
    for p in parts:
        text += p + [""]
    text += [
        "/* b1nix's way in: the registers the tables cover, and the boot",
        " * CPU's and every other CPU's values folded into them. */",
        "unsigned int lkpi_arm64_ftr_count(void)",
        "{",
        "\treturn ARRAY_SIZE(arm64_ftr_regs);",
        "}",
        "",
        "u32 lkpi_arm64_ftr_sys_id(unsigned int i)",
        "{",
        "\treturn arm64_ftr_regs[i].sys_id;",
        "}",
        "",
        "void lkpi_arm64_ftr_init(u32 sys_id, u64 val)",
        "{",
        "\tinit_cpu_ftr_reg(sys_id, val);",
        "}",
        "",
        "void lkpi_arm64_ftr_update(u32 sys_id, u64 val)",
        "{",
        "\tstruct arm64_ftr_reg *reg = get_arm64_ftr_reg(sys_id);",
        "",
        "\tif (reg)",
        "\t\tupdate_cpu_ftr_reg(reg, val);",
        "}",
        "",
    ]
    with open(out, "w") as f:
        f.write("\n".join(text))


if __name__ == "__main__":
    main()
