/* Auto-generated: `xkbcli compile-keymap --layout us` (US QWERTY, evdev).
 * Embedded so displayd can send a real XKB_V1 keymap fd without linking
 * xkbcommon or shipping XKB data files. Regenerate only if the layout
 * needs to change. Clients (GTK/Qt/SDL via their own xkbcommon) parse this
 * to translate the raw evdev keycodes displayd sends in wl_keyboard.key. */
static const char xkb_keymap_us[] =
	"xkb_keymap {\n"
	"xkb_keycodes \"evdev_aliases(qwerty)\" {\n"
	"	minimum = 8;\n"
	"	maximum = 709;\n"
	"	<ESC>                = 9;\n"
	"	<AE01>               = 10;\n"
	"	<AE02>               = 11;\n"
	"	<AE03>               = 12;\n"
	"	<AE04>               = 13;\n"
	"	<AE05>               = 14;\n"
	"	<AE06>               = 15;\n"
	"	<AE07>               = 16;\n"
	"	<AE08>               = 17;\n"
	"	<AE09>               = 18;\n"
	"	<AE10>               = 19;\n"
	"	<AE11>               = 20;\n"
	"	<AE12>               = 21;\n"
	"	<BKSP>               = 22;\n"
	"	<TAB>                = 23;\n"
	"	<AD01>               = 24;\n"
	"	<AD02>               = 25;\n"
	"	<AD03>               = 26;\n"
	"	<AD04>               = 27;\n"
	"	<AD05>               = 28;\n"
	"	<AD06>               = 29;\n"
	"	<AD07>               = 30;\n"
	"	<AD08>               = 31;\n"
	"	<AD09>               = 32;\n"
	"	<AD10>               = 33;\n"
	"	<AD11>               = 34;\n"
	"	<AD12>               = 35;\n"
	"	<RTRN>               = 36;\n"
	"	<LCTL>               = 37;\n"
	"	<AC01>               = 38;\n"
	"	<AC02>               = 39;\n"
	"	<AC03>               = 40;\n"
	"	<AC04>               = 41;\n"
	"	<AC05>               = 42;\n"
	"	<AC06>               = 43;\n"
	"	<AC07>               = 44;\n"
	"	<AC08>               = 45;\n"
	"	<AC09>               = 46;\n"
	"	<AC10>               = 47;\n"
	"	<AC11>               = 48;\n"
	"	<TLDE>               = 49;\n"
	"	<LFSH>               = 50;\n"
	"	<BKSL>               = 51;\n"
	"	<AB01>               = 52;\n"
	"	<AB02>               = 53;\n"
	"	<AB03>               = 54;\n"
	"	<AB04>               = 55;\n"
	"	<AB05>               = 56;\n"
	"	<AB06>               = 57;\n"
	"	<AB07>               = 58;\n"
	"	<AB08>               = 59;\n"
	"	<AB09>               = 60;\n"
	"	<AB10>               = 61;\n"
	"	<RTSH>               = 62;\n"
	"	<KPMU>               = 63;\n"
	"	<LALT>               = 64;\n"
	"	<SPCE>               = 65;\n"
	"	<CAPS>               = 66;\n"
	"	<FK01>               = 67;\n"
	"	<FK02>               = 68;\n"
	"	<FK03>               = 69;\n"
	"	<FK04>               = 70;\n"
	"	<FK05>               = 71;\n"
	"	<FK06>               = 72;\n"
	"	<FK07>               = 73;\n"
	"	<FK08>               = 74;\n"
	"	<FK09>               = 75;\n"
	"	<FK10>               = 76;\n"
	"	<NMLK>               = 77;\n"
	"	<SCLK>               = 78;\n"
	"	<KP7>                = 79;\n"
	"	<KP8>                = 80;\n"
	"	<KP9>                = 81;\n"
	"	<KPSU>               = 82;\n"
	"	<KP4>                = 83;\n"
	"	<KP5>                = 84;\n"
	"	<KP6>                = 85;\n"
	"	<KPAD>               = 86;\n"
	"	<KP1>                = 87;\n"
	"	<KP2>                = 88;\n"
	"	<KP3>                = 89;\n"
	"	<KP0>                = 90;\n"
	"	<KPDL>               = 91;\n"
	"	<LVL3>               = 92;\n"
	"	<ZEHA>               = 93;\n"
	"	<LSGT>               = 94;\n"
	"	<FK11>               = 95;\n"
	"	<FK12>               = 96;\n"
	"	<AB11>               = 97;\n"
	"	<KATA>               = 98;\n"
	"	<HIRA>               = 99;\n"
	"	<HENK>               = 100;\n"
	"	<HKTG>               = 101;\n"
	"	<MUHE>               = 102;\n"
	"	<JPCM>               = 103;\n"
	"	<KPEN>               = 104;\n"
	"	<RCTL>               = 105;\n"
	"	<KPDV>               = 106;\n"
	"	<PRSC>               = 107;\n"
	"	<RALT>               = 108;\n"
	"	<LNFD>               = 109;\n"
	"	<HOME>               = 110;\n"
	"	<UP>                 = 111;\n"
	"	<PGUP>               = 112;\n"
	"	<LEFT>               = 113;\n"
	"	<RGHT>               = 114;\n"
	"	<END>                = 115;\n"
	"	<DOWN>               = 116;\n"
	"	<PGDN>               = 117;\n"
	"	<INS>                = 118;\n"
	"	<DELE>               = 119;\n"
	"	<I120>               = 120;\n"
	"	<MUTE>               = 121;\n"
	"	<VOL->               = 122;\n"
	"	<VOL+>               = 123;\n"
	"	<POWR>               = 124;\n"
	"	<KPEQ>               = 125;\n"
	"	<I126>               = 126;\n"
	"	<PAUS>               = 127;\n"
	"	<I128>               = 128;\n"
	"	<I129>               = 129;\n"
	"	<HNGL>               = 130;\n"
	"	<HJCV>               = 131;\n"
	"	<AE13>               = 132;\n"
	"	<LWIN>               = 133;\n"
	"	<RWIN>               = 134;\n"
	"	<COMP>               = 135;\n"
	"	<STOP>               = 136;\n"
	"	<AGAI>               = 137;\n"
	"	<PROP>               = 138;\n"
	"	<UNDO>               = 139;\n"
	"	<FRNT>               = 140;\n"
	"	<COPY>               = 141;\n"
	"	<OPEN>               = 142;\n"
	"	<PAST>               = 143;\n"
	"	<FIND>               = 144;\n"
	"	<CUT>                = 145;\n"
	"	<HELP>               = 146;\n"
	"	<I147>               = 147;\n"
	"	<I148>               = 148;\n"
	"	<I149>               = 149;\n"
	"	<I150>               = 150;\n"
	"	<I151>               = 151;\n"
	"	<I152>               = 152;\n"
	"	<I153>               = 153;\n"
	"	<I154>               = 154;\n"
	"	<I155>               = 155;\n"
	"	<I156>               = 156;\n"
	"	<I157>               = 157;\n"
	"	<I158>               = 158;\n"
	"	<I159>               = 159;\n"
	"	<I160>               = 160;\n"
	"	<I161>               = 161;\n"
	"	<I162>               = 162;\n"
	"	<I163>               = 163;\n"
	"	<I164>               = 164;\n"
	"	<I165>               = 165;\n"
	"	<I166>               = 166;\n"
	"	<I167>               = 167;\n"
	"	<I168>               = 168;\n"
	"	<I169>               = 169;\n"
	"	<I170>               = 170;\n"
	"	<I171>               = 171;\n"
	"	<I172>               = 172;\n"
	"	<I173>               = 173;\n"
	"	<I174>               = 174;\n"
	"	<I175>               = 175;\n"
	"	<I176>               = 176;\n"
	"	<I177>               = 177;\n"
	"	<I178>               = 178;\n"
	"	<I179>               = 179;\n"
	"	<I180>               = 180;\n"
	"	<I181>               = 181;\n"
	"	<I182>               = 182;\n"
	"	<I183>               = 183;\n"
	"	<I184>               = 184;\n"
	"	<I185>               = 185;\n"
	"	<I186>               = 186;\n"
	"	<I187>               = 187;\n"
	"	<I188>               = 188;\n"
	"	<I189>               = 189;\n"
	"	<I190>               = 190;\n"
	"	<FK13>               = 191;\n"
	"	<FK14>               = 192;\n"
	"	<FK15>               = 193;\n"
	"	<FK16>               = 194;\n"
	"	<FK17>               = 195;\n"
	"	<FK18>               = 196;\n"
	"	<FK19>               = 197;\n"
	"	<FK20>               = 198;\n"
	"	<FK21>               = 199;\n"
	"	<FK22>               = 200;\n"
	"	<FK23>               = 201;\n"
	"	<FK24>               = 202;\n"
	"	<LVL5>               = 203;\n"
	"	<ALT>                = 204;\n"
	"	<META>               = 205;\n"
	"	<SUPR>               = 206;\n"
	"	<HYPR>               = 207;\n"
	"	<I208>               = 208;\n"
	"	<I209>               = 209;\n"
	"	<I210>               = 210;\n"
	"	<I211>               = 211;\n"
	"	<I212>               = 212;\n"
	"	<I213>               = 213;\n"
	"	<I214>               = 214;\n"
	"	<I215>               = 215;\n"
	"	<I216>               = 216;\n"
	"	<I217>               = 217;\n"
	"	<I218>               = 218;\n"
	"	<I219>               = 219;\n"
	"	<I220>               = 220;\n"
	"	<I221>               = 221;\n"
	"	<I222>               = 222;\n"
	"	<I223>               = 223;\n"
	"	<I224>               = 224;\n"
	"	<I225>               = 225;\n"
	"	<I226>               = 226;\n"
	"	<I227>               = 227;\n"
	"	<I228>               = 228;\n"
	"	<I229>               = 229;\n"
	"	<I230>               = 230;\n"
	"	<I231>               = 231;\n"
	"	<I232>               = 232;\n"
	"	<I233>               = 233;\n"
	"	<I234>               = 234;\n"
	"	<I235>               = 235;\n"
	"	<I236>               = 236;\n"
	"	<I237>               = 237;\n"
	"	<I238>               = 238;\n"
	"	<I239>               = 239;\n"
	"	<I240>               = 240;\n"
	"	<I241>               = 241;\n"
	"	<I242>               = 242;\n"
	"	<I243>               = 243;\n"
	"	<I244>               = 244;\n"
	"	<I245>               = 245;\n"
	"	<I246>               = 246;\n"
	"	<I247>               = 247;\n"
	"	<I248>               = 248;\n"
	"	<I249>               = 249;\n"
	"	<I250>               = 250;\n"
	"	<I251>               = 251;\n"
	"	<I252>               = 252;\n"
	"	<I253>               = 253;\n"
	"	<I254>               = 254;\n"
	"	<I255>               = 255;\n"
	"	<I256>               = 256;\n"
	"	<I360>               = 360;\n"
	"	<I361>               = 361;\n"
	"	<I362>               = 362;\n"
	"	<I363>               = 363;\n"
	"	<I364>               = 364;\n"
	"	<I365>               = 365;\n"
	"	<I366>               = 366;\n"
	"	<I367>               = 367;\n"
	"	<I368>               = 368;\n"
	"	<I369>               = 369;\n"
	"	<I370>               = 370;\n"
	"	<I371>               = 371;\n"
	"	<I372>               = 372;\n"
	"	<I373>               = 373;\n"
	"	<I374>               = 374;\n"
	"	<I375>               = 375;\n"
	"	<I376>               = 376;\n"
	"	<I377>               = 377;\n"
	"	<I378>               = 378;\n"
	"	<I379>               = 379;\n"
	"	<I380>               = 380;\n"
	"	<I381>               = 381;\n"
	"	<I382>               = 382;\n"
	"	<I383>               = 383;\n"
	"	<I384>               = 384;\n"
	"	<I385>               = 385;\n"
	"	<I386>               = 386;\n"
	"	<I387>               = 387;\n"
	"	<I388>               = 388;\n"
	"	<I389>               = 389;\n"
	"	<I390>               = 390;\n"
	"	<I391>               = 391;\n"
	"	<I392>               = 392;\n"
	"	<I393>               = 393;\n"
	"	<I394>               = 394;\n"
	"	<I395>               = 395;\n"
	"	<I396>               = 396;\n"
	"	<I397>               = 397;\n"
	"	<I398>               = 398;\n"
	"	<I399>               = 399;\n"
	"	<I400>               = 400;\n"
	"	<I401>               = 401;\n"
	"	<I402>               = 402;\n"
	"	<I403>               = 403;\n"
	"	<I404>               = 404;\n"
	"	<I405>               = 405;\n"
	"	<I406>               = 406;\n"
	"	<I407>               = 407;\n"
	"	<I408>               = 408;\n"
	"	<I409>               = 409;\n"
	"	<I410>               = 410;\n"
	"	<I411>               = 411;\n"
	"	<I412>               = 412;\n"
	"	<I413>               = 413;\n"
	"	<I414>               = 414;\n"
	"	<I415>               = 415;\n"
	"	<I416>               = 416;\n"
	"	<I417>               = 417;\n"
	"	<I418>               = 418;\n"
	"	<I419>               = 419;\n"
	"	<I420>               = 420;\n"
	"	<I421>               = 421;\n"
	"	<I422>               = 422;\n"
	"	<I423>               = 423;\n"
	"	<I424>               = 424;\n"
	"	<I425>               = 425;\n"
	"	<I426>               = 426;\n"
	"	<I427>               = 427;\n"
	"	<I428>               = 428;\n"
	"	<I429>               = 429;\n"
	"	<I430>               = 430;\n"
	"	<I431>               = 431;\n"
	"	<I432>               = 432;\n"
	"	<I433>               = 433;\n"
	"	<I434>               = 434;\n"
	"	<I435>               = 435;\n"
	"	<I436>               = 436;\n"
	"	<I437>               = 437;\n"
	"	<I438>               = 438;\n"
	"	<I439>               = 439;\n"
	"	<I440>               = 440;\n"
	"	<I441>               = 441;\n"
	"	<I442>               = 442;\n"
	"	<I443>               = 443;\n"
	"	<I444>               = 444;\n"
	"	<I445>               = 445;\n"
	"	<I446>               = 446;\n"
	"	<I447>               = 447;\n"
	"	<I448>               = 448;\n"
	"	<I449>               = 449;\n"
	"	<I450>               = 450;\n"
	"	<I452>               = 452;\n"
	"	<I453>               = 453;\n"
	"	<I454>               = 454;\n"
	"	<I455>               = 455;\n"
	"	<I456>               = 456;\n"
	"	<I457>               = 457;\n"
	"	<I458>               = 458;\n"
	"	<I459>               = 459;\n"
	"	<I472>               = 472;\n"
	"	<I473>               = 473;\n"
	"	<I474>               = 474;\n"
	"	<I475>               = 475;\n"
	"	<I476>               = 476;\n"
	"	<I477>               = 477;\n"
	"	<I478>               = 478;\n"
	"	<I479>               = 479;\n"
	"	<I480>               = 480;\n"
	"	<I481>               = 481;\n"
	"	<I482>               = 482;\n"
	"	<I483>               = 483;\n"
	"	<I484>               = 484;\n"
	"	<I485>               = 485;\n"
	"	<I486>               = 486;\n"
	"	<I487>               = 487;\n"
	"	<I488>               = 488;\n"
	"	<I489>               = 489;\n"
	"	<I490>               = 490;\n"
	"	<I491>               = 491;\n"
	"	<I492>               = 492;\n"
	"	<I493>               = 493;\n"
	"	<I505>               = 505;\n"
	"	<I506>               = 506;\n"
	"	<I507>               = 507;\n"
	"	<I508>               = 508;\n"
	"	<I509>               = 509;\n"
	"	<I510>               = 510;\n"
	"	<I511>               = 511;\n"
	"	<I512>               = 512;\n"
	"	<I513>               = 513;\n"
	"	<I514>               = 514;\n"
	"	<I520>               = 520;\n"
	"	<I521>               = 521;\n"
	"	<I522>               = 522;\n"
	"	<I523>               = 523;\n"
	"	<I524>               = 524;\n"
	"	<I525>               = 525;\n"
	"	<I526>               = 526;\n"
	"	<I527>               = 527;\n"
	"	<I528>               = 528;\n"
	"	<I529>               = 529;\n"
	"	<I530>               = 530;\n"
	"	<I531>               = 531;\n"
	"	<I532>               = 532;\n"
	"	<I533>               = 533;\n"
	"	<I534>               = 534;\n"
	"	<I535>               = 535;\n"
	"	<I536>               = 536;\n"
	"	<I537>               = 537;\n"
	"	<I538>               = 538;\n"
	"	<I539>               = 539;\n"
	"	<I540>               = 540;\n"
	"	<I541>               = 541;\n"
	"	<I542>               = 542;\n"
	"	<I543>               = 543;\n"
	"	<I544>               = 544;\n"
	"	<I545>               = 545;\n"
	"	<I546>               = 546;\n"
	"	<I547>               = 547;\n"
	"	<I548>               = 548;\n"
	"	<I549>               = 549;\n"
	"	<I550>               = 550;\n"
	"	<I568>               = 568;\n"
	"	<I569>               = 569;\n"
	"	<I570>               = 570;\n"
	"	<I584>               = 584;\n"
	"	<I585>               = 585;\n"
	"	<I586>               = 586;\n"
	"	<I587>               = 587;\n"
	"	<I588>               = 588;\n"
	"	<I589>               = 589;\n"
	"	<I590>               = 590;\n"
	"	<I591>               = 591;\n"
	"	<I592>               = 592;\n"
	"	<I593>               = 593;\n"
	"	<I594>               = 594;\n"
	"	<I595>               = 595;\n"
	"	<I596>               = 596;\n"
	"	<I597>               = 597;\n"
	"	<I598>               = 598;\n"
	"	<I599>               = 599;\n"
	"	<I600>               = 600;\n"
	"	<I601>               = 601;\n"
	"	<I616>               = 616;\n"
	"	<I617>               = 617;\n"
	"	<I618>               = 618;\n"
	"	<I619>               = 619;\n"
	"	<I620>               = 620;\n"
	"	<I621>               = 621;\n"
	"	<I622>               = 622;\n"
	"	<I623>               = 623;\n"
	"	<I624>               = 624;\n"
	"	<I625>               = 625;\n"
	"	<I626>               = 626;\n"
	"	<I627>               = 627;\n"
	"	<I628>               = 628;\n"
	"	<I629>               = 629;\n"
	"	<I630>               = 630;\n"
	"	<I631>               = 631;\n"
	"	<I632>               = 632;\n"
	"	<I633>               = 633;\n"
	"	<I634>               = 634;\n"
	"	<I635>               = 635;\n"
	"	<I636>               = 636;\n"
	"	<I637>               = 637;\n"
	"	<I638>               = 638;\n"
	"	<I639>               = 639;\n"
	"	<I640>               = 640;\n"
	"	<I641>               = 641;\n"
	"	<I642>               = 642;\n"
	"	<I643>               = 643;\n"
	"	<I644>               = 644;\n"
	"	<I645>               = 645;\n"
	"	<I646>               = 646;\n"
	"	<I647>               = 647;\n"
	"	<I648>               = 648;\n"
	"	<I649>               = 649;\n"
	"	<I650>               = 650;\n"
	"	<I651>               = 651;\n"
	"	<I652>               = 652;\n"
	"	<I653>               = 653;\n"
	"	<I654>               = 654;\n"
	"	<I655>               = 655;\n"
	"	<I656>               = 656;\n"
	"	<I657>               = 657;\n"
	"	<I664>               = 664;\n"
	"	<I665>               = 665;\n"
	"	<I666>               = 666;\n"
	"	<I667>               = 667;\n"
	"	<I668>               = 668;\n"
	"	<I669>               = 669;\n"
	"	<I670>               = 670;\n"
	"	<I671>               = 671;\n"
	"	<I672>               = 672;\n"
	"	<I673>               = 673;\n"
	"	<I674>               = 674;\n"
	"	<I675>               = 675;\n"
	"	<I676>               = 676;\n"
	"	<I677>               = 677;\n"
	"	<I678>               = 678;\n"
	"	<I679>               = 679;\n"
	"	<I680>               = 680;\n"
	"	<I681>               = 681;\n"
	"	<I682>               = 682;\n"
	"	<I683>               = 683;\n"
	"	<I684>               = 684;\n"
	"	<I685>               = 685;\n"
	"	<I686>               = 686;\n"
	"	<I687>               = 687;\n"
	"	<I688>               = 688;\n"
	"	<I689>               = 689;\n"
	"	<I690>               = 690;\n"
	"	<I691>               = 691;\n"
	"	<I692>               = 692;\n"
	"	<I693>               = 693;\n"
	"	<I696>               = 696;\n"
	"	<I697>               = 697;\n"
	"	<I698>               = 698;\n"
	"	<I699>               = 699;\n"
	"	<I700>               = 700;\n"
	"	<I701>               = 701;\n"
	"	<I704>               = 704;\n"
	"	<I705>               = 705;\n"
	"	<I706>               = 706;\n"
	"	<I707>               = 707;\n"
	"	<I708>               = 708;\n"
	"	<I709>               = 709;\n"
	"	indicator 1 = \"Caps Lock\";\n"
	"	indicator 2 = \"Num Lock\";\n"
	"	indicator 3 = \"Scroll Lock\";\n"
	"	indicator 4 = \"Compose\";\n"
	"	indicator 5 = \"Kana\";\n"
	"	indicator 6 = \"Sleep\";\n"
	"	indicator 7 = \"Suspend\";\n"
	"	indicator 8 = \"Mute\";\n"
	"	indicator 9 = \"Misc\";\n"
	"	indicator 10 = \"Mail\";\n"
	"	indicator 11 = \"Charging\";\n"
	"	indicator 12 = \"Shift Lock\";\n"
	"	indicator 13 = \"Group 2\";\n"
	"	indicator 14 = \"Mouse Keys\";\n"
	"	alias <AC12>         = <BKSL>;\n"
	"	alias <ALGR>         = <RALT>;\n"
	"	alias <MENU>         = <COMP>;\n"
	"	alias <HZTG>         = <TLDE>;\n"
	"	alias <LMTA>         = <LWIN>;\n"
	"	alias <RMTA>         = <RWIN>;\n"
	"	alias <OUTP>         = <I235>;\n"
	"	alias <KITG>         = <I236>;\n"
	"	alias <KIDN>         = <I237>;\n"
	"	alias <KIUP>         = <I238>;\n"
	"	alias <I121>         = <MUTE>;\n"
	"	alias <I122>         = <VOL->;\n"
	"	alias <I123>         = <VOL+>;\n"
	"	alias <I124>         = <POWR>;\n"
	"	alias <I125>         = <KPEQ>;\n"
	"	alias <I127>         = <PAUS>;\n"
	"	alias <I130>         = <HNGL>;\n"
	"	alias <I131>         = <HJCV>;\n"
	"	alias <I132>         = <AE13>;\n"
	"	alias <I133>         = <LWIN>;\n"
	"	alias <I134>         = <RWIN>;\n"
	"	alias <I135>         = <COMP>;\n"
	"	alias <I136>         = <STOP>;\n"
	"	alias <I137>         = <AGAI>;\n"
	"	alias <I138>         = <PROP>;\n"
	"	alias <I139>         = <UNDO>;\n"
	"	alias <I140>         = <FRNT>;\n"
	"	alias <I141>         = <COPY>;\n"
	"	alias <I142>         = <OPEN>;\n"
	"	alias <I143>         = <PAST>;\n"
	"	alias <I144>         = <FIND>;\n"
	"	alias <I145>         = <CUT>;\n"
	"	alias <I146>         = <HELP>;\n"
	"	alias <I191>         = <FK13>;\n"
	"	alias <I192>         = <FK14>;\n"
	"	alias <I193>         = <FK15>;\n"
	"	alias <I194>         = <FK16>;\n"
	"	alias <I195>         = <FK17>;\n"
	"	alias <I196>         = <FK18>;\n"
	"	alias <I197>         = <FK19>;\n"
	"	alias <I198>         = <FK20>;\n"
	"	alias <I199>         = <FK21>;\n"
	"	alias <I200>         = <FK22>;\n"
	"	alias <I201>         = <FK23>;\n"
	"	alias <I202>         = <FK24>;\n"
	"	alias <MDSW>         = <LVL5>;\n"
	"	alias <KPPT>         = <I129>;\n"
	"	alias <LatQ>         = <AD01>;\n"
	"	alias <LatW>         = <AD02>;\n"
	"	alias <LatE>         = <AD03>;\n"
	"	alias <LatR>         = <AD04>;\n"
	"	alias <LatT>         = <AD05>;\n"
	"	alias <LatY>         = <AD06>;\n"
	"	alias <LatU>         = <AD07>;\n"
	"	alias <LatI>         = <AD08>;\n"
	"	alias <LatO>         = <AD09>;\n"
	"	alias <LatP>         = <AD10>;\n"
	"	alias <LatA>         = <AC01>;\n"
	"	alias <LatS>         = <AC02>;\n"
	"	alias <LatD>         = <AC03>;\n"
	"	alias <LatF>         = <AC04>;\n"
	"	alias <LatG>         = <AC05>;\n"
	"	alias <LatH>         = <AC06>;\n"
	"	alias <LatJ>         = <AC07>;\n"
	"	alias <LatK>         = <AC08>;\n"
	"	alias <LatL>         = <AC09>;\n"
	"	alias <LatZ>         = <AB01>;\n"
	"	alias <LatX>         = <AB02>;\n"
	"	alias <LatC>         = <AB03>;\n"
	"	alias <LatV>         = <AB04>;\n"
	"	alias <LatB>         = <AB05>;\n"
	"	alias <LatN>         = <AB06>;\n"
	"	alias <LatM>         = <AB07>;\n"
	"};\n"
	"\n"
	"xkb_types \"complete\" {\n"
	"	virtual_modifiers NumLock,Alt,LevelThree,Super,LevelFive,Meta,Hyper=0x4000,ScrollLock=0x8000;\n"
	"\n"
	"	type \"ONE_LEVEL\" {\n"
	"		modifiers= none;\n"
	"		level_name[1]= \"Any\";\n"
	"	};\n"
	"	type \"TWO_LEVEL\" {\n"
	"		modifiers= Shift;\n"
	"		map[Shift]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"	};\n"
	"	type \"ALPHABETIC\" {\n"
	"		modifiers= Shift+Lock;\n"
	"		map[Shift]= 2;\n"
	"		map[Lock]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Caps\";\n"
	"	};\n"
	"	type \"PC_ALT_LEVEL2\" {\n"
	"		modifiers= Alt;\n"
	"		map[Alt]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Alt\";\n"
	"	};\n"
	"	type \"PC_SUPER_LEVEL2\" {\n"
	"		modifiers= Super;\n"
	"		map[Super]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Super\";\n"
	"	};\n"
	"	type \"PC_SHIFT_SUPER_LEVEL2\" {\n"
	"		modifiers= Shift+Super;\n"
	"		map[Shift+Super]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Super\";\n"
	"	};\n"
	"	type \"PC_CONTROL_LEVEL2\" {\n"
	"		modifiers= Control;\n"
	"		map[Control]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Control\";\n"
	"	};\n"
	"	type \"PC_CONTROL_SUPER_LEVEL2\" {\n"
	"		modifiers= Control+Super;\n"
	"		map[Control+Super]= 2;\n"
	"		map[Control]= 1;\n"
	"		preserve[Control]= Control;\n"
	"		map[Super]= 1;\n"
	"		preserve[Super]= Super;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Control + Super\";\n"
	"	};\n"
	"	type \"CTRL+ALT\" {\n"
	"		modifiers= Shift+Control+Alt+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		preserve[Shift]= Shift;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		preserve[Shift+LevelThree]= Shift;\n"
	"		map[Control]= 1;\n"
	"		preserve[Control]= Control;\n"
	"		map[Shift+Control]= 2;\n"
	"		preserve[Shift+Control]= Shift+Control;\n"
	"		map[Control+LevelThree]= 3;\n"
	"		preserve[Control+LevelThree]= Control;\n"
	"		map[Shift+Control+LevelThree]= 4;\n"
	"		preserve[Shift+Control+LevelThree]= Shift+Control;\n"
	"		map[Alt]= 1;\n"
	"		preserve[Alt]= Alt;\n"
	"		map[Shift+Alt]= 2;\n"
	"		preserve[Shift+Alt]= Shift+Alt;\n"
	"		map[Alt+LevelThree]= 3;\n"
	"		preserve[Alt+LevelThree]= Alt;\n"
	"		map[Shift+Alt+LevelThree]= 4;\n"
	"		preserve[Shift+Alt+LevelThree]= Shift+Alt;\n"
	"		map[Control+Alt]= 5;\n"
	"		map[Shift+Control+Alt]= 2;\n"
	"		preserve[Shift+Control+Alt]= Shift+Control+Alt;\n"
	"		map[Control+Alt+LevelThree]= 3;\n"
	"		preserve[Control+Alt+LevelThree]= Control+Alt;\n"
	"		map[Shift+Control+Alt+LevelThree]= 4;\n"
	"		preserve[Shift+Control+Alt+LevelThree]= Shift+Control+Alt;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"		level_name[5]= \"Ctrl+Alt\";\n"
	"	};\n"
	"	type \"THREE_LEVEL\" {\n"
	"		modifiers= Shift+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 3;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"Level3\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL\" {\n"
	"		modifiers= Shift+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL_ALPHABETIC\" {\n"
	"		modifiers= Shift+Lock+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[Lock]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[Lock+LevelThree]= 4;\n"
	"		map[Shift+Lock+LevelThree]= 3;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL_SEMIALPHABETIC\" {\n"
	"		modifiers= Shift+Lock+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[Lock]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[Lock+LevelThree]= 3;\n"
	"		preserve[Lock+LevelThree]= Lock;\n"
	"		map[Shift+Lock+LevelThree]= 4;\n"
	"		preserve[Shift+Lock+LevelThree]= Lock;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL_KEYPAD\" {\n"
	"		modifiers= Shift+NumLock+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[NumLock]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[NumLock+LevelThree]= 4;\n"
	"		map[Shift+NumLock+LevelThree]= 3;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift/Numlock\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift/Numlock AltGr\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL_MIXED_KEYPAD\" {\n"
	"		modifiers= Shift+NumLock+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[NumLock]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[NumLock+LevelThree]= 3;\n"
	"		map[Shift+NumLock+LevelThree]= 4;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Number\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL_LOCKABLE_LEVEL2\" {\n"
	"		modifiers= Shift+LevelThree+LevelFive;\n"
	"		map[Shift]= 2;\n"
	"		map[LevelFive]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[LevelThree+LevelFive]= 3;\n"
	"		map[Shift+LevelThree+LevelFive]= 4;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Digit\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL_X\" {\n"
	"		modifiers= Shift+Control+Alt+LevelThree;\n"
	"		map[LevelThree]= 2;\n"
	"		map[Shift+LevelThree]= 3;\n"
	"		map[Control+Alt]= 4;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"AltGr\";\n"
	"		level_name[3]= \"Shift AltGr\";\n"
	"		level_name[4]= \"Ctrl+Alt\";\n"
	"	};\n"
	"	type \"SEPARATE_CAPS_AND_SHIFT_ALPHABETIC\" {\n"
	"		modifiers= Shift+Lock+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[Lock]= 4;\n"
	"		preserve[Lock]= Lock;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[Lock+LevelThree]= 3;\n"
	"		preserve[Lock+LevelThree]= Lock;\n"
	"		map[Shift+Lock+LevelThree]= 3;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Caps / Shift AltGr\";\n"
	"	};\n"
	"	type \"FOUR_LEVEL_PLUS_LOCK\" {\n"
	"		modifiers= Shift+Lock+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[Lock]= 5;\n"
	"		map[Shift+Lock]= 2;\n"
	"		map[Lock+LevelThree]= 3;\n"
	"		map[Shift+Lock+LevelThree]= 4;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"		level_name[5]= \"Lock\";\n"
	"	};\n"
	"	type \"EIGHT_LEVEL\" {\n"
	"		modifiers= Shift+LevelThree+LevelFive;\n"
	"		map[Shift]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[LevelFive]= 5;\n"
	"		map[Shift+LevelFive]= 6;\n"
	"		map[LevelThree+LevelFive]= 7;\n"
	"		map[Shift+LevelThree+LevelFive]= 8;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"		level_name[5]= \"X\";\n"
	"		level_name[6]= \"X Shift\";\n"
	"		level_name[7]= \"X AltGr\";\n"
	"		level_name[8]= \"X Shift AltGr\";\n"
	"	};\n"
	"	type \"EIGHT_LEVEL_ALPHABETIC\" {\n"
	"		modifiers= Shift+Lock+LevelThree+LevelFive;\n"
	"		map[Shift]= 2;\n"
	"		map[Lock]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[Lock+LevelThree]= 4;\n"
	"		map[Shift+Lock+LevelThree]= 3;\n"
	"		map[LevelFive]= 5;\n"
	"		map[Shift+LevelFive]= 6;\n"
	"		map[Lock+LevelFive]= 6;\n"
	"		map[Shift+Lock+LevelFive]= 5;\n"
	"		map[LevelThree+LevelFive]= 7;\n"
	"		map[Shift+LevelThree+LevelFive]= 8;\n"
	"		map[Lock+LevelThree+LevelFive]= 8;\n"
	"		map[Shift+Lock+LevelThree+LevelFive]= 7;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"		level_name[5]= \"X\";\n"
	"		level_name[6]= \"X Shift\";\n"
	"		level_name[7]= \"X AltGr\";\n"
	"		level_name[8]= \"X Shift AltGr\";\n"
	"	};\n"
	"	type \"EIGHT_LEVEL_SEMIALPHABETIC\" {\n"
	"		modifiers= Shift+Lock+LevelThree+LevelFive;\n"
	"		map[Shift]= 2;\n"
	"		map[Lock]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[Lock+LevelThree]= 3;\n"
	"		preserve[Lock+LevelThree]= Lock;\n"
	"		map[Shift+Lock+LevelThree]= 4;\n"
	"		preserve[Shift+Lock+LevelThree]= Lock;\n"
	"		map[LevelFive]= 5;\n"
	"		map[Shift+LevelFive]= 6;\n"
	"		map[Lock+LevelFive]= 6;\n"
	"		map[Shift+Lock+LevelFive]= 5;\n"
	"		map[LevelThree+LevelFive]= 7;\n"
	"		map[Shift+LevelThree+LevelFive]= 8;\n"
	"		map[Lock+LevelThree+LevelFive]= 7;\n"
	"		preserve[Lock+LevelThree+LevelFive]= Lock;\n"
	"		map[Shift+Lock+LevelThree+LevelFive]= 8;\n"
	"		preserve[Shift+Lock+LevelThree+LevelFive]= Lock;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"		level_name[5]= \"X\";\n"
	"		level_name[6]= \"X Shift\";\n"
	"		level_name[7]= \"X AltGr\";\n"
	"		level_name[8]= \"X Shift AltGr\";\n"
	"	};\n"
	"	type \"EIGHT_LEVEL_WITH_LEVEL5_LOCK\" {\n"
	"		modifiers= Shift+NumLock+LevelThree+LevelFive;\n"
	"		map[Shift]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[LevelFive]= 5;\n"
	"		map[Shift+LevelFive]= 6;\n"
	"		preserve[Shift+LevelFive]= Shift;\n"
	"		map[LevelThree+LevelFive]= 7;\n"
	"		map[Shift+LevelThree+LevelFive]= 8;\n"
	"		map[NumLock]= 5;\n"
	"		map[Shift+NumLock]= 6;\n"
	"		preserve[Shift+NumLock]= Shift;\n"
	"		map[NumLock+LevelThree]= 7;\n"
	"		map[Shift+NumLock+LevelThree]= 8;\n"
	"		map[Shift+NumLock+LevelFive]= 2;\n"
	"		map[NumLock+LevelThree+LevelFive]= 3;\n"
	"		map[Shift+NumLock+LevelThree+LevelFive]= 4;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"		level_name[5]= \"X\";\n"
	"		level_name[6]= \"X Shift\";\n"
	"		level_name[7]= \"X AltGr\";\n"
	"		level_name[8]= \"X Shift AltGr\";\n"
	"	};\n"
	"	type \"EIGHT_LEVEL_ALPHABETIC_WITH_LEVEL5_LOCK\" {\n"
	"		modifiers= Shift+Lock+NumLock+LevelThree+LevelFive;\n"
	"		map[Shift]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[LevelFive]= 5;\n"
	"		map[Shift+LevelFive]= 6;\n"
	"		preserve[Shift+LevelFive]= Shift;\n"
	"		map[LevelThree+LevelFive]= 7;\n"
	"		map[Shift+LevelThree+LevelFive]= 8;\n"
	"		map[NumLock]= 5;\n"
	"		map[Shift+NumLock]= 6;\n"
	"		preserve[Shift+NumLock]= Shift;\n"
	"		map[NumLock+LevelThree]= 7;\n"
	"		map[Shift+NumLock+LevelThree]= 8;\n"
	"		map[Shift+NumLock+LevelFive]= 2;\n"
	"		map[NumLock+LevelThree+LevelFive]= 3;\n"
	"		map[Shift+NumLock+LevelThree+LevelFive]= 4;\n"
	"		map[Lock]= 2;\n"
	"		map[Lock+LevelThree]= 3;\n"
	"		map[Shift+Lock+LevelThree]= 4;\n"
	"		map[Lock+LevelFive]= 5;\n"
	"		map[Shift+Lock+LevelFive]= 6;\n"
	"		map[Lock+LevelThree+LevelFive]= 7;\n"
	"		map[Shift+Lock+LevelThree+LevelFive]= 8;\n"
	"		map[Lock+NumLock]= 5;\n"
	"		map[Shift+Lock+NumLock]= 6;\n"
	"		map[Lock+NumLock+LevelThree]= 7;\n"
	"		map[Shift+Lock+NumLock+LevelThree]= 8;\n"
	"		map[Lock+NumLock+LevelFive]= 2;\n"
	"		map[Lock+NumLock+LevelThree+LevelFive]= 3;\n"
	"		map[Shift+Lock+NumLock+LevelThree+LevelFive]= 4;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"AltGr\";\n"
	"		level_name[4]= \"Shift AltGr\";\n"
	"		level_name[5]= \"X\";\n"
	"		level_name[6]= \"X Shift\";\n"
	"		level_name[7]= \"X AltGr\";\n"
	"		level_name[8]= \"X Shift AltGr\";\n"
	"	};\n"
	"	type \"EIGHT_LEVEL_BY_CTRL\" {\n"
	"		modifiers= Shift+Lock+Control+LevelThree;\n"
	"		map[Shift]= 2;\n"
	"		map[Lock]= 2;\n"
	"		map[LevelThree]= 3;\n"
	"		map[Shift+LevelThree]= 4;\n"
	"		map[Lock+LevelThree]= 4;\n"
	"		map[Shift+Lock+LevelThree]= 3;\n"
	"		map[Control]= 5;\n"
	"		map[Shift+Control]= 6;\n"
	"		map[Lock+Control]= 6;\n"
	"		map[Shift+Lock+Control]= 5;\n"
	"		map[Control+LevelThree]= 7;\n"
	"		map[Shift+Control+LevelThree]= 8;\n"
	"		map[Lock+Control+LevelThree]= 8;\n"
	"		map[Shift+Lock+Control+LevelThree]= 7;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift\";\n"
	"		level_name[3]= \"Level3\";\n"
	"		level_name[4]= \"Shift Level3\";\n"
	"		level_name[5]= \"Ctrl\";\n"
	"		level_name[6]= \"Shift Ctrl\";\n"
	"		level_name[7]= \"Level3 Ctrl\";\n"
	"		level_name[8]= \"Shift Level3 Ctrl\";\n"
	"	};\n"
	"	type \"KEYPAD\" {\n"
	"		modifiers= Shift+NumLock;\n"
	"		map[NumLock]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Number\";\n"
	"	};\n"
	"	type \"SHIFT+ALT\" {\n"
	"		modifiers= Shift+Alt;\n"
	"		map[Shift+Alt]= 2;\n"
	"		level_name[1]= \"Base\";\n"
	"		level_name[2]= \"Shift+Alt\";\n"
	"	};\n"
	"};\n"
	"\n"
	"xkb_compatibility \"complete\" {\n"
	"	virtual_modifiers NumLock,Alt,LevelThree,Super,LevelFive,Meta,Hyper=0x4000,ScrollLock=0x8000;\n"
	"\n"
	"	interpret.useModMapMods= AnyLevel;\n"
	"	interpret.repeat= False;\n"
	"	interpret ISO_Level2_Latch+Exactly(Shift) {\n"
	"		useModMapMods=level1;\n"
	"		action= LatchMods(modifiers=Shift,clearLocks,latchToLock);\n"
	"	};\n"
	"	interpret Shift_Lock+AnyOf(Shift+Lock) {\n"
	"		action= LockMods(modifiers=Shift);\n"
	"	};\n"
	"	interpret Num_Lock+AnyOf(all) {\n"
	"		virtualModifier= NumLock;\n"
	"		action= LockMods(modifiers=NumLock);\n"
	"	};\n"
	"	interpret ISO_Level3_Shift+AnyOf(all) {\n"
	"		virtualModifier= LevelThree;\n"
	"		useModMapMods=level1;\n"
	"		action= SetMods(modifiers=LevelThree,clearLocks);\n"
	"	};\n"
	"	interpret ISO_Level3_Latch+AnyOf(all) {\n"
	"		virtualModifier= LevelThree;\n"
	"		useModMapMods=level1;\n"
	"		action= LatchMods(modifiers=LevelThree,clearLocks,latchToLock);\n"
	"	};\n"
	"	interpret ISO_Level3_Lock+AnyOf(all) {\n"
	"		virtualModifier= LevelThree;\n"
	"		useModMapMods=level1;\n"
	"		action= LockMods(modifiers=LevelThree);\n"
	"	};\n"
	"	interpret Alt_L+AnyOf(all) {\n"
	"		virtualModifier= Alt;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Alt_R+AnyOf(all) {\n"
	"		virtualModifier= Alt;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Meta_L+AnyOf(all) {\n"
	"		virtualModifier= Meta;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Meta_R+AnyOf(all) {\n"
	"		virtualModifier= Meta;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Super_L+AnyOf(all) {\n"
	"		virtualModifier= Super;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Super_R+AnyOf(all) {\n"
	"		virtualModifier= Super;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Hyper_L+AnyOf(all) {\n"
	"		virtualModifier= Hyper;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Hyper_R+AnyOf(all) {\n"
	"		virtualModifier= Hyper;\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	interpret Scroll_Lock+AnyOf(all) {\n"
	"		virtualModifier= ScrollLock;\n"
	"		action= LockMods(modifiers=modMapMods);\n"
	"	};\n"
	"	interpret ISO_Level5_Shift+AnyOf(all) {\n"
	"		virtualModifier= LevelFive;\n"
	"		useModMapMods=level1;\n"
	"		action= SetMods(modifiers=LevelFive,clearLocks);\n"
	"	};\n"
	"	interpret ISO_Level5_Latch+AnyOf(all) {\n"
	"		virtualModifier= LevelFive;\n"
	"		useModMapMods=level1;\n"
	"		action= LatchMods(modifiers=LevelFive,clearLocks,latchToLock);\n"
	"	};\n"
	"	interpret ISO_Level5_Lock+AnyOf(all) {\n"
	"		virtualModifier= LevelFive;\n"
	"		useModMapMods=level1;\n"
	"		action= LockMods(modifiers=LevelFive);\n"
	"	};\n"
	"	interpret ISO_Group_Shift+AnyOfOrNone(all) {\n"
	"		action= SetGroup(group=+1);\n"
	"	};\n"
	"	interpret ISO_Level3_Shift+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=LevelThree,clearLocks);\n"
	"	};\n"
	"	interpret ISO_Level3_Latch+AnyOfOrNone(all) {\n"
	"		action= LatchMods(modifiers=LevelThree,clearLocks,latchToLock);\n"
	"	};\n"
	"	interpret ISO_Level3_Lock+AnyOfOrNone(all) {\n"
	"		action= LockMods(modifiers=LevelThree);\n"
	"	};\n"
	"	interpret ISO_Group_Latch+AnyOfOrNone(all) {\n"
	"		action= LatchGroup(group=2);\n"
	"	};\n"
	"	interpret ISO_Next_Group+AnyOfOrNone(all) {\n"
	"		action= LockGroup(group=+1);\n"
	"	};\n"
	"	interpret ISO_Prev_Group+AnyOfOrNone(all) {\n"
	"		action= LockGroup(group=-1);\n"
	"	};\n"
	"	interpret ISO_First_Group+AnyOfOrNone(all) {\n"
	"		action= LockGroup(group=1);\n"
	"	};\n"
	"	interpret ISO_Last_Group+AnyOfOrNone(all) {\n"
	"		action= LockGroup(group=2);\n"
	"	};\n"
	"	interpret KP_1+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=+1);\n"
	"	};\n"
	"	interpret KP_End+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=+1);\n"
	"	};\n"
	"	interpret KP_2+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+0,y=+1);\n"
	"	};\n"
	"	interpret KP_Down+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+0,y=+1);\n"
	"	};\n"
	"	interpret KP_3+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=+1);\n"
	"	};\n"
	"	interpret KP_Next+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=+1);\n"
	"	};\n"
	"	interpret KP_4+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=+0);\n"
	"	};\n"
	"	interpret KP_Left+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=+0);\n"
	"	};\n"
	"	interpret KP_6+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=+0);\n"
	"	};\n"
	"	interpret KP_Right+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=+0);\n"
	"	};\n"
	"	interpret KP_7+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=-1);\n"
	"	};\n"
	"	interpret KP_Home+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=-1);\n"
	"	};\n"
	"	interpret KP_8+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+0,y=-1);\n"
	"	};\n"
	"	interpret KP_Up+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+0,y=-1);\n"
	"	};\n"
	"	interpret KP_9+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=-1);\n"
	"	};\n"
	"	interpret KP_Prior+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=-1);\n"
	"	};\n"
	"	interpret KP_5+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= PtrBtn(button=default);\n"
	"	};\n"
	"	interpret KP_Begin+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= PtrBtn(button=default);\n"
	"	};\n"
	"	interpret KP_F2+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=1);\n"
	"	};\n"
	"	interpret KP_Divide+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=1);\n"
	"	};\n"
	"	interpret KP_F3+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=2);\n"
	"	};\n"
	"	interpret KP_Multiply+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=2);\n"
	"	};\n"
	"	interpret KP_F4+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=3);\n"
	"	};\n"
	"	interpret KP_Subtract+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=3);\n"
	"	};\n"
	"	interpret KP_Separator+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= PtrBtn(button=default,count=2);\n"
	"	};\n"
	"	interpret KP_Add+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= PtrBtn(button=default,count=2);\n"
	"	};\n"
	"	interpret KP_0+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= LockPtrBtn(button=default,affect=lock);\n"
	"	};\n"
	"	interpret KP_Insert+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= LockPtrBtn(button=default,affect=lock);\n"
	"	};\n"
	"	interpret KP_Decimal+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= LockPtrBtn(button=default,affect=unlock);\n"
	"	};\n"
	"	interpret KP_Delete+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= LockPtrBtn(button=default,affect=unlock);\n"
	"	};\n"
	"	interpret F25+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=1);\n"
	"	};\n"
	"	interpret F26+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SetPtrDflt(affect=button,button=2);\n"
	"	};\n"
	"	interpret F27+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=-1);\n"
	"	};\n"
	"	interpret F29+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=-1);\n"
	"	};\n"
	"	interpret F31+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= PtrBtn(button=default);\n"
	"	};\n"
	"	interpret F33+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=-1,y=+1);\n"
	"	};\n"
	"	interpret F35+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= MovePtr(x=+1,y=+1);\n"
	"	};\n"
	"	interpret Pointer_Button_Dflt+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=default);\n"
	"	};\n"
	"	interpret Pointer_Button1+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=1);\n"
	"	};\n"
	"	interpret Pointer_Button2+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=2);\n"
	"	};\n"
	"	interpret Pointer_Button3+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=3);\n"
	"	};\n"
	"	interpret Pointer_DblClick_Dflt+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=default,count=2);\n"
	"	};\n"
	"	interpret Pointer_DblClick1+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=1,count=2);\n"
	"	};\n"
	"	interpret Pointer_DblClick2+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=2,count=2);\n"
	"	};\n"
	"	interpret Pointer_DblClick3+AnyOfOrNone(all) {\n"
	"		action= PtrBtn(button=3,count=2);\n"
	"	};\n"
	"	interpret Pointer_Drag_Dflt+AnyOfOrNone(all) {\n"
	"		action= LockPtrBtn(button=default,affect=both);\n"
	"	};\n"
	"	interpret Pointer_Drag1+AnyOfOrNone(all) {\n"
	"		action= LockPtrBtn(button=1,affect=both);\n"
	"	};\n"
	"	interpret Pointer_Drag2+AnyOfOrNone(all) {\n"
	"		action= LockPtrBtn(button=2,affect=both);\n"
	"	};\n"
	"	interpret Pointer_Drag3+AnyOfOrNone(all) {\n"
	"		action= LockPtrBtn(button=3,affect=both);\n"
	"	};\n"
	"	interpret Pointer_EnableKeys+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=MouseKeys);\n"
	"	};\n"
	"	interpret Pointer_Accelerate+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=MouseKeysAccel);\n"
	"	};\n"
	"	interpret Pointer_DfltBtnNext+AnyOfOrNone(all) {\n"
	"		action= SetPtrDflt(affect=button,button=+1);\n"
	"	};\n"
	"	interpret Pointer_DfltBtnPrev+AnyOfOrNone(all) {\n"
	"		action= SetPtrDflt(affect=button,button=-1);\n"
	"	};\n"
	"	interpret AccessX_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=AccessXKeys);\n"
	"	};\n"
	"	interpret AccessX_Feedback_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=AccessXFeedback);\n"
	"	};\n"
	"	interpret RepeatKeys_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=RepeatKeys);\n"
	"	};\n"
	"	interpret SlowKeys_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=SlowKeys);\n"
	"	};\n"
	"	interpret BounceKeys_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=BounceKeys);\n"
	"	};\n"
	"	interpret StickyKeys_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=StickyKeys);\n"
	"	};\n"
	"	interpret MouseKeys_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=MouseKeys);\n"
	"	};\n"
	"	interpret MouseKeys_Accel_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=MouseKeysAccel);\n"
	"	};\n"
	"	interpret Overlay1_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=none);\n"
	"	};\n"
	"	interpret Overlay2_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=none);\n"
	"	};\n"
	"	interpret AudibleBell_Enable+AnyOfOrNone(all) {\n"
	"		action= LockControls(controls=AudibleBell);\n"
	"	};\n"
	"	interpret Terminate_Server+AnyOfOrNone(all) {\n"
	"		action= Terminate();\n"
	"	};\n"
	"	interpret Alt_L+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Alt,clearLocks);\n"
	"	};\n"
	"	interpret Alt_R+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Alt,clearLocks);\n"
	"	};\n"
	"	interpret Meta_L+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Meta,clearLocks);\n"
	"	};\n"
	"	interpret Meta_R+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Meta,clearLocks);\n"
	"	};\n"
	"	interpret Super_L+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Super,clearLocks);\n"
	"	};\n"
	"	interpret Super_R+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Super,clearLocks);\n"
	"	};\n"
	"	interpret Hyper_L+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Hyper,clearLocks);\n"
	"	};\n"
	"	interpret Hyper_R+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Hyper,clearLocks);\n"
	"	};\n"
	"	interpret Shift_L+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Shift,clearLocks);\n"
	"	};\n"
	"	interpret Shift_R+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=Shift,clearLocks);\n"
	"	};\n"
	"	interpret XF86Switch_VT_1+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=1,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_2+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=2,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_3+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=3,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_4+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=4,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_5+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=5,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_6+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=6,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_7+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=7,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_8+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=8,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_9+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=9,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_10+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=10,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_11+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=11,!same);\n"
	"	};\n"
	"	interpret XF86Switch_VT_12+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= SwitchScreen(screen=12,!same);\n"
	"	};\n"
	"	interpret XF86LogGrabInfo+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= Private(type=0x86,data[0]=0x50,data[1]=0x72,data[2]=0x47,data[3]=0x72,data[4]=0x62,data[5]=0x73,data[6]=0x00);\n"
	"	};\n"
	"	interpret XF86LogWindowTree+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= Private(type=0x86,data[0]=0x50,data[1]=0x72,data[2]=0x57,data[3]=0x69,data[4]=0x6e,data[5]=0x73,data[6]=0x00);\n"
	"	};\n"
	"	interpret XF86Next_VMode+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= Private(type=0x86,data[0]=0x2b,data[1]=0x56,data[2]=0x4d,data[3]=0x6f,data[4]=0x64,data[5]=0x65,data[6]=0x00);\n"
	"	};\n"
	"	interpret XF86Prev_VMode+AnyOfOrNone(all) {\n"
	"		repeat= True;\n"
	"		action= Private(type=0x86,data[0]=0x2d,data[1]=0x56,data[2]=0x4d,data[3]=0x6f,data[4]=0x64,data[5]=0x65,data[6]=0x00);\n"
	"	};\n"
	"	interpret ISO_Level5_Shift+AnyOfOrNone(all) {\n"
	"		action= SetMods(modifiers=LevelFive,clearLocks);\n"
	"	};\n"
	"	interpret ISO_Level5_Latch+AnyOfOrNone(all) {\n"
	"		action= LatchMods(modifiers=LevelFive,clearLocks,latchToLock);\n"
	"	};\n"
	"	interpret ISO_Level5_Lock+AnyOfOrNone(all) {\n"
	"		action= LockMods(modifiers=LevelFive);\n"
	"	};\n"
	"	interpret Caps_Lock+AnyOfOrNone(all) {\n"
	"		action= LockMods(modifiers=Lock);\n"
	"	};\n"
	"	interpret Any+Exactly(Lock) {\n"
	"		action= LockMods(modifiers=Lock);\n"
	"	};\n"
	"	interpret Any+AnyOf(all) {\n"
	"		action= SetMods(modifiers=modMapMods,clearLocks);\n"
	"	};\n"
	"	indicator \"Caps Lock\" {\n"
	"		whichModState= locked;\n"
	"		modifiers= Lock;\n"
	"	};\n"
	"	indicator \"Num Lock\" {\n"
	"		whichModState= locked;\n"
	"		modifiers= NumLock;\n"
	"	};\n"
	"	indicator \"Scroll Lock\" {\n"
	"		whichModState= locked;\n"
	"		modifiers= ScrollLock;\n"
	"	};\n"
	"	indicator \"Shift Lock\" {\n"
	"		whichModState= locked;\n"
	"		modifiers= Shift;\n"
	"	};\n"
	"	indicator \"Group 2\" {\n"
	"		groups= 0xfffffffe;\n"
	"	};\n"
	"	indicator \"Mouse Keys\" {\n"
	"		controls= MouseKeys;\n"
	"	};\n"
	"};\n"
	"\n"
	"xkb_symbols \"pc_us_inet(evdev)\" {\n"
	"	name[1]=\"English (US)\";\n"
	"\n"
	"	key <ESC>                {	[          Escape ] };\n"
	"	key <AE01>               {	[               1,          exclam ] };\n"
	"	key <AE02>               {	[               2,              at ] };\n"
	"	key <AE03>               {	[               3,      numbersign ] };\n"
	"	key <AE04>               {	[               4,          dollar ] };\n"
	"	key <AE05>               {	[               5,         percent ] };\n"
	"	key <AE06>               {	[               6,     asciicircum ] };\n"
	"	key <AE07>               {	[               7,       ampersand ] };\n"
	"	key <AE08>               {	[               8,        asterisk ] };\n"
	"	key <AE09>               {	[               9,       parenleft ] };\n"
	"	key <AE10>               {	[               0,      parenright ] };\n"
	"	key <AE11>               {	[           minus,      underscore ] };\n"
	"	key <AE12>               {	[           equal,            plus ] };\n"
	"	key <BKSP>               {	[       BackSpace,       BackSpace ] };\n"
	"	key <TAB>                {	[             Tab,    ISO_Left_Tab ] };\n"
	"	key <AD01>               {	[               q,               Q ] };\n"
	"	key <AD02>               {	[               w,               W ] };\n"
	"	key <AD03>               {	[               e,               E ] };\n"
	"	key <AD04>               {	[               r,               R ] };\n"
	"	key <AD05>               {	[               t,               T ] };\n"
	"	key <AD06>               {	[               y,               Y ] };\n"
	"	key <AD07>               {	[               u,               U ] };\n"
	"	key <AD08>               {	[               i,               I ] };\n"
	"	key <AD09>               {	[               o,               O ] };\n"
	"	key <AD10>               {	[               p,               P ] };\n"
	"	key <AD11>               {	[     bracketleft,       braceleft ] };\n"
	"	key <AD12>               {	[    bracketright,      braceright ] };\n"
	"	key <RTRN>               {	[          Return ] };\n"
	"	key <LCTL>               {	[       Control_L ] };\n"
	"	key <AC01>               {	[               a,               A ] };\n"
	"	key <AC02>               {	[               s,               S ] };\n"
	"	key <AC03>               {	[               d,               D ] };\n"
	"	key <AC04>               {	[               f,               F ] };\n"
	"	key <AC05>               {	[               g,               G ] };\n"
	"	key <AC06>               {	[               h,               H ] };\n"
	"	key <AC07>               {	[               j,               J ] };\n"
	"	key <AC08>               {	[               k,               K ] };\n"
	"	key <AC09>               {	[               l,               L ] };\n"
	"	key <AC10>               {	[       semicolon,           colon ] };\n"
	"	key <AC11>               {	[      apostrophe,        quotedbl ] };\n"
	"	key <TLDE>               {	[           grave,      asciitilde ] };\n"
	"	key <LFSH>               {	[         Shift_L ] };\n"
	"	key <BKSL>               {	[       backslash,             bar ] };\n"
	"	key <AB01>               {	[               z,               Z ] };\n"
	"	key <AB02>               {	[               x,               X ] };\n"
	"	key <AB03>               {	[               c,               C ] };\n"
	"	key <AB04>               {	[               v,               V ] };\n"
	"	key <AB05>               {	[               b,               B ] };\n"
	"	key <AB06>               {	[               n,               N ] };\n"
	"	key <AB07>               {	[               m,               M ] };\n"
	"	key <AB08>               {	[           comma,            less ] };\n"
	"	key <AB09>               {	[          period,         greater ] };\n"
	"	key <AB10>               {	[           slash,        question ] };\n"
	"	key <RTSH>               {	[         Shift_R ] };\n"
	"	key <KPMU>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [     KP_Multiply,     KP_Multiply,     KP_Multiply,     KP_Multiply,   XF86ClearGrab ]\n"
	"	};\n"
	"	key <LALT>               {	[           Alt_L ] };\n"
	"	key <SPCE>               {	[           space ] };\n"
	"	key <CAPS>               {	[       Caps_Lock ] };\n"
	"	key <FK01>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F1,              F1,              F1,              F1, XF86Switch_VT_1 ]\n"
	"	};\n"
	"	key <FK02>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F2,              F2,              F2,              F2, XF86Switch_VT_2 ]\n"
	"	};\n"
	"	key <FK03>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F3,              F3,              F3,              F3, XF86Switch_VT_3 ]\n"
	"	};\n"
	"	key <FK04>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F4,              F4,              F4,              F4, XF86Switch_VT_4 ]\n"
	"	};\n"
	"	key <FK05>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F5,              F5,              F5,              F5, XF86Switch_VT_5 ]\n"
	"	};\n"
	"	key <FK06>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F6,              F6,              F6,              F6, XF86Switch_VT_6 ]\n"
	"	};\n"
	"	key <FK07>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F7,              F7,              F7,              F7, XF86Switch_VT_7 ]\n"
	"	};\n"
	"	key <FK08>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F8,              F8,              F8,              F8, XF86Switch_VT_8 ]\n"
	"	};\n"
	"	key <FK09>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [              F9,              F9,              F9,              F9, XF86Switch_VT_9 ]\n"
	"	};\n"
	"	key <FK10>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [             F10,             F10,             F10,             F10, XF86Switch_VT_10 ]\n"
	"	};\n"
	"	key <NMLK>               {	[        Num_Lock ] };\n"
	"	key <SCLK>               {	[     Scroll_Lock ] };\n"
	"	key <KP7>                {	[         KP_Home,            KP_7 ] };\n"
	"	key <KP8>                {	[           KP_Up,            KP_8 ] };\n"
	"	key <KP9>                {	[        KP_Prior,            KP_9 ] };\n"
	"	key <KPSU>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [     KP_Subtract,     KP_Subtract,     KP_Subtract,     KP_Subtract,  XF86Prev_VMode ]\n"
	"	};\n"
	"	key <KP4>                {	[         KP_Left,            KP_4 ] };\n"
	"	key <KP5>                {	[        KP_Begin,            KP_5 ] };\n"
	"	key <KP6>                {	[        KP_Right,            KP_6 ] };\n"
	"	key <KPAD>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [          KP_Add,          KP_Add,          KP_Add,          KP_Add,  XF86Next_VMode ]\n"
	"	};\n"
	"	key <KP1>                {	[          KP_End,            KP_1 ] };\n"
	"	key <KP2>                {	[         KP_Down,            KP_2 ] };\n"
	"	key <KP3>                {	[         KP_Next,            KP_3 ] };\n"
	"	key <KP0>                {	[       KP_Insert,            KP_0 ] };\n"
	"	key <KPDL>               {	[       KP_Delete,      KP_Decimal ] };\n"
	"	key <LVL3>               {	[ ISO_Level3_Shift ] };\n"
	"	key <ZEHA>               {\n"
	"		type= \"PC_CONTROL_SUPER_LEVEL2\",\n"
	"		symbols[1]= [             F24, XF86TouchpadToggle ]\n"
	"	};\n"
	"	key <LSGT>               {	[            less,         greater,             bar,       brokenbar ] };\n"
	"	key <FK11>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [             F11,             F11,             F11,             F11, XF86Switch_VT_11 ]\n"
	"	};\n"
	"	key <FK12>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [             F12,             F12,             F12,             F12, XF86Switch_VT_12 ]\n"
	"	};\n"
	"	key <KATA>               {	[        Katakana ] };\n"
	"	key <HIRA>               {	[        Hiragana ] };\n"
	"	key <HENK>               {	[     Henkan_Mode ] };\n"
	"	key <HKTG>               {	[ Hiragana_Katakana ] };\n"
	"	key <MUHE>               {	[        Muhenkan ] };\n"
	"	key <KPEN>               {	[        KP_Enter ] };\n"
	"	key <RCTL>               {	[       Control_R ] };\n"
	"	key <KPDV>               {\n"
	"		type= \"CTRL+ALT\",\n"
	"		symbols[1]= [       KP_Divide,       KP_Divide,       KP_Divide,       KP_Divide,      XF86Ungrab ]\n"
	"	};\n"
	"	key <PRSC>               {\n"
	"		type= \"PC_ALT_LEVEL2\",\n"
	"		symbols[1]= [           Print,         Sys_Req ]\n"
	"	};\n"
	"	key <RALT>               {	[           Alt_R ] };\n"
	"	key <LNFD>               {	[        Linefeed ] };\n"
	"	key <HOME>               {	[            Home ] };\n"
	"	key <UP>                 {	[              Up ] };\n"
	"	key <PGUP>               {	[           Prior ] };\n"
	"	key <LEFT>               {	[            Left ] };\n"
	"	key <RGHT>               {	[           Right ] };\n"
	"	key <END>                {	[             End ] };\n"
	"	key <DOWN>               {	[            Down ] };\n"
	"	key <PGDN>               {	[            Next ] };\n"
	"	key <INS>                {	[          Insert ] };\n"
	"	key <DELE>               {	[          Delete ] };\n"
	"	key <MUTE>               {	[   XF86AudioMute ] };\n"
	"	key <VOL->               {	[ XF86AudioLowerVolume ] };\n"
	"	key <VOL+>               {	[ XF86AudioRaiseVolume ] };\n"
	"	key <POWR>               {	[    XF86PowerOff ] };\n"
	"	key <KPEQ>               {	[        KP_Equal ] };\n"
	"	key <I126>               {	[       plusminus ] };\n"
	"	key <PAUS>               {\n"
	"		type= \"PC_CONTROL_LEVEL2\",\n"
	"		symbols[1]= [           Pause,           Break ]\n"
	"	};\n"
	"	key <I128>               {	[     XF86LaunchA ] };\n"
	"	key <I129>               {	[      KP_Decimal,      KP_Decimal ] };\n"
	"	key <HNGL>               {	[          Hangul ] };\n"
	"	key <HJCV>               {	[    Hangul_Hanja ] };\n"
	"	key <LWIN>               {	[         Super_L ] };\n"
	"	key <RWIN>               {	[         Super_R ] };\n"
	"	key <COMP>               {	[            Menu ] };\n"
	"	key <STOP>               {	[          Cancel ] };\n"
	"	key <AGAI>               {	[            Redo ] };\n"
	"	key <PROP>               {	[        SunProps ] };\n"
	"	key <UNDO>               {	[            Undo ] };\n"
	"	key <FRNT>               {	[        SunFront ] };\n"
	"	key <COPY>               {	[        XF86Copy ] };\n"
	"	key <OPEN>               {	[        XF86Open ] };\n"
	"	key <PAST>               {	[       XF86Paste ] };\n"
	"	key <FIND>               {	[            Find ] };\n"
	"	key <CUT>                {	[         XF86Cut ] };\n"
	"	key <HELP>               {	[            Help ] };\n"
	"	key <I147>               {	[      XF86MenuKB ] };\n"
	"	key <I148>               {	[  XF86Calculator ] };\n"
	"	key <I150>               {	[       XF86Sleep ] };\n"
	"	key <I151>               {	[      XF86WakeUp ] };\n"
	"	key <I152>               {	[    XF86Explorer ] };\n"
	"	key <I153>               {	[        XF86Send ] };\n"
	"	key <I155>               {	[        XF86Xfer ] };\n"
	"	key <I156>               {	[     XF86Launch1 ] };\n"
	"	key <I157>               {	[     XF86Launch2 ] };\n"
	"	key <I158>               {	[         XF86WWW ] };\n"
	"	key <I159>               {	[         XF86DOS ] };\n"
	"	key <I160>               {	[ XF86ScreenSaver ] };\n"
	"	key <I161>               {	[ XF86RotateWindows ] };\n"
	"	key <I162>               {	[    XF86TaskPane ] };\n"
	"	key <I163>               {	[        XF86Mail ] };\n"
	"	key <I164>               {	[   XF86Favorites ] };\n"
	"	key <I165>               {	[  XF86MyComputer ] };\n"
	"	key <I166>               {	[        XF86Back ] };\n"
	"	key <I167>               {	[     XF86Forward ] };\n"
	"	key <I169>               {	[       XF86Eject ] };\n"
	"	key <I170>               {	[       XF86Eject ] };\n"
	"	key <I171>               {	[   XF86AudioNext ] };\n"
	"	key <I172>               {	[   XF86AudioPlay,  XF86AudioPause ] };\n"
	"	key <I173>               {	[   XF86AudioPrev ] };\n"
	"	key <I174>               {	[   XF86AudioStop,       XF86Eject ] };\n"
	"	key <I175>               {	[ XF86AudioRecord ] };\n"
	"	key <I176>               {	[ XF86AudioRewind ] };\n"
	"	key <I177>               {	[       XF86Phone ] };\n"
	"	key <I179>               {	[       XF86Tools ] };\n"
	"	key <I180>               {	[    XF86HomePage ] };\n"
	"	key <I181>               {	[      XF86Reload ] };\n"
	"	key <I182>               {	[       XF86Close ] };\n"
	"	key <I185>               {	[    XF86ScrollUp ] };\n"
	"	key <I186>               {	[  XF86ScrollDown ] };\n"
	"	key <I187>               {	[       parenleft ] };\n"
	"	key <I188>               {	[      parenright ] };\n"
	"	key <I189>               {	[         XF86New ] };\n"
	"	key <I190>               {	[            Redo ] };\n"
	"	key <FK13>               {	[       XF86Tools ] };\n"
	"	key <FK14>               {	[     XF86Launch5 ] };\n"
	"	key <FK15>               {	[     XF86Launch6 ] };\n"
	"	key <FK16>               {	[     XF86Launch7 ] };\n"
	"	key <FK17>               {	[     XF86Launch8 ] };\n"
	"	key <FK18>               {	[     XF86Launch9 ] };\n"
	"	key <FK19>               {	[             F19 ] };\n"
	"	key <FK20>               {	[ XF86AudioMicMute ] };\n"
	"	key <FK21>               {	[ XF86TouchpadToggle ] };\n"
	"	key <FK22>               {	[  XF86TouchpadOn ] };\n"
	"	key <FK23>               {\n"
	"		type= \"PC_SHIFT_SUPER_LEVEL2\",\n"
	"		symbols[1]= [             F23,   XF86Assistant ]\n"
	"	};\n"
	"	key <FK24>               {\n"
	"		type= \"PC_CONTROL_SUPER_LEVEL2\",\n"
	"		symbols[1]= [             F24, XF86TouchpadToggle ]\n"
	"	};\n"
	"	key <LVL5>               {	[ ISO_Level5_Shift ] };\n"
	"	key <ALT>                {	[        NoSymbol,           Alt_L ] };\n"
	"	key <META>               {	[        NoSymbol,          Meta_L ] };\n"
	"	key <SUPR>               {	[        NoSymbol,         Super_L ] };\n"
	"	key <HYPR>               {	[        NoSymbol,         Hyper_L ] };\n"
	"	key <I208>               {	[   XF86AudioPlay ] };\n"
	"	key <I209>               {	[  XF86AudioPause ] };\n"
	"	key <I210>               {	[     XF86Launch3 ] };\n"
	"	key <I211>               {	[     XF86Launch4 ] };\n"
	"	key <I212>               {	[     XF86LaunchB ] };\n"
	"	key <I213>               {	[     XF86Suspend ] };\n"
	"	key <I214>               {	[       XF86Close ] };\n"
	"	key <I215>               {	[   XF86AudioPlay ] };\n"
	"	key <I216>               {	[ XF86AudioForward ] };\n"
	"	key <I217>               {	[ XF86AudioBassBoost ] };\n"
	"	key <I218>               {	[           Print ] };\n"
	"	key <I220>               {	[      XF86WebCam ] };\n"
	"	key <I221>               {	[ XF86AudioPreset ] };\n"
	"	key <I223>               {	[        XF86Mail ] };\n"
	"	key <I224>               {	[   XF86Messenger ] };\n"
	"	key <I225>               {	[      XF86Search ] };\n"
	"	key <I226>               {	[          XF86Go ] };\n"
	"	key <I227>               {	[     XF86Finance ] };\n"
	"	key <I228>               {	[        XF86Game ] };\n"
	"	key <I229>               {	[        XF86Shop ] };\n"
	"	key <I231>               {	[          Cancel ] };\n"
	"	key <I232>               {	[ XF86MonBrightnessDown ] };\n"
	"	key <I233>               {	[ XF86MonBrightnessUp ] };\n"
	"	key <I234>               {	[  XF86AudioMedia ] };\n"
	"	key <I235>               {	[     XF86Display ] };\n"
	"	key <I236>               {	[ XF86KbdLightOnOff ] };\n"
	"	key <I237>               {	[ XF86KbdBrightnessDown ] };\n"
	"	key <I238>               {	[ XF86KbdBrightnessUp ] };\n"
	"	key <I239>               {	[        XF86Send ] };\n"
	"	key <I240>               {	[       XF86Reply ] };\n"
	"	key <I241>               {	[ XF86MailForward ] };\n"
	"	key <I242>               {	[        XF86Save ] };\n"
	"	key <I243>               {	[   XF86Documents ] };\n"
	"	key <I244>               {	[     XF86Battery ] };\n"
	"	key <I245>               {	[   XF86Bluetooth ] };\n"
	"	key <I246>               {	[        XF86WLAN ] };\n"
	"	key <I247>               {	[         XF86UWB ] };\n"
	"	key <I249>               {	[  XF86Next_VMode ] };\n"
	"	key <I250>               {	[  XF86Prev_VMode ] };\n"
	"	key <I251>               {	[ XF86MonBrightnessCycle ] };\n"
	"	key <I252>               {	[ XF86BrightnessAuto ] };\n"
	"	key <I253>               {	[  XF86DisplayOff ] };\n"
	"	key <I254>               {	[        XF86WWAN ] };\n"
	"	key <I255>               {	[      XF86RFKill ] };\n"
	"	key <I256>               {	[ XF86AudioMicMute ] };\n"
	"	key <I360>               {	[          XF86OK ] };\n"
	"	key <I361>               {	[      XF86Select ] };\n"
	"	key <I362>               {	[        XF86GoTo ] };\n"
	"	key <I363>               {	[       XF86Clear ] };\n"
	"	key <I365>               {	[      XF86Option ] };\n"
	"	key <I366>               {	[        XF86Info ] };\n"
	"	key <I367>               {	[        XF86Time ] };\n"
	"	key <I368>               {	[  XF86VendorLogo ] };\n"
	"	key <I370>               {	[ XF86MediaSelectProgramGuide ] };\n"
	"	key <I371>               {	[ XF86NextFavorite ] };\n"
	"	key <I372>               {	[   XF86Favorites ] };\n"
	"	key <I373>               {	[ XF86MediaSelectProgramGuide ] };\n"
	"	key <I374>               {	[ XF86MediaSelectHome ] };\n"
	"	key <I376>               {	[ XF86MediaLanguageMenu ] };\n"
	"	key <I377>               {	[ XF86MediaTitleMenu ] };\n"
	"	key <I378>               {	[    XF86Subtitle ] };\n"
	"	key <I379>               {	[  XF86CycleAngle ] };\n"
	"	key <I380>               {	[  XF86FullScreen ] };\n"
	"	key <I381>               {	[ XF86AudioChannelMode ] };\n"
	"	key <I382>               {	[    XF86Keyboard ] };\n"
	"	key <I383>               {	[ XF86AspectRatio ] };\n"
	"	key <I384>               {	[ XF86MediaSelectPC ] };\n"
	"	key <I385>               {	[ XF86MediaSelectTV ] };\n"
	"	key <I386>               {	[ XF86MediaSelectCable ] };\n"
	"	key <I387>               {	[ XF86MediaSelectVCR ] };\n"
	"	key <I388>               {	[ XF86MediaSelectVCRPlus ] };\n"
	"	key <I389>               {	[ XF86MediaSelectSatellite ] };\n"
	"	key <I391>               {	[          XF86CD ] };\n"
	"	key <I392>               {	[ XF86MediaSelectTape ] };\n"
	"	key <I393>               {	[ XF86MediaSelectRadio ] };\n"
	"	key <I394>               {	[ XF86MediaSelectTuner ] };\n"
	"	key <I395>               {	[ XF86MediaPlayer ] };\n"
	"	key <I396>               {	[ XF86MediaSelectTeletext ] };\n"
	"	key <I397>               {	[         XF86DVD ] };\n"
	"	key <I398>               {	[ XF86MediaSelectAuxiliary ] };\n"
	"	key <I400>               {	[       XF86Audio ] };\n"
	"	key <I401>               {	[       XF86Video ] };\n"
	"	key <I404>               {	[        XF86Memo ] };\n"
	"	key <I405>               {	[    XF86Calendar ] };\n"
	"	key <I406>               {	[         XF86Red ] };\n"
	"	key <I407>               {	[       XF86Green ] };\n"
	"	key <I408>               {	[      XF86Yellow ] };\n"
	"	key <I409>               {	[        XF86Blue ] };\n"
	"	key <I410>               {	[   XF86ChannelUp ] };\n"
	"	key <I411>               {	[ XF86ChannelDown ] };\n"
	"	key <I417>               {	[ XF86MediaPlaySlow ] };\n"
	"	key <I418>               {	[ XF86AudioRandomPlay ] };\n"
	"	key <I419>               {	[       XF86Break ] };\n"
	"	key <I421>               {	[ XF86NumberEntryMode ] };\n"
	"	key <I424>               {	[  XF86VideoPhone ] };\n"
	"	key <I425>               {	[        XF86Game ] };\n"
	"	key <I426>               {	[      XF86ZoomIn ] };\n"
	"	key <I427>               {	[     XF86ZoomOut ] };\n"
	"	key <I428>               {	[   XF86ZoomReset ] };\n"
	"	key <I429>               {	[        XF86Word ] };\n"
	"	key <I430>               {	[      XF86Editor ] };\n"
	"	key <I431>               {	[       XF86Excel ] };\n"
	"	key <I432>               {	[ XF86GraphicsEditor ] };\n"
	"	key <I433>               {	[ XF86Presentation ] };\n"
	"	key <I434>               {	[    XF86Database ] };\n"
	"	key <I435>               {	[        XF86News ] };\n"
	"	key <I436>               {	[   XF86Voicemail ] };\n"
	"	key <I437>               {	[ XF86Addressbook ] };\n"
	"	key <I438>               {	[   XF86Messenger ] };\n"
	"	key <I439>               {	[ XF86DisplayToggle ] };\n"
	"	key <I440>               {	[  XF86SpellCheck ] };\n"
	"	key <I441>               {	[      XF86LogOff ] };\n"
	"	key <I442>               {	[          dollar ] };\n"
	"	key <I443>               {	[        EuroSign ] };\n"
	"	key <I444>               {	[   XF86FrameBack ] };\n"
	"	key <I445>               {	[ XF86FrameForward ] };\n"
	"	key <I446>               {	[ XF86ContextMenu ] };\n"
	"	key <I447>               {	[ XF86MediaRepeat ] };\n"
	"	key <I448>               {	[ XF8610ChannelsUp ] };\n"
	"	key <I449>               {	[ XF8610ChannelsDown ] };\n"
	"	key <I450>               {	[      XF86Images ] };\n"
	"	key <I452>               {	[ XF86NotificationCenter ] };\n"
	"	key <I453>               {	[ XF86PickupPhone ] };\n"
	"	key <I454>               {	[ XF86HangupPhone ] };\n"
	"	key <I455>               {	[   XF86LinkPhone ] };\n"
	"	key <I472>               {	[          XF86Fn ] };\n"
	"	key <I473>               {	[      XF86Fn_Esc ] };\n"
	"	key <I474>               {	[       XF86Fn_F1 ] };\n"
	"	key <I475>               {	[       XF86Fn_F2 ] };\n"
	"	key <I476>               {	[       XF86Fn_F3 ] };\n"
	"	key <I477>               {	[       XF86Fn_F4 ] };\n"
	"	key <I478>               {	[       XF86Fn_F5 ] };\n"
	"	key <I479>               {	[       XF86Fn_F6 ] };\n"
	"	key <I480>               {	[       XF86Fn_F7 ] };\n"
	"	key <I481>               {	[       XF86Fn_F8 ] };\n"
	"	key <I482>               {	[       XF86Fn_F9 ] };\n"
	"	key <I483>               {	[      XF86Fn_F10 ] };\n"
	"	key <I484>               {	[      XF86Fn_F11 ] };\n"
	"	key <I485>               {	[      XF86Fn_F12 ] };\n"
	"	key <I486>               {	[        XF86Fn_1 ] };\n"
	"	key <I487>               {	[        XF86Fn_2 ] };\n"
	"	key <I488>               {	[        XF86Fn_D ] };\n"
	"	key <I489>               {	[        XF86Fn_E ] };\n"
	"	key <I490>               {	[        XF86Fn_F ] };\n"
	"	key <I491>               {	[        XF86Fn_S ] };\n"
	"	key <I492>               {	[        XF86Fn_B ] };\n"
	"	key <I493>               {	[ XF86FnRightShift ] };\n"
	"	key <I505>               {	[   braille_dot_1 ] };\n"
	"	key <I506>               {	[   braille_dot_2 ] };\n"
	"	key <I507>               {	[   braille_dot_3 ] };\n"
	"	key <I508>               {	[   braille_dot_4 ] };\n"
	"	key <I509>               {	[   braille_dot_5 ] };\n"
	"	key <I510>               {	[   braille_dot_6 ] };\n"
	"	key <I511>               {	[   braille_dot_7 ] };\n"
	"	key <I512>               {	[   braille_dot_8 ] };\n"
	"	key <I513>               {	[   braille_dot_9 ] };\n"
	"	key <I514>               {	[   braille_dot_1 ] };\n"
	"	key <I520>               {	[    XF86Numeric0 ] };\n"
	"	key <I521>               {	[    XF86Numeric1 ] };\n"
	"	key <I522>               {	[    XF86Numeric2 ] };\n"
	"	key <I523>               {	[    XF86Numeric3 ] };\n"
	"	key <I524>               {	[    XF86Numeric4 ] };\n"
	"	key <I525>               {	[    XF86Numeric5 ] };\n"
	"	key <I526>               {	[    XF86Numeric6 ] };\n"
	"	key <I527>               {	[    XF86Numeric7 ] };\n"
	"	key <I528>               {	[    XF86Numeric8 ] };\n"
	"	key <I529>               {	[    XF86Numeric9 ] };\n"
	"	key <I530>               {	[ XF86NumericStar ] };\n"
	"	key <I531>               {	[ XF86NumericPound ] };\n"
	"	key <I532>               {	[    XF86NumericA ] };\n"
	"	key <I533>               {	[    XF86NumericB ] };\n"
	"	key <I534>               {	[    XF86NumericC ] };\n"
	"	key <I535>               {	[    XF86NumericD ] };\n"
	"	key <I536>               {	[ XF86CameraFocus ] };\n"
	"	key <I537>               {	[   XF86WPSButton ] };\n"
	"	key <I538>               {	[ XF86TouchpadToggle ] };\n"
	"	key <I539>               {	[  XF86TouchpadOn ] };\n"
	"	key <I540>               {	[ XF86TouchpadOff ] };\n"
	"	key <I541>               {	[ XF86CameraZoomIn ] };\n"
	"	key <I542>               {	[ XF86CameraZoomOut ] };\n"
	"	key <I543>               {	[    XF86CameraUp ] };\n"
	"	key <I544>               {	[  XF86CameraDown ] };\n"
	"	key <I545>               {	[  XF86CameraLeft ] };\n"
	"	key <I546>               {	[ XF86CameraRight ] };\n"
	"	key <I547>               {	[ XF86AttendantOn ] };\n"
	"	key <I548>               {	[ XF86AttendantOff ] };\n"
	"	key <I549>               {	[ XF86AttendantToggle ] };\n"
	"	key <I550>               {	[ XF86LightsToggle ] };\n"
	"	key <I568>               {	[   XF86ALSToggle ] };\n"
	"	key <I569>               {	[ XF86RotationLockToggle ] };\n"
	"	key <I570>               {	[ XF86RefreshRateToggle ] };\n"
	"	key <I584>               {	[ XF86Buttonconfig ] };\n"
	"	key <I585>               {	[ XF86Taskmanager ] };\n"
	"	key <I586>               {	[     XF86Journal ] };\n"
	"	key <I587>               {	[ XF86ControlPanel ] };\n"
	"	key <I588>               {	[   XF86AppSelect ] };\n"
	"	key <I589>               {	[ XF86Screensaver ] };\n"
	"	key <I590>               {	[ XF86VoiceCommand ] };\n"
	"	key <I591>               {	[   XF86Assistant ] };\n"
	"	key <I592>               {	[  ISO_Next_Group ] };\n"
	"	key <I593>               {	[ XF86EmojiPicker ] };\n"
	"	key <I594>               {	[     XF86Dictate ] };\n"
	"	key <I595>               {	[ XF86CameraAccessEnable ] };\n"
	"	key <I596>               {	[ XF86CameraAccessDisable ] };\n"
	"	key <I597>               {	[ XF86CameraAccessToggle ] };\n"
	"	key <I598>               {	[ XF86Accessibility ] };\n"
	"	key <I599>               {	[ XF86DoNotDisturb ] };\n"
	"	key <I600>               {	[ XF86BrightnessMin ] };\n"
	"	key <I601>               {	[ XF86BrightnessMax ] };\n"
	"	key <I616>               {	[ XF86KbdInputAssistPrev ] };\n"
	"	key <I617>               {	[ XF86KbdInputAssistNext ] };\n"
	"	key <I618>               {	[ XF86KbdInputAssistPrevgroup ] };\n"
	"	key <I619>               {	[ XF86KbdInputAssistNextgroup ] };\n"
	"	key <I620>               {	[ XF86KbdInputAssistAccept ] };\n"
	"	key <I621>               {	[ XF86KbdInputAssistCancel ] };\n"
	"	key <I622>               {	[     XF86RightUp ] };\n"
	"	key <I623>               {	[   XF86RightDown ] };\n"
	"	key <I624>               {	[      XF86LeftUp ] };\n"
	"	key <I625>               {	[    XF86LeftDown ] };\n"
	"	key <I626>               {	[    XF86RootMenu ] };\n"
	"	key <I627>               {	[ XF86MediaTopMenu ] };\n"
	"	key <I628>               {	[   XF86Numeric11 ] };\n"
	"	key <I629>               {	[   XF86Numeric12 ] };\n"
	"	key <I630>               {	[   XF86AudioDesc ] };\n"
	"	key <I631>               {	[      XF863DMode ] };\n"
	"	key <I632>               {	[ XF86NextFavorite ] };\n"
	"	key <I633>               {	[  XF86StopRecord ] };\n"
	"	key <I634>               {	[ XF86PauseRecord ] };\n"
	"	key <I635>               {	[         XF86VOD ] };\n"
	"	key <I636>               {	[      XF86Unmute ] };\n"
	"	key <I637>               {	[ XF86FastReverse ] };\n"
	"	key <I638>               {	[ XF86SlowReverse ] };\n"
	"	key <I639>               {	[        XF86Data ] };\n"
	"	key <I640>               {	[ XF86OnScreenKeyboard ] };\n"
	"	key <I641>               {	[ XF86PrivacyScreenToggle ] };\n"
	"	key <I642>               {	[ XF86SelectiveScreenshot ] };\n"
	"	key <I643>               {	[ XF86NextElement ] };\n"
	"	key <I644>               {	[ XF86PreviousElement ] };\n"
	"	key <I645>               {	[ XF86AutopilotEngageToggle ] };\n"
	"	key <I646>               {	[ XF86MarkWaypoint ] };\n"
	"	key <I647>               {	[         XF86Sos ] };\n"
	"	key <I648>               {	[    XF86NavChart ] };\n"
	"	key <I649>               {	[ XF86FishingChart ] };\n"
	"	key <I650>               {	[ XF86SingleRangeRadar ] };\n"
	"	key <I651>               {	[ XF86DualRangeRadar ] };\n"
	"	key <I652>               {	[ XF86RadarOverlay ] };\n"
	"	key <I653>               {	[ XF86TraditionalSonar ] };\n"
	"	key <I654>               {	[ XF86ClearvuSonar ] };\n"
	"	key <I655>               {	[ XF86SidevuSonar ] };\n"
	"	key <I656>               {	[     XF86NavInfo ] };\n"
	"	key <I657>               {	[ XF86BrightnessAdjust ] };\n"
	"	key <I664>               {	[      XF86Macro1 ] };\n"
	"	key <I665>               {	[      XF86Macro2 ] };\n"
	"	key <I666>               {	[      XF86Macro3 ] };\n"
	"	key <I667>               {	[      XF86Macro4 ] };\n"
	"	key <I668>               {	[      XF86Macro5 ] };\n"
	"	key <I669>               {	[      XF86Macro6 ] };\n"
	"	key <I670>               {	[      XF86Macro7 ] };\n"
	"	key <I671>               {	[      XF86Macro8 ] };\n"
	"	key <I672>               {	[      XF86Macro9 ] };\n"
	"	key <I673>               {	[     XF86Macro10 ] };\n"
	"	key <I674>               {	[     XF86Macro11 ] };\n"
	"	key <I675>               {	[     XF86Macro12 ] };\n"
	"	key <I676>               {	[     XF86Macro13 ] };\n"
	"	key <I677>               {	[     XF86Macro14 ] };\n"
	"	key <I678>               {	[     XF86Macro15 ] };\n"
	"	key <I679>               {	[     XF86Macro16 ] };\n"
	"	key <I680>               {	[     XF86Macro17 ] };\n"
	"	key <I681>               {	[     XF86Macro18 ] };\n"
	"	key <I682>               {	[     XF86Macro19 ] };\n"
	"	key <I683>               {	[     XF86Macro20 ] };\n"
	"	key <I684>               {	[     XF86Macro21 ] };\n"
	"	key <I685>               {	[     XF86Macro22 ] };\n"
	"	key <I686>               {	[     XF86Macro23 ] };\n"
	"	key <I687>               {	[     XF86Macro24 ] };\n"
	"	key <I688>               {	[     XF86Macro25 ] };\n"
	"	key <I689>               {	[     XF86Macro26 ] };\n"
	"	key <I690>               {	[     XF86Macro27 ] };\n"
	"	key <I691>               {	[     XF86Macro28 ] };\n"
	"	key <I692>               {	[     XF86Macro29 ] };\n"
	"	key <I693>               {	[     XF86Macro30 ] };\n"
	"	key <I696>               {	[ XF86MacroRecordStart ] };\n"
	"	key <I697>               {	[ XF86MacroRecordStop ] };\n"
	"	key <I698>               {	[ XF86MacroPresetCycle ] };\n"
	"	key <I699>               {	[ XF86MacroPreset1 ] };\n"
	"	key <I700>               {	[ XF86MacroPreset2 ] };\n"
	"	key <I701>               {	[ XF86MacroPreset3 ] };\n"
	"	key <I704>               {	[ XF86KbdLcdMenu1 ] };\n"
	"	key <I705>               {	[ XF86KbdLcdMenu2 ] };\n"
	"	key <I706>               {	[ XF86KbdLcdMenu3 ] };\n"
	"	key <I707>               {	[ XF86KbdLcdMenu4 ] };\n"
	"	key <I708>               {	[ XF86KbdLcdMenu5 ] };\n"
	"	key <I709>               {	[ XF86PerformanceMode ] };\n"
	"	modifier_map Shift { <LFSH>, <RTSH> };\n"
	"	modifier_map Lock { <CAPS> };\n"
	"	modifier_map Control { <LCTL>, <RCTL> };\n"
	"	modifier_map Mod1 { <LALT>, <RALT>, <ALT>, <META> };\n"
	"	modifier_map Mod2 { <NMLK> };\n"
	"	modifier_map Mod3 { <LVL5> };\n"
	"	modifier_map Mod4 { <LWIN>, <RWIN>, <SUPR> };\n"
	"	modifier_map Mod5 { <LVL3> };\n"
	"};\n"
	"\n"
	"};\n";
