#!/bin/sh
# Generate a CMake toolchain file that cross-compiles C/C++ for x86_64-b1nix with
# the LLVM clang frontend and the b1nix *shared* libc++ runtime (libc++.so.1 +
# libc++abi.so.1), NOT GCC libstdc++. Used to rebuild the native LLVM/Clang
# toolchain (libLLVM.so) GCC-free — see tools/build-native-clang-libcxx.sh.
#
# clang has no b1nix driver, so linking through `clang --target=x86_64-b1nix`
# delegates to gcc and fails. Instead we override CMAKE_<LANG>_LINK_EXECUTABLE and
# CMAKE_CXX_CREATE_SHARED_LIBRARY to call ld.lld directly with the b1nix recipe:
#   - executables: crt0-dynamic.o + fixed base via linker-libcxx.ld + /lib/ld-b1nix.so
#   - shared libs: -shared, base 0 (PIC), NEEDED libc++.so.1/libc++abi.so.1/libc.so.1
# Both fold static compiler-rt for builtins (no libgcc) and resolve the C++ runtime
# from the shared libc++.so.1 (no libstdc++).
#
# Usage: gen-libcxx-native-cmake.sh <output.cmake>
set -eu
OUT="${1:?usage: gen-libcxx-native-cmake.sh <output.cmake>}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TRIPLET="x86_64-b1nix"
ARCH="x86_64"

CLANG="$(command -v clang)"
CLANGXX="$(command -v clang++)"
LD="$(command -v ld.lld)"
AR="$(command -v llvm-ar || command -v ar)"
RANLIB="$(command -v llvm-ranlib || command -v ranlib)"
NM="$(command -v llvm-nm || command -v nm)"
RES="$("$CLANG" -print-resource-dir)"

TB="$ROOT/build/x86_64/toolchain/$TRIPLET"
V1="$TB/llvm-runtimes-build/libcxx-install/include/c++/v1"
# STATIC libc++/libc++abi archives — folded (whole-archive) into libLLVM.so so the
# dylib's DT_NEEDED graph stays SHALLOW (just libc.so.1), matching the proven-
# working topology of the old libstdc++-folded libLLVM.so. Linking the *shared*
# libc++.so.1 instead gave clang a deep clang->libLLVM->libc++->libc++abi NEEDED
# chain the in-kernel eager loader stalls on. libc++.a is PIC-foldable into a .so.
LIBCXX_A="$TB/llvm-runtimes-build/libcxx-install/lib/libc++.a"
LIBCXXABI_A="$TB/llvm-runtimes-build/libcxx-install/lib/libc++abi.a"
COMPILER_RT="$TB/llvm-runtimes-build/install/lib/libcompiler_rt.a"
# Static libunwind.a supplies __register_frame/__deregister_frame (used by LLVM's
# JIT to register EH frames) — the shared libc++abi.so.1 folds the unwinder but
# does NOT export those two symbols. LLVM is built -fno-exceptions, so pulling the
# static unwinder in only satisfies these leaf JIT helpers; runtime C++ exception
# unwinding still goes through libc++abi.so.1.
LIBUNWIND_A="$TB/llvm-runtimes-build/install/lib/libunwind.a"
CRT0="$ROOT/userspace/build/$ARCH/crt/crt0-dynamic.o"
LIBC_SO="$ROOT/userspace/build/$ARCH/libc.so.1"
LDSCRIPT="$ROOT/userspace/linker-libcxx.ld"
UINC="$ROOT/userspace/include"
SYSROOT="$ROOT/build/x86_64/rootfs"

# OS predefines the b1nix cross-GCC driver sets but clang (unknown-OS target)
# does not: __b1nix__/b1nix (LLVM's Path.inc etc. branch on it) and __unix__
# (POSIX code paths). Without these, clang picks the wrong platform branch and
# fails (e.g. MNT_LOCAL undeclared in lib/Support/Unix/Path.inc).
B1NIX_DEFS="-D__b1nix__=1 -D__b1nix=1 -Db1nix=1 -D__unix__=1 -D__unix=1"

# Common compile flags: target b1nix, libc++ headers, clang builtin C headers,
# b1nix libc headers. -fno-exceptions -fno-rtti matches how LLVM builds itself.
CFLAGS_COMMON="--target=$TRIPLET $B1NIX_DEFS -nostdinc -isystem $RES/include -isystem $UINC"
CXXFLAGS_COMMON="--target=$TRIPLET $B1NIX_DEFS -nostdinc -nostdinc++ -isystem $V1 -isystem $RES/include -isystem $UINC"

# Static C++ runtime archives folded into every link. In the .so they are
# whole-archived (so libLLVM.so exports the libc++ symbols clang resolves against);
# the exe pulls only what libLLVM.so does not already export.
CXX_STATIC="$LIBCXX_A $LIBCXXABI_A $LIBUNWIND_A $COMPILER_RT"

# ── Link driver ─────────────────────────────────────────────────────────────
# clang emits compiler-driver link args (-Wl,--version-script,..., -Wl,--whole-
# archive, -lrt, -ldl) that raw ld.lld rejects. This driver translates them: it
# splits -Wl,a,b,c into a b c, drops libs b1nix folds into libc.so.1 (rt/dl/
# pthread/m/z), and appends the b1nix link recipe. $1 = exe|shared.
DRIVER="$(dirname "$OUT")/b1nix-lld-driver.sh"
cat > "$DRIVER" <<EOF
#!/bin/sh
# AUTO-GENERATED by gen-libcxx-native-cmake.sh — b1nix ld.lld link driver.
set -e
mode="\$1"; shift
LD="$LD"
CRT0="$CRT0"
LDSCRIPT="$LDSCRIPT"
LIBCXX_A="$LIBCXX_A"
LIBCXXABI_A="$LIBCXXABI_A"
LIBUNWIND_A="$LIBUNWIND_A"
COMPILER_RT="$COMPILER_RT"
LIBC="$LIBC_SO"
args=""
for a in "\$@"; do
  case "\$a" in
    -Wl,*) rest="\${a#-Wl,}"; oldifs="\$IFS"; IFS=','; for w in \$rest; do args="\$args \$w"; done; IFS="\$oldifs" ;;
    -lrt|-ldl|-lpthread|-lm|-lz|-lcurses|-ltinfo|-ledit|-lxml2) : ;;  # provided by libc.so.1 / disabled
    *) args="\$args \$a" ;;
  esac
done
if [ "\$mode" = shared ]; then
  # Fold libc++ statically so the .so's NEEDED graph is just libc.so.1 (shallow —
  # the in-kernel eager loader handles it). whole-archive exports the libc++
  # symbols so dependents (clang) resolve against this .so.
  # shellcheck disable=SC2086
  exec "\$LD" -m elf_x86_64 -shared --allow-multiple-definition \$args \
    --whole-archive "\$LIBCXX_A" "\$LIBCXXABI_A" --no-whole-archive "\$LIBUNWIND_A" "\$COMPILER_RT" "\$LIBC"
else
  # exe: libLLVM.so (in \$args via LINK_LIBRARIES) exports libc++; the static
  # group only fills symbols it does not export. crt0 first, fixed base.
  # shellcheck disable=SC2086
  exec "\$LD" -m elf_x86_64 -T "\$LDSCRIPT" --gc-sections --allow-multiple-definition -z norelro --hash-style=sysv --eh-frame-hdr --dynamic-linker /lib/ld-b1nix.so "\$CRT0" \$args \
    --start-group "\$LIBCXX_A" "\$LIBCXXABI_A" "\$LIBUNWIND_A" "\$COMPILER_RT" --end-group "\$LIBC"
fi
EOF
chmod +x "$DRIVER"

cat > "$OUT" <<EOF
# AUTO-GENERATED by tools/toolchain/gen-libcxx-native-cmake.sh — do not edit.
set(CMAKE_SYSTEM_NAME B1nix)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "$CLANG")
set(CMAKE_CXX_COMPILER "$CLANGXX")
set(CMAKE_ASM_COMPILER "$CLANG")
set(CMAKE_AR "$AR")
set(CMAKE_RANLIB "$RANLIB")
set(CMAKE_NM "$NM")
set(CMAKE_C_COMPILER_TARGET $TRIPLET)
set(CMAKE_CXX_COMPILER_TARGET $TRIPLET)

set(CMAKE_SYSROOT "$SYSROOT")
set(CMAKE_FIND_ROOT_PATH "$SYSROOT" "$TB/cross/$TRIPLET" "$TB/cross")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Probe: build only static libraries so CMake never tries to link with the clang
# driver (which would delegate to gcc and fail for the b1nix target).
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS_INIT   "$CFLAGS_COMMON -O2 -ffunction-sections -fdata-sections")
set(CMAKE_CXX_FLAGS_INIT "$CXXFLAGS_COMMON -O2 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti")
set(CMAKE_ASM_FLAGS_INIT "$CFLAGS_COMMON")

# Huge object lists (LLVM) -> response files.
set(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS 1)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS 1)
set(CMAKE_C_RESPONSE_FILE_LINK_FLAG "@")
set(CMAKE_CXX_RESPONSE_FILE_LINK_FLAG "@")

# Link through the b1nix ld.lld driver (translates -Wl,/-lrt/-ldl, adds recipe).
# Executable: dynamic, fixed base 0x2000000 via linker-libcxx.ld, crt0 first.
set(CMAKE_C_LINK_EXECUTABLE
    "$DRIVER exe <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE
    "$DRIVER exe <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

# Shared library (libLLVM.so): base 0 (PIC), NEEDED shared libc++/libc.
# --soname via the CMake SONAME_FLAG so <TARGET_SONAME> is populated (else a raw
# "-soname <TARGET_SONAME>" swallows the first object when the placeholder is empty).
set(CMAKE_SHARED_LIBRARY_SONAME_C_FLAG   "--soname=")
set(CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG "--soname=")
set(CMAKE_CXX_CREATE_SHARED_LIBRARY
    "$DRIVER shared <CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG><TARGET_SONAME> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_C_CREATE_SHARED_LIBRARY
    "$DRIVER shared <CMAKE_SHARED_LIBRARY_SONAME_C_FLAG><TARGET_SONAME> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

# Shared libraries must be PIC.
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".so")
EOF
echo "$OUT"
