#!/bin/sh
# xxd-i.sh — the one thing this build uses xxd for, without needing xxd.
#
# `xxd -i` ships inside vim, so a host without vim cannot build the initramfs
# byte arrays at all: the recipe fails with "xxd: command not found" and the
# error names a generated .inc file rather than the missing package. The output
# format is small and fixed, so generating it here removes vim from the build's
# requirements instead of documenting it as one.
#
# Usage: xxd-i.sh -i -n NAME FILE   (the flags exist so this is a drop-in)
set -e
name=
file=
while [ $# -gt 0 ]; do
	case "$1" in
	-i) ;;
	-n) name=$2; shift;;
	*)  file=$1;;
	esac
	shift
done
[ -n "$name" ] && [ -n "$file" ] || { echo "usage: $0 -i -n NAME FILE" >&2; exit 2; }

python3 - "$name" "$file" <<'PY'
import sys

name, path = sys.argv[1], sys.argv[2]
data = open(path, 'rb').read()
out = sys.stdout
out.write("unsigned char %s[] = {\n" % name)
# Twelve bytes a line, two-digit lower-case hex: what xxd -i emits, so a diff
# against a file generated by the real tool stays empty.
for i in range(0, len(data), 12):
    row = data[i:i + 12]
    out.write("  " + ", ".join("0x%02x" % b for b in row))
    out.write(",\n" if i + 12 < len(data) else "\n")
out.write("};\n")
out.write("unsigned int %s_len = %d;\n" % (name, len(data)))
PY
