#!/bin/sh
# Build libhubbub as a static libhubbub.a for the b1nix userspace ABI.
# Freestanding curated compile of the portable C sources (no autotools), like
# the other ports. libhubbub is NetSurf's HTML5 tokeniser + tree constructor;
# it parses input through libparserutils. Prints the install dir.
#
# M53 (NetSurf browser platform) — browser lib chain step 3. Depends on
# build-libparserutils.sh.

set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
HUBBUB_VERSION="${HUBBUB_VERSION:-0.3.8}"
TARBALL="libhubbub-${HUBBUB_VERSION}-src.tar.gz"
URL="https://download.netsurf-browser.org/libs/releases/${TARBALL}"
AR_BIN="${AR:-$(command -v llvm-ar 2>/dev/null || echo /opt/homebrew/opt/llvm/bin/llvm-ar)}"
PERL_BIN="${PERL:-$(command -v perl)}"
GPERF_BIN="${GPERF:-$(command -v gperf)}"

. "$ROOT_DIR/tools/toolchain-env.sh"

PU_DIR="$(B1NIX_ARCH="$B1NIX_ARCH" "$ROOT_DIR/tools/build-libparserutils.sh")"

SRC_PARENT="$ROOT_DIR/build/netsurf-src"
SRC_DIR="$SRC_PARENT/libhubbub-${HUBBUB_VERSION}"
BUILD_DIR="$ROOT_DIR/build/libhubbub-b1nix/$B1NIX_TRIPLET"
OBJ_DIR="$BUILD_DIR/obj"
INSTALL_DIR="$BUILD_DIR/install"

mkdir -p "$SRC_PARENT" "$OBJ_DIR" "$INSTALL_DIR/include" "$INSTALL_DIR/lib"

if [ ! -d "$SRC_DIR" ]; then
  tmp="$SRC_PARENT/$TARBALL"
  [ -f "$tmp" ] || curl -L "$URL" -o "$tmp" 1>&2
  tar -xzf "$tmp" -C "$SRC_PARENT" 1>&2
fi

# Named-entity table: generated from build/Entities by the upstream perl script
# (host perl, arch-agnostic).
if [ ! -f "$SRC_DIR/src/tokeniser/entities.inc" ]; then
  ( cd "$SRC_DIR" && "$PERL_BIN" build/make-entities.pl ) 1>&2
fi

# Element-type perfect-hash: gperf the .gperf file, then mark the table static
# (exactly the upstream Makefile rule). It is #included by element-type.c, so it
# is a fragment — never compiled as its own translation unit.
ELT_GEN="$SRC_DIR/src/treebuilder/autogenerated-element-type.c"
if [ ! -f "$ELT_GEN" ]; then
  "$GPERF_BIN" --output-file="$ELT_GEN.tmp" "$SRC_DIR/src/treebuilder/element-type.gperf" 1>&2
  sed -e 's/^\(const struct element_type_map\)/static \1/' "$ELT_GEN.tmp" >"$ELT_GEN"
  rm -f "$ELT_GEN.tmp"
fi

if [ "$B1NIX_ARCH" = "x86" ]; then
  TARGET="i686-unknown-elf"
else
  TARGET="x86_64-unknown-elf"
fi

# -Isrc for the internal "tokeniser/..."/"treebuilder/..." headers; the
# libparserutils install include dir for <parserutils/...>.
CFLAGS="--target=$TARGET -ffreestanding -fno-builtin -fno-stack-protector
  -nostdinc -isystem $ROOT_DIR/userspace/include -I$ROOT_DIR/userspace/include
  -O2 -fno-strict-aliasing -Db1nix -DNDEBUG
  -I$SRC_DIR/include -I$SRC_DIR/src -I$PU_DIR/include
  -Wno-implicit-function-declaration"

OBJS=""
for src in $(find "$SRC_DIR/src" -name '*.c' ! -name 'autogenerated-*.c' | sort); do
  obj="$OBJ_DIR/$(echo "${src#$SRC_DIR/src/}" | tr '/' '_').o"
  # shellcheck disable=SC2086
  clang $CFLAGS -c "$src" -o "$obj"
  OBJS="$OBJS $obj"
done

# shellcheck disable=SC2086
"$AR_BIN" rcs "$INSTALL_DIR/lib/libhubbub.a" $OBJS
cp -R "$SRC_DIR/include/hubbub" "$INSTALL_DIR/include/"

echo "$INSTALL_DIR"
