#!/bin/sh
# Build libcss as a static libcss.a for the b1nix userspace ABI. Freestanding
# curated compile of the portable C sources (no autotools), like the other
# ports. libcss is NetSurf's CSS parser + selection engine; it interns through
# libwapcaplet and parses input through libparserutils. The release tarball
# ships all generated property tables (select/properties/*.c, parse/properties/
# *.c, autogenerated_*.h), so no python/perl generation is needed. Prints the
# install dir.
#
# M53 (NetSurf browser platform) — browser lib chain step 4. Depends on
# build-libwapcaplet.sh and build-libparserutils.sh.

set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CSS_VERSION="${CSS_VERSION:-0.9.2}"
TARBALL="libcss-${CSS_VERSION}-src.tar.gz"
URL="https://download.netsurf-browser.org/libs/releases/${TARBALL}"
AR_BIN="${AR:-$(command -v llvm-ar 2>/dev/null || echo /opt/homebrew/opt/llvm/bin/llvm-ar)}"
PERL_BIN="${PERL:-$(command -v perl)}"
HOST_CC="${CC_FOR_BUILD:-$(command -v cc || command -v clang)}"

. "$ROOT_DIR/tools/toolchain-env.sh"

LWC_DIR="$(B1NIX_ARCH="$B1NIX_ARCH" "$ROOT_DIR/tools/build-libwapcaplet.sh")"
PU_DIR="$(B1NIX_ARCH="$B1NIX_ARCH" "$ROOT_DIR/tools/build-libparserutils.sh")"

SRC_PARENT="$ROOT_DIR/build/netsurf-src"
SRC_DIR="$SRC_PARENT/libcss-${CSS_VERSION}"
BUILD_DIR="$ROOT_DIR/build/libcss-b1nix/$B1NIX_TRIPLET"
OBJ_DIR="$BUILD_DIR/obj"
INSTALL_DIR="$BUILD_DIR/install"

mkdir -p "$SRC_PARENT" "$OBJ_DIR" "$INSTALL_DIR/include" "$INSTALL_DIR/lib"

if [ ! -d "$SRC_DIR" ]; then
  tmp="$SRC_PARENT/$TARBALL"
  [ -f "$tmp" ] || curl -L "$URL" -o "$tmp" 1>&2
  tar -xzf "$tmp" -C "$SRC_PARENT" 1>&2
fi

# The "simple" enum/keyword property parsers (display, direction, ...) are not
# shipped: a host tool (css_property_parser_gen.c) is compiled and run once per
# property descriptor in properties.gen to emit autogenerated_<prop>.c. This
# mirrors the upstream parse/properties/Makefile rule exactly.
PROP_DIR="$SRC_DIR/src/parse/properties"
GEN_PARSER="$BUILD_DIR/gen_parser"
if [ ! -f "$PROP_DIR/.b1nix-autogen-stamp" ]; then
  "$HOST_CC" -O2 -o "$GEN_PARSER" "$PROP_DIR/css_property_parser_gen.c" 1>&2
  # Property names: the token before the first ':' on each non-comment line.
  PROPS=$("$PERL_BIN" -ne 'print "$1\n" if /^([^#][^:]+):/' "$PROP_DIR/properties.gen")
  for p in $PROPS; do
    line=$(grep "^$p:" "$PROP_DIR/properties.gen")
    "$GEN_PARSER" -o "$PROP_DIR/autogenerated_$p.c" "$line" 1>&2
  done
  touch "$PROP_DIR/.b1nix-autogen-stamp"
fi

if [ "$B1NIX_ARCH" = "x86" ]; then
  TARGET="i686-unknown-elf"
else
  TARGET="x86_64-unknown-elf"
fi

# -Isrc for internal "select/..."/"parse/..." headers; the dep install include
# dirs for <libwapcaplet/...> and <parserutils/...>.
# _ALIGNED is an alignment-attribute macro libcss leaves undefined, relying on
# old-GCC -fcommon to merge the bogus tentative global it produces in every TU
# (clang defaults to -fno-common → duplicate-symbol errors). Define it empty:
# the struct keeps its default layout and no stray symbol is emitted.
CFLAGS="--target=$TARGET -ffreestanding -fno-builtin -fno-stack-protector
  -nostdinc -isystem $ROOT_DIR/userspace/include -I$ROOT_DIR/userspace/include
  -O2 -fno-strict-aliasing -Db1nix -D_ALIGNED=
  -I$SRC_DIR/include -I$SRC_DIR/src -I$LWC_DIR/include -I$PU_DIR/include
  -Wno-implicit-function-declaration"

# css_property_parser_gen.c is the HOST generator tool (it has its own main and
# is not part of the library) — never compile it into the target archive.
OBJS=""
for src in $(find "$SRC_DIR/src" -name '*.c' ! -name 'css_property_parser_gen.c' | sort); do
  obj="$OBJ_DIR/$(echo "${src#$SRC_DIR/src/}" | tr '/' '_').o"
  # shellcheck disable=SC2086
  clang $CFLAGS -c "$src" -o "$obj"
  OBJS="$OBJS $obj"
done

# shellcheck disable=SC2086
"$AR_BIN" rcs "$INSTALL_DIR/lib/libcss.a" $OBJS
cp -R "$SRC_DIR/include/libcss" "$INSTALL_DIR/include/"

echo "$INSTALL_DIR"
