#!/bin/sh
# Build libsvgtiny as a static libsvgtiny.a for the b1nix userspace ABI.
# Freestanding curated compile (no autotools). libsvgtiny is NetSurf's SVG
# decoder; the browser registers it as an image content handler so inline/img
# SVG renders.
#
# libsvgtiny parses SVG (which is XML) through libdom's XML binding
# (dom_xml_parser_*). b1nix's libdom build only ships the hubbub (HTML) binding,
# so we compile libdom's expat XML binding (bindings/xml/expat_xmlparser.c) into
# libsvgtiny.a here and link against the b1nix expat port. Also depends on
# libdom + libwapcaplet (staged) and openlibm (math). The named-colour table is
# generated from colors.gperf with gperf. Prints the install dir.
#
# M53 (NetSurf browser platform) — SVG image decoder.

set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
AR_BIN="${AR:-$(command -v llvm-ar 2>/dev/null || echo /opt/homebrew/opt/llvm/bin/llvm-ar)}"
GPERF_BIN="${GPERF:-$(command -v gperf 2>/dev/null || true)}"

. "$ROOT_DIR/tools/toolchain-env.sh"

if [ -z "$GPERF_BIN" ]; then
  echo "build-libsvgtiny.sh: gperf not found on host (needed for colors table)" >&2
  exit 1
fi

# libsvgtiny + libdom both ship inside the netsurf-all bundle build-netsurf-fb.sh
# extracts; use that copy of libdom for the XML binding source.
SRC_PARENT="$ROOT_DIR/build/netsurf-src"
SRC_DIR="$(ls -d "$SRC_PARENT"/netsurf-all-*/libsvgtiny 2>/dev/null | head -1)"
LIBDOM_DIR="$(ls -d "$SRC_PARENT"/netsurf-all-*/libdom 2>/dev/null | head -1)"
if [ -z "$SRC_DIR" ] || [ ! -f "$SRC_DIR/src/svgtiny.c" ]; then
  echo "build-libsvgtiny.sh: libsvgtiny source not found (run build-netsurf-fb.sh first)" >&2
  exit 1
fi
if [ -z "$LIBDOM_DIR" ] || [ ! -f "$LIBDOM_DIR/bindings/xml/expat_xmlparser.c" ]; then
  echo "build-libsvgtiny.sh: libdom XML binding source not found" >&2
  exit 1
fi

# expat (M51 port) — XML parser backing libdom's XML binding.
EXPAT_INST="$(B1NIX_ARCH="$B1NIX_ARCH" "$ROOT_DIR/tools/build-expat.sh" | tail -1)"

# Sysroot from build-netsurf-fb.sh holds libdom/libwapcaplet headers + openlibm.
SYSROOT="$ROOT_DIR/build/netsurf-sysroot/$B1NIX_TRIPLET"

BUILD_DIR="$ROOT_DIR/build/libsvgtiny-b1nix/$B1NIX_TRIPLET"
OBJ_DIR="$BUILD_DIR/obj"
INSTALL_DIR="$BUILD_DIR/install"
GENINC="$BUILD_DIR/geninc" # staged dom/bindings/xml headers, included as <dom/...>
mkdir -p "$OBJ_DIR" "$INSTALL_DIR/include" "$INSTALL_DIR/lib" \
         "$GENINC/dom/bindings/xml"

# Stage the libdom XML binding public headers under the install <dom/...> layout
# (libdom's own install does this; b1nix's curated libdom build skips it).
cp "$LIBDOM_DIR/bindings/xml/xmlparser.h" "$LIBDOM_DIR/bindings/xml/xmlerror.h" \
   "$GENINC/dom/bindings/xml/"

# Generate the named-colour perfect-hash table (svgtiny.c #includes it).
"$GPERF_BIN" --output-file="$SRC_DIR/src/autogenerated_colors.c" "$SRC_DIR/src/colors.gperf"

if [ "$B1NIX_ARCH" = "x86" ]; then TARGET="i686-unknown-elf"; else TARGET="x86_64-unknown-elf"; fi

CFLAGS="--target=$TARGET -ffreestanding -fno-builtin -fno-stack-protector
  -nostdinc -isystem $ROOT_DIR/userspace/include -I$ROOT_DIR/userspace/include
  -O2 -fno-strict-aliasing -Db1nix
  -I$SRC_DIR/include -I$SRC_DIR/src
  -I$SYSROOT/include -I$GENINC -I$EXPAT_INST/include
  -Wno-implicit-function-declaration"

OBJS=""
add_obj() { # $1 = source file, $2 = -I extras (optional)
  obj="$OBJ_DIR/$(echo "$1" | tr '/' '_').o"
  # shellcheck disable=SC2086
  clang $CFLAGS ${2:-} -c "$1" -o "$obj"
  OBJS="$OBJS $obj"
}

add_obj "$SRC_DIR/src/svgtiny.c"
add_obj "$SRC_DIR/src/svgtiny_gradient.c"
add_obj "$SRC_DIR/src/svgtiny_list.c"
# libdom XML binding (expat backend). Needs its sibling utils.h/xmlerror.h.
add_obj "$LIBDOM_DIR/bindings/xml/expat_xmlparser.c" "-I$LIBDOM_DIR/bindings/xml"

# shellcheck disable=SC2086
"$AR_BIN" rcs "$INSTALL_DIR/lib/libsvgtiny.a" $OBJS
cp "$SRC_DIR/include/svgtiny.h" "$INSTALL_DIR/include/"
# Make sure libexpat.a is reachable in the netsurf sysroot for the final link.
cp "$EXPAT_INST/lib/libexpat.a" "$SYSROOT/lib/" 2>/dev/null || true

echo "$INSTALL_DIR"
