#!/bin/sh
# tools/gen_netsurf_initramfs.sh — package the NetSurf framebuffer browser, its
# runtime resources and a test page for the b1nix kernel initramfs (same xxd +
# table-macro pattern as gen_tcc_initramfs.sh). Emits a .inc defining
# NETSURF_INITRAMFS_FILES for kernel/fs/initramfs.c.
set -eu

OUT="$1"
if [ -z "$OUT" ]; then echo "Usage: $0 <output_file>" >&2; exit 1; fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"
B1NIX_ARCH="${B1NIX_ARCH:-x86_64}"
case "$B1NIX_ARCH" in x86) TRIPLET=i686-b1nix;; *) TRIPLET=x86_64-b1nix;; esac

NSFB="build/netsurf-fb-b1nix/$TRIPLET/nsfb"
RES="build/netsurf-src/netsurf-3.11/frontends/framebuffer/res"
ASSETS="tools/netsurf-assets"

mkdir -p "$(dirname "$OUT")"
echo "/* Auto-generated by tools/gen_netsurf_initramfs.sh - DO NOT EDIT */" > "$OUT"
echo "" >> "$OUT"

# 1. The browser binary.
xxd -i -n vfs_nsfb_elf "$NSFB" >> "$OUT"

# 2. Runtime resources, installed under a default RESPATH entry
#    (/usr/local/share/netsurf) so NetSurf finds them with no env setup.
#    pkgpath:srcfile  pairs.
RES_ENTRIES="
default.css:$RES/default.css
quirks.css:$RES/quirks.css
internal.css:$RES/internal.css
adblock.css:$RES/adblock.css
Messages:$RES/Messages
"
i=0
for pair in $RES_ENTRIES; do
  pkg=${pair%%:*}; src=${pair#*:}
  [ -f "$src" ] || continue
  var="vfs_nsres_$i"
  xxd -i -n "$var" "$src" >> "$OUT"
  eval "RVAR_$i=$var; RPKG_$i=$pkg"
  i=$((i+1))
done
NRES=$i

# 3. The test page + image.
xxd -i -n vfs_ns_testhtml "$ASSETS/test.html" >> "$OUT"
xxd -i -n vfs_ns_testpng  "$ASSETS/test.png"  >> "$OUT"

# 4. The file table macro.
{
  echo ""
  echo "#define NETSURF_INITRAMFS_FILES \\"
  echo "    {\"/bin/nsfb\", (const char *)vfs_nsfb_elf, sizeof(vfs_nsfb_elf), INITRAMFS_EXECUTABLE}, \\"
  j=0
  while [ "$j" -lt "$NRES" ]; do
    eval "v=\$RVAR_$j; p=\$RPKG_$j"
    echo "    {\"/usr/local/share/netsurf/$p\", (const char *)$v, sizeof($v), 0}, \\"
    j=$((j+1))
  done
  echo "    {\"/netsurf/test.html\", (const char *)vfs_ns_testhtml, sizeof(vfs_ns_testhtml), 0}, \\"
  printf "    {\"/netsurf/test.png\", (const char *)vfs_ns_testpng, sizeof(vfs_ns_testpng), 0}\n"
} >> "$OUT"

echo "gen_netsurf_initramfs: wrote $OUT" >&2
