#!/bin/sh
# Phase 1 of the Chromium -> b1nix port (M60-M63): depot_tools + a Chromium
# `fetch`/`gclient sync`, then re-apply the b1nix //build patches and `gn gen`.
#
# RUN THIS YOURSELF — it downloads ~50 GB of source and the build tree grows to
# ~100 GB+. Claude isn't allowed to fetch external code unattended, and this box
# (43 GB free) cannot hold it. Run on a host with >=150 GB free.
#
#   sh tools/sync-chromium.sh
#
# Reuses the b1nix GN target/toolchain the V8 port already added to the shared
# //build module — see tools/patches/chromium/PORT-PLAN.md.
set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CR="${CHROMIUM_DIR:-$ROOT_DIR/build/toolchain_build/chromium}"
GN="$ROOT_DIR/build/toolchain_build/v8-skeleton/gn-src/out/gn"
[ -x "$GN" ] || { echo "gn missing — run: sh tools/build-gn.sh"; exit 1; }

# Hard disk guard. Lean headless release (--no-history src + release out/) fits in
# ~80-90 GB; a full debug/component build needs ~150 GB. We build lean → 90 GB floor.
MIN_GB="${MIN_GB:-90}"
avail_gb=$(df -P "$(dirname "$CR")" 2>/dev/null | awk 'NR==2{print int($4/1024/1024)}')
if [ "${avail_gb:-0}" -lt "$MIN_GB" ]; then
  echo "ABORT: only ${avail_gb:-?} GB free at $CR; need >=${MIN_GB} GB (set MIN_GB= to override)." >&2
  echo "Set CHROMIUM_DIR= to a bigger volume and re-run." >&2
  exit 1
fi

mkdir -p "$CR"
cd "$CR"

# depot_tools (gclient/fetch). Cached after first run.
if [ ! -d depot_tools ]; then
  git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
fi
export PATH="$CR/depot_tools:$PATH"

# Fetch Chromium (no history = smaller). `fetch` is idempotent-ish; `sync` after.
if [ ! -d src ]; then
  fetch --no-history chromium
fi
cd src
gclient sync --no-history

# Re-apply the b1nix //build patches (gclient sync re-pulls //build at its
# DEPS-pinned revision, so these MUST be re-applied after every sync).
sh "$ROOT_DIR/tools/patches/chromium/apply.sh" "$CR/src"

# Generate the b1nix build dir. args.gn keeps it minimal: headless, no sandbox.
mkdir -p out/b1nix
cat > out/b1nix/args.gn <<'EOF'
target_os = "b1nix"
target_cpu = "x64"
is_debug = false
is_component_build = false
use_sysroot = false
# M62 config: headless render, sandbox stubbed (M63 is deferred).
use_ozone = true
ozone_platform_headless = true
ozone_auto_platforms = false
enable_supervised_users = true
use_autogenerated_modules = false   # GCC build — clang C++ modules unused
use_custom_libcxx = false           # b1nix builds with GCC + its own libstdc++ (M55); bundled libc++ needs GCC15+
v8_enable_sandbox = false           # M62: V8 sandbox is M63-deferred; also requires libc++ hardening (use_safe_libcxx)
EOF
"$GN" gen out/b1nix

echo "=== gn gen done. Next: ninja -C $CR/src/out/b1nix base ==="
