#!/bin/sh
# tools/images/gen_tcc_initramfs.sh — Package TCC binary, libs, and headers for kernel initramfs
set -e

OUT="$1"
if [ -z "$OUT" ]; then
    echo "Usage: $0 <output_file>" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
B1NIX_ARCH="${B1NIX_ARCH:-x86_64}"
USERSPACE_BUILD="userspace/build/$B1NIX_ARCH"

cd "$PROJECT_DIR"

# Ensure directories exist
mkdir -p "$(dirname "$OUT")"
rm -f "$OUT"

echo "/* Automatically generated by tools/images/gen_tcc_initramfs.sh - DO NOT EDIT */" > "$OUT"
echo "" >> "$OUT"

# 1. Package key files using xxd
echo "Packing /bin/tcc..." >&2
xxd -i -n vfs_tcc_elf "$USERSPACE_BUILD/bin/tcc" >> "$OUT"

echo "Packing /lib/crt0.o..." >&2
xxd -i -n vfs_crt0_o "$USERSPACE_BUILD/crt/crt0.o" >> "$OUT"

echo "Packing /lib/libb1nix.a..." >&2
xxd -i -n vfs_libb1nix_a "$USERSPACE_BUILD/libb1nix.a" >> "$OUT"

# 2. Package standard headers
echo "Packing userspace/include/*.h..." >&2
HEADERS=$(find userspace/include -type f | grep -v "\.DS_Store" | sort)
for h in $HEADERS; do
    rel_path=${h#userspace/include/}
    var_name="vfs_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    xxd -i -n "$var_name" "$h" >> "$OUT"
done

# 3. Package TCC internal headers
echo "Packing userspace/tcc/include/*.h..." >&2
TCC_HEADERS=$(find userspace/tcc/include -type f | grep -v "\.DS_Store" | sort)
for h in $TCC_HEADERS; do
    rel_path=${h#userspace/tcc/include/}
    var_name="vfs_tcc_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    xxd -i -n "$var_name" "$h" >> "$OUT"
done

# 4. Generate the macro listing all files
echo "" >> "$OUT"
echo "#define TCC_INITRAMFS_FILES \\" >> "$OUT"
echo "    {\"/bin/tcc\", (const char *)vfs_tcc_elf, sizeof(vfs_tcc_elf), INITRAMFS_EXECUTABLE}, \\" >> "$OUT"
echo "    {\"/lib/crt0.o\", (const char *)vfs_crt0_o, sizeof(vfs_crt0_o), 0}, \\" >> "$OUT"
printf "    {\"/lib/libb1nix.a\", (const char *)vfs_libb1nix_a, sizeof(vfs_libb1nix_a), 0}" >> "$OUT"

for h in $HEADERS; do
    rel_path=${h#userspace/include/}
    var_name="vfs_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    echo ", \\" >> "$OUT"
    printf "    {\"/include/%s\", (const char *)%s, sizeof(%s), 0}" "$rel_path" "$var_name" "$var_name" >> "$OUT"
done

for h in $TCC_HEADERS; do
    rel_path=${h#userspace/tcc/include/}
    var_name="vfs_tcc_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    echo ", \\" >> "$OUT"
    printf "    {\"/lib/tcc/include/%s\", (const char *)%s, sizeof(%s), 0}" "$rel_path" "$var_name" "$var_name" >> "$OUT"
done

echo "" >> "$OUT"
echo "gen_tcc_initramfs: generated $OUT successfully" >&2
