#!/bin/sh
# Package the M34 corpus sources, its on-device runner, and standard headers.
set -e
OUT="$1"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ARCH="${B1NIX_ARCH:-x86_64}"
mkdir -p "$(dirname "$OUT")"
rm -f "$OUT"
echo '/* Generated by gen_b1cc_m34_initramfs.sh. */' > "$OUT"
xxd -i -n vfs_b1cc_m34_runner "$ROOT/userspace/build/$ARCH/bin/b1cc_m34_corpus" >> "$OUT"
xxd -i -n vfs_b1cc_m34_elf "$ROOT/userspace/build/$ARCH/bin/b1cc_m34" >> "$OUT"
for src in \
  return_42 precedence local if_else while for function string_pointer \
  m34_control_flow m34_expression_semantics m34_typedef_array_decay \
  m34_local_partial_init m34_knr_params m34_const_correct m34_complex_storage \
  m34_vla_loop m34_hideset_recursion m34_va_copy m34_weak_symbol m34_headers \
  m34_runtime puts m10_switch m11_globals m18_aggregates; do
    var="vfs_b1cc_m34_${src}"
    file="$ROOT/userspace/b1cc/tests/$src.c"
    xxd -i -n "$var" "$file" >> "$OUT"
done

# Package standard headers
HEADERS=$(find "$ROOT/userspace/include" -type f | grep -v "\.DS_Store" | sort)
for h in $HEADERS; do
    rel_path=${h#$ROOT/userspace/include/}
    var_name="vfs_b1cc_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    xxd -i -n "$var_name" "$h" >> "$OUT"
done

# Package real libm.a
xxd -i -n vfs_b1cc_libm "$ROOT/build/openlibm-b1nix/$ARCH-b1nix/install/lib/libm.a" >> "$OUT"

echo '#define B1CC_M34_INITRAMFS_FILES \\' >> "$OUT"
printf '    {"/bin/b1cc_m34_corpus", (const char *)vfs_b1cc_m34_runner, sizeof(vfs_b1cc_m34_runner), INITRAMFS_EXECUTABLE},' >> "$OUT"
echo ' \\' >> "$OUT"
printf '    {"/lib/b1cc/libm.a", (const char *)vfs_b1cc_libm, sizeof(vfs_b1cc_libm), 0},' >> "$OUT"

for src in \
  return_42 precedence local if_else while for function string_pointer \
  m34_control_flow m34_expression_semantics m34_typedef_array_decay \
  m34_local_partial_init m34_knr_params m34_const_correct m34_complex_storage \
  m34_vla_loop m34_hideset_recursion m34_va_copy m34_weak_symbol m34_headers \
  m34_runtime puts m10_switch m11_globals m18_aggregates; do
    var="vfs_b1cc_m34_${src}"
    echo ' \\' >> "$OUT"
    printf '    {"/tests/m34/%s.c", (const char *)%s, sizeof(%s), 0},' "$src" "$var" "$var" >> "$OUT"
done

for h in $HEADERS; do
    rel_path=${h#$ROOT/userspace/include/}
    var_name="vfs_b1cc_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    echo ' \\' >> "$OUT"
    printf '    {"/include/%s", (const char *)%s, sizeof(%s), 0},' "$rel_path" "$var_name" "$var_name" >> "$OUT"
done
echo >> "$OUT"
