#!/bin/sh
# tools/images/gen_tcc_initramfs.sh — Package TCC binary, libs, and headers for kernel initramfs
set -e

OUT="$1"
if [ -z "$OUT" ]; then
    echo "Usage: $0 <output_file>" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
B1NIX_ARCH="${B1NIX_ARCH:-x86_64}"
USERSPACE_BUILD="userspace/build/$B1NIX_ARCH"

cd "$PROJECT_DIR"

# Ensure directories exist
mkdir -p "$(dirname "$OUT")"
rm -f "$OUT"

echo "/* Automatically generated by tools/images/gen_tcc_initramfs.sh - DO NOT EDIT */" > "$OUT"
echo "" >> "$OUT"

# 1. Package key files using xxd
echo "Packing /bin/tcc..." >&2
xxd -i -n vfs_tcc_elf "$USERSPACE_BUILD/bin/tcc" >> "$OUT"

# TCC-compiled programs link against musl now (the old b1nix crt0.o/libb1nix.a
# path was retired with the musl migration). tcc's b1nix branch links a single
# "crt0.o", so hand it musl's crt1.o under that name; -lc resolves via the
# /lib/libc.so -> ld-musl symlink already in the initramfs.
MUSL_ROOT="build/musl-b1nix/$B1NIX_ARCH-b1nix/install/usr"

echo "Packing /lib/crt0.o (musl crt1.o)..." >&2
xxd -i -n vfs_crt0_o "$MUSL_ROOT/lib/crt1.o" >> "$OUT"

# TCC's own compiler-runtime archive. tcc links it into every program it
# compiles (alloca, __va_start, atomics, integer division/conversion helpers).
# tcc_add_support() searches library_paths[0] = CONFIG_TCC_LIBPATHS = /lib, so it
# must live at /lib/libtcc1.a (NOT /lib/tcc/). Built by userspace ($(TCC_LIBTCC1)).
echo "Packing /lib/libtcc1.a..." >&2
xxd -i -n vfs_tcc_libtcc1_a "$USERSPACE_BUILD/tcc/libtcc1.a" >> "$OUT"

# 2. Package musl standard C headers under /include (tcc's sysinclude path).
# Skip the bundled libc++ tree (c++/v1/...): tcc is a C compiler and those
# paths carry '+' which is not a valid C identifier character.
echo "Packing musl headers..." >&2
HEADERS=$(find "$MUSL_ROOT/include" -type f -name '*.h' | grep -v '/c++/' | sort)
for h in $HEADERS; do
    rel_path=${h#"$MUSL_ROOT"/include/}
    var_name="vfs_hdr_$(echo "$rel_path" | tr '/.+-' '____')"
    xxd -i -n "$var_name" "$h" >> "$OUT"
done

# 3. Package TCC internal headers
echo "Packing userspace/tcc/include/*.h..." >&2
TCC_HEADERS=$(find userspace/tcc/include -type f | grep -v "\.DS_Store" | sort)
for h in $TCC_HEADERS; do
    rel_path=${h#userspace/tcc/include/}
    var_name="vfs_tcc_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    xxd -i -n "$var_name" "$h" >> "$OUT"
done

# 4. Generate the macro listing all files
echo "" >> "$OUT"
echo "#define TCC_INITRAMFS_FILES \\" >> "$OUT"
echo "    {\"/bin/tcc\", (const char *)vfs_tcc_elf, sizeof(vfs_tcc_elf), INITRAMFS_EXECUTABLE}, \\" >> "$OUT"
echo "    {\"/lib/libtcc1.a\", (const char *)vfs_tcc_libtcc1_a, sizeof(vfs_tcc_libtcc1_a), 0}, \\" >> "$OUT"
printf "    {\"/lib/crt0.o\", (const char *)vfs_crt0_o, sizeof(vfs_crt0_o), 0}" >> "$OUT"

for h in $HEADERS; do
    rel_path=${h#"$MUSL_ROOT"/include/}
    var_name="vfs_hdr_$(echo "$rel_path" | tr '/.+-' '____')"
    echo ", \\" >> "$OUT"
    printf "    {\"/include/%s\", (const char *)%s, sizeof(%s), 0}" "$rel_path" "$var_name" "$var_name" >> "$OUT"
done

for h in $TCC_HEADERS; do
    rel_path=${h#userspace/tcc/include/}
    var_name="vfs_tcc_hdr_$(echo "$rel_path" | tr '/.-' '___')"
    echo ", \\" >> "$OUT"
    printf "    {\"/lib/tcc/include/%s\", (const char *)%s, sizeof(%s), 0}" "$rel_path" "$var_name" "$var_name" >> "$OUT"
done

echo "" >> "$OUT"
echo "gen_tcc_initramfs: generated $OUT successfully" >&2
