#ifndef B1NIX_SYSCALL_H
#define B1NIX_SYSCALL_H

#include <b1nix/types.h>

enum syscall_number {
	SYS_WRITE = 1,
	SYS_EXIT = 2,
	SYS_SPAWN = 3,
	SYS_LIST = 4,
	SYS_READ_FILE = 5,
	SYS_YIELD = 6,
	SYS_OPEN = 7,
	SYS_READ = 8,
	SYS_CLOSE = 9,
	SYS_CREATE = 10,
	SYS_NET_PING = 11,
	SYS_NET_DNS = 12,
	SYS_READ_KBD = 13,
	SYS_CLEAR = 14,
	SYS_PS = 15,
	SYS_MEM = 16,
	SYS_REBOOT = 17,
	SYS_SET_STDOUT = 18,
	SYS_NET_INFO = 19,
	SYS_EXEC = 20,
	SYS_WAIT = 21,
	SYS_MMAP = 22,
	SYS_SLEEP = 23,
	SYS_KILL = 24,
	SYS_SIGNAL = 25,
	SYS_GETPID = 26,
	SYS_MQ_OPEN = 27,
	SYS_MQ_SEND = 28,
	SYS_MQ_RECEIVE = 29,
	SYS_MQ_CLOSE = 30,
	SYS_MQ_UNLINK = 31,
	SYS_SHMDT = 32,
	SYS_SHMGET = 33,
	SYS_SHMAT = 34,
	SYS_SHMCTL = 35,
	SYS_CHMOD = 36,
	SYS_CHOWN = 37,
	SYS_GETUID = 38,
	SYS_GETEUID = 39,
	SYS_GETGID = 40,
	SYS_GETEGID = 41,
	SYS_SETUID = 42,
	SYS_SETGID = 43,
	SYS_READDIR = 44,
	SYS_FORK = 45,
	SYS_EXECVE = 46,
	SYS_WAITPID = 47,
	SYS_STAT = 48,
	SYS_LSEEK = 49,
	SYS_UNLINK = 50,
	SYS_MKDIR = 51,
	SYS_CHDIR = 52,
	SYS_GETDENTS = 53,
	SYS_PIPE = 54,
	SYS_DUP2 = 55,
	SYS_FCNTL = 56,
	SYS_MUNMAP = 57,
	SYS_BRK = 58,
	SYS_SOCKET = 59,
	SYS_BIND = 60,
	SYS_CONNECT = 61,
	SYS_SEND = 62,
	SYS_RECV = 63,
	SYS_IOCTL = 64,
	SYS_TERMIOS_GET = 65,
	SYS_TERMIOS_SET = 66,
	SYS_SELFHOST_STATUS = 67,
	SYS_RENAME = 68,
	SYS_RMDIR = 69,
	SYS_FSTAT = 70,
	SYS_FSYNC = 71,
	SYS_MOUNT = 72,
	SYS_UMOUNT = 73,
	SYS_SYNC = 74,
};

u64 syscall_dispatch(u64 number, u64 arg0, u64 arg1, u64 arg2, u64 arg3);
int syscall_copyin(void *dst, const void *user_src, usize size);
int syscall_copyout(void *user_dst, const void *src, usize size);
int syscall_copyinstr(char *dst, usize dst_size, const char *user_src);

#endif
